### ISSUE TITLE
测试不成功

### ISSUE THREAD

**Issue by Qifcn** [reuixiy/hugo-theme-meme#10]
你好作者，我测试你这个主题不知道是什么原因预览不成功，已附上截图
```
$ hugo.exe server
Building sites … ERROR 2019/09/21 22:37:13 Failed to read Git log: fatal: Not a           git repository (or any of the parent directories): .git
ERROR 2019/09/21 22:37:13 Transformation failed: TOCSS: failed to transform "sty          les/main-rendered.scss" (text/x-scss): this feature is not available in your cur          rent Hugo version, see https://goo.gl/YMrWcn for more information
ERROR 2019/09/21 22:37:14 Transformation failed: TOCSS: failed to transform "sty          les/main-rendered.scss" (text/x-scss): this feature is not available in your cur          rent Hugo version, see https://goo.gl/YMrWcn for more information
Total in 1286 ms
Error: Error building site: logged 3 error(s)
```

![QQ截图20190921225913](https://user-images.githubusercontent.com/34029055/65375046-8afbc500-dcc3-11e9-8231-4f07ff3ed6e3.png)

**Comment by boholder** [comment]
https://goo.gl/YMrWcn
->
https://gohugo.io/troubleshooting/faq/#i-get-tocss-this-feature-is-not-available-in-your-current-hugo-version

As err msg said.  
You need a extra installation for this featrue.

**Comment by reuixiy** [comment]
@Qifcn 你好，

感谢你尝试 MemE :smile_cat: ～

正如 @boholder 所说，你需要安装扩展版的 Hugo 以解决这个问题，即 Releases 页面以 `hugo_extended` 开头的版本，比如 `hugo_extended_0.58.3_Windows-64bit.zip`。

此外，对于第一个报错，如果你的博客不是一个 Git 仓库（没有 `git init` 过），请将 `config.toml` 中的 `enableGitInfo` 改为 `false`，即 `enableGitInfo = false`。
