### ISSUE TITLE
自定义SVG图标无法使用

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#101]
我在博客站点的`date`文件夹里面已经创建了`SVG.toml`并添加了自定义图标。

但是无论在本地`hugo server`还是进行部署后，都无法应用自定义图标，图标本身的SVG代码并没有问题，不知道这是不是主题的问题？

希望看到的朋友可以尝试一下自己的看新增的图标能否使用，也可能是我自己的问题，不过目前还没发现问题在哪？谢谢各位！🎈

Hugo Version：0.68.3
MemE Version：4.3.1

**Comment by dawnow** [comment]
使用主题自带的图标`theme-meme-date-SVG.toml`就没问题，可以正常显示。

**Comment by reuixiy** [comment]
https://github.com/dawnow/blog/blob/c0955d3a34a55ca4c6c237ab6830c2d21f3895b6/config.toml#L331

**Comment by dawnow** [comment]
> https://github.com/dawnow/blog/blob/c0955d3a34a55ca4c6c237ab6830c2d21f3895b6/config.toml#L331

不，这个是品牌栏的SVG，我指的是例如主页页脚年份跟作者之间的地方、菜单栏的图标这种，使用自己添加的图标会不显示。

**Comment by reuixiy** [comment]
Okay...

https://github.com/dawnow/blog/tree/master/date

It's **data**, not **date**

**Comment by dawnow** [comment]
我*，我要被我自己笑死了，太马虎了我，得多向reuixiy学习，谢谢你！🍔
