### ISSUE TITLE
lang-switcher do not appears

### ISSUE THREAD

**Issue by guinuxbr** [reuixiy/hugo-theme-meme#104]
I need some help. Whats is the proper way to make the "lang-switcher" works?
I have the following setup:
For better organization, I have one folder for each idiom at the "content" folder, just like this:

|   content||
|---|---|
| en | pt-br |
| about | about |
| posts | posts |

Inside the language folder I have the .md files preceded by the language code, for instance:

- folder **en**/posts/test-01.**en**.md
- folder **pt-br**/posts/test-01.**pt-br**.md

In config.toml I have:
```
##########################################
# Site Settings
languageCode = "pt-br"

# i18n
defaultContentLanguage = "pt-br"
defaultContentLanguageInSubdir = true

[[menu.main]]
        weight = 7
        identifier = "lang-switcher"
    [[languages.pt-br.menu.main]]
        weight = 7
        identifier = "lang-switcher"

[languages]
  [languages.en] 
    contentDir = "content/en" # English
    languageName = "EN"
    weight = 10
  [languages.pt-br]
    contentDir = "content/pt-br" # Brazilian Portuguese
    languageName = "PT-BR"
    weight = 20
```

I can access directly both http://localhost:1313/en/ and http://localhost:1313/pt-br/, but the "lang-switcher" do not appears.

Am I doing something wrong?

**Comment by reuixiy** [comment]
You need to set [`enableLangToggle`](https://github.com/reuixiy/hugo-theme-meme/blob/0d14242bfe588efe12c0c11d3cb200c9d45e4eda/config-examples/en/config.toml#L1225) to `true`.

Also, you can delete these lines:

```diff
[[menu.main]]
        weight = 7
        identifier = "lang-switcher"
-    [[languages.pt-br.menu.main]]
-        weight = 7
-        identifier = "lang-switcher"
```

Hugo can inherits the default language's params, so there is no need to repeat that unless you want to assign a different value.

And you can also delete the lang suffixes in your post's filename if you have already organized your content by sub-directories, for instance:

- folder **en**/posts/test-01.md
- folder **pt-br**/posts/test-01.md

**Comment by guinuxbr** [comment]
It works! I totally forgot about the toggle, my mistake, sorry. :disappointed: 

By the way, if I delete the suggested line, the toggle disappear.

Anyway, I keep the lines and everything is working as expected.

Thank you!
