### ISSUE TITLE
IPhone显示错误（系统12.0.1）

### ISSUE THREAD

**Issue by FFRaycoder** [reuixiy/hugo-theme-meme#109]
1.代码块字体
![803587FE618DDF044A094105572CEE05](https://user-images.githubusercontent.com/58381667/78895126-df6c6380-7aa0-11ea-8724-17aed7b2ec17.png)
2.文字显示
![423BC6C55E26154C088B9F7E49CE05C2](https://user-images.githubusercontent.com/58381667/78895160-eabf8f00-7aa0-11ea-8d4d-dffb31bc8cbf.png)

**Comment by reuixiy** [comment]
见 https://github.com/reuixiy/io-oi.me/issues/52#issuecomment-586512359

**Comment by FFRaycoder** [comment]
第二个的确是网络字体原因。但是第一个还没有解决。

**Comment by wzhix** [comment]
思源宋体显示问题应该是 Safari 本身的问题，可以看下这个 https://github.com/google/fonts/issues/1913。
