### ISSUE TITLE
In safari, the style breakdown

### ISSUE THREAD

**Issue by ZhaoTim** [reuixiy/hugo-theme-meme#11]
Hi,
I love the hugo theme , and I have used it , my domain is [HOME](https://zhaomeicheng.com), and I find in safari, the style is something wrong , but I can't figure it out ...plz help me !
here is the screenshot....
![pic](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F8288b666-b376-4e38-902b-72906bac47de%2FUntitled.png?table=block&id=a063b768-8068-4536-9e5b-38d728d2fac9&width=6540&cache=v2)

**Comment by reuixiy** [comment]
Hi @ZhaoTim,

Thank you for trying MemE! :smile_cat:

The problem is caused by the glyph-correction font, and I just submitted a commit to solve that.

Please update MemE and test again.

**Comment by ZhaoTim** [comment]
> Hi @ZhaoTim,
> 
> Thank you for trying MemE! 😸
> 
> The problem is caused by the glyph-correction font, and I just submitted a commit to fix that.
> 
> Please update MemE and test again.

thx!!! and I've updated it ! such a nice guy/girl you are!!!
