### ISSUE TITLE
如果使用categories分类博客文章：

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#112]
那么如何使文章即在分类A里面又在分类B里面呢？因为有时候可能这篇文章涉及了两个分类的内容，又不需要再去细化一个类别，这时该如何操作呢？

**Comment by wzhix** [comment]
Hugo 和 MemE 支持「系列」的分类方式：https://gohugo.io/content-management/taxonomies/#example-adding-a-custom-taxonomy-named-series

在 Front Matter 中配置：
```
categories: ["技术分类"]
series: ["技术系列"]
```

**Comment by reuixiy** [comment]
@dawnow 看了下你的博客，你的 categories 只有一级，并无多级的树状分类。

所以，你将 categories 当 tags 用就行了，`categories: ["a", "b"]`。

然后，修改一下 [`categoryDelimiter`](https://github.com/reuixiy/hugo-theme-meme/blob/3754acc74c03c33003fc3d9755a550510ec05683/config-examples/zh-cn/config.toml#L713-L714) 分隔符，将默认的 `/` 修改为 ` | ` 或 ` · `。

这样，极简页脚的显示就由 `a/b` 变为 `a | b` 或 `a · b`，给读者展示的逻辑关系就由纵向的父子变成横向的并列。

当然，你也可以尝试 @wzhix 的方法，一种盒子之外的「高维」操作 :)

**Comment by dawnow** [comment]
@reuixiy 我先按照你的方法进行了尝试，然后我本地预览了一下，分类页面如下图所示：

![image](https://user-images.githubusercontent.com/46470508/79035922-895d0480-7bf5-11ea-8406-1924f01c487f.png)


为什么这个列表里会出现两个重复的分类项呢？（我有一篇文章既在Film里面又在Tech里面）
我以为还会像之前这样，只是后面多了一个数字。

**Comment by reuixiy** [comment]
这种布局是给多级的树状分类用的，如果你将 categories 当 tags 用的话，将 [`enableTree`](https://github.com/reuixiy/hugo-theme-meme/blob/3754acc74c03c33003fc3d9755a550510ec05683/config-examples/zh-cn/config.toml#L370) 关闭。

**Comment by dawnow** [comment]
> 这种布局是给多级的树状分类用的，如果你将 categories 当 tags 用的话，将 [`enableTree`](https://github.com/reuixiy/hugo-theme-meme/blob/3754acc74c03c33003fc3d9755a550510ec05683/config-examples/zh-cn/config.toml#L370) 关闭。

嗯，这样是OK了，就是无法关闭标题显示了，也就是无法以一个folder的逻辑进行展示了。它会以一个完整了列表进行展示，只是进行了归类。要是也能进行折叠就好了😅（不可兼得

**Comment by reuixiy** [comment]
你提到 folder，那么你在系统的文件浏览器中，可以将**一个文件**同时放在两个 folder 吗？类比过来，在博客中，如果你要将 categories 当作 folder 来组织文章，那么一篇文章可以同时属于两个 categories 吗？

事实上，我也一直困于分类，在我的博客的《[浅谈博客文章的两种分类方式](https://io-oi.me/tech/categories+tags/)》和《[Hugo 与 Hexo 的异同之分类方式和组织方式](https://io-oi.me/tech/hugo-vs-hexo/#分类方式和组织方式)》中看到我的纠结和思考。

现在的话，我建议选择一个主要维度作为博客的「范畴」，比如 categories（或者 Hugo 中的 sections），并将之作为菜单栏展示给读者，比如：

- 简单的二分法，生活 | 技术
- 按文体或文类，诗歌 | 笔记 | 随笔
- ……

然后，如果不同 categories 之间还有相同之处，则使用 tags（或者 Hugo 中的任何 *Taxonomies*）将之联系起来。

世界也许是多维的，但时间是一维的。至少作为一个人，我们只能在一个时间看到一个地点，你不可能**同时**身处两地，你不可能因果**同时**，那样就逻辑混乱了（也即无组织）。所以，还是基于现有的范畴组织，然后通过时间的流动实现多维组织。

P.S. 又胡言乱语了🙃

**Comment by dawnow** [comment]
@reuixiy 很有道理，categories（section）就相当于是两条不同的平行的时间线，它们都在往前走（尽管你作为“上帝”可以同时推动两条时间线）。而tags就是联系两条时间线中某个节点的介质。（不知道可以这样理解🐴）你这个回复已经思考的很到位了。谢谢你！😀
