### ISSUE TITLE
windows 安装出现错误

### ISSUE THREAD

**Issue by Cheene** [reuixiy/hugo-theme-meme#114]
![image](https://user-images.githubusercontent.com/26854813/79248048-ea166680-7ead-11ea-9eab-ef1887c5ac6d.png)
Error building site: TOCSS: failed to transform "en/styles/main-rendered.scss" (text/x-scss): resource "scss/scss/main.scss_51" not found in file cache

**Comment by FFRaycoder** [comment]
善用搜索，你有安装拓展版hugo吗？

**Comment by reuixiy** [comment]
如 @FFRaycoder 所言，请安装扩展版（extended）Hugo。

**Comment by Cheene** [comment]
谢谢，是前期工作准备不足，花掉了好多的时间。
