### ISSUE TITLE
分页的页码

### ISSUE THREAD

**Issue by so1ve** [reuixiy/hugo-theme-meme#115]
meme是一个很好的主题，但是Archive页面没有文章总数的统计。能否告诉一下Archive页面的模板在哪里？谢谢！

**Comment by FFRaycoder** [comment]
以及建议在翻页时在前一页与后一页的按钮间增加一键跳转功能。

**Comment by reuixiy** [comment]
> 模板在哪里？

https://github.com/reuixiy/hugo-theme-meme/blob/master/layouts/_default/list.html

> 一键跳转功能

你是指页码吧？

**Comment by FFRaycoder** [comment]
> > 模板在哪里？
> 
> https://github.com/reuixiy/hugo-theme-meme/blob/master/layouts/_default/list.html
> 
> > 一键跳转功能
> 
> 你是指页码吧？

是。（原谅我语文不好表达不清楚:dog:）
