### ISSUE TITLE
header自适应

### ISSUE THREAD

**Issue by FFRaycoder** [reuixiy/hugo-theme-meme#117]
我又来提Issue了，很抱歉给reuixiy带来这么多麻烦:sweat_smile:

如下，如果导航栏超过七个以上的链接，就会有一部分超出header范围。
![image](https://user-images.githubusercontent.com/58381667/79517647-5e553380-8081-11ea-8669-874b1286dfce.png)

**Comment by reuixiy** [comment]
修改这 https://github.com/reuixiy/hugo-theme-meme/blob/86bfc7748271b2e6c3e573c2555b0a85af723703/config-examples/zh-cn/config.toml#L250

**Comment by FFRaycoder** [comment]
此言极是，我的锅 不过还是希望可以自适应，希望可以加上。 Issue close.
