### ISSUE TITLE
中文版出现问题

### ISSUE THREAD

**Issue by iYIJUN** [reuixiy/hugo-theme-meme#118]
hugo server出错：
Error: Error building site: TOCSS: failed to transform "zh/styles/main-rendered.scss" (text/x-scss): resource "scss/scss/main.scss_a059ebc49e8302e6cfbf0e02020b9d85" not found in file cache

**Comment by he-sb** [comment]
用的是 hugo extend 还是 hugo ，本主题需要 hugo 扩展版

**Comment by iYIJUN** [comment]
> 用的是 hugo extend 还是 hugo ，本主题需要 hugo 扩展版

**Comment by iYIJUN** [comment]
> 用的是 hugo extend 还是 hugo ，本主题需要 hugo 扩展版

可能就是這原因了(/ω＼)晚上我試試
