### ISSUE TITLE
Utterances 生产环境评论加载不出来

### ISSUE THREAD

**Issue by georgehao** [reuixiy/hugo-theme-meme#119]
# 是否开启（全局设置）
    enableMermaid = false
    # 说明：文章的 Front Matter 中的 `mermaid`
    #      的优先级高于此处

    ######################################
    # 评论

    # 说明：仅在生产环境（production）下渲染

    # 是否开启（全局设置）
    enableComments = true 
    # 说明：文章的 Front Matter 中的 `comments`
    #      的优先级高于此处

    ## Disqus
    enableDisqus = false
    disqusShortname = ""

    ## Valine
    enableValine = false
    valineAppId = ""
    valineAppKey = ""
    valinePlaceholder = "Just go go"
    valineNotify = false
    valineVerify = false
    valinePath = ""
    valineAvatar = "mm"
    valineMeta = ["nick", "mail", "link"]
    valinePageSize = 10
    valineLang = "zh-cn"
    valineVisitor = false
    valineHighlight = true
    avatarForce = false
    valineRecordIP = false
    valineServerURLs = ""
    # 说明：https://valine.js.org/

    ## Utterances
    enableUtterances = true
    utterancesRepo = "georgehao/blog"
    utterancesIssueTerm = "pathname"
    utterancesTheme = "github-light"
    utterancesThemeDark = "photon-dark"
    utterancesLabel = ""
    # 说明：https://utteranc.es/

![image](https://user-images.githubusercontent.com/6947653/79634129-3528c600-819b-11ea-8f51-ccae5e7b5a80.png)

我的博客:
https://www.haohongfan.com/post/2020-03-11-go-cache/

**Comment by reuixiy** [comment]
见 https://github.com/reuixiy/hugo-theme-meme/issues/83#issuecomment-600942729
