### ISSUE TITLE
无法安装 PWA 应用

### ISSUE THREAD

**Issue by Xuezenghuigithub** [reuixiy/hugo-theme-meme#120]
reuixiy 你好，我按照《[利用 Workbox 实现博客的 PWA](https://io-oi.me/tech/pwa-via-workbox/)》一文做了相关配置，已经深深体会到了 ServiceWorker 的优越性👍（后悔没有早点尝试...）。

<img width="1721" alt="requests" src="https://user-images.githubusercontent.com/40421053/80077220-c626e500-857f-11ea-9f8f-972cec5d817d.png" width=400>

但是浏览器的导航栏并没有出现 + 符号让我来安装应用，不知道是什么缘故呢？

**Comment by ayalhw** [comment]
你看下浏览器ServiceWork选项卡，是不是显示有不合适的
另外如果是火狐的话是不显示加号的

**Comment by Xuezenghuigithub** [comment]
@ayalhw 应该不是浏览器的问题，我使用的 Chrome，Console、Network 面板里也没有什么错误，而且我安装作者博客的 PWA 功能是没问题的。

**Comment by ayalhw** [comment]
![图片](https://user-images.githubusercontent.com/43064781/80078312-50bc1400-8581-11ea-88f3-d85d67c21d40.png)

这不是有提示错误吗?

**Comment by FFRaycoder** [comment]
图像太小了

**Comment by ayalhw** [comment]
我记得作者的文章里有说去生成不同大小的图片

**Comment by Xuezenghuigithub** [comment]
是的，差了 4px，多谢两位。（原来 App Manifest 在这里调试🥺
