### ISSUE TITLE
页面更新提醒栏鼠标指针样式

### ISSUE THREAD

**Issue by Xuezenghuigithub** [reuixiy/hugo-theme-meme#122]
希望可以点击的内容的  `cursor` 属性为 `pointer`，而不是现在的默认箭头，并且「点击刷新」四字的 `cursor` 值为 `text`，不符常理。

**Comment by denalon** [comment]
😁请问，怎么在meme主题里加入bootstrap，我把代码加上去就出现页面有遮挡，显示bug。

**Comment by reuixiy** [comment]
@Xuezenghuigithub Emmm，还在考虑...

@denalon 麻烦提个新的 Issue，并提供在线地址。

**Comment by reuixiy** [comment]
现在想了想，`point` 看起来像链接，点击有种貌似要跳转的感觉，所以还是默认的好一点大概。

当然，现在这个不完全的通知已经移除了……以后应该会为 PWA 设计新的通知样式，https://github.com/reuixiy/io-oi.me/issues/108
