### ISSUE TITLE
Feature request - Bottom social media icons

### ISSUE THREAD

**Issue by guinuxbr** [reuixiy/hugo-theme-meme#123]
Is it possible to add the possibility to include some icons of social media contacts at the bottom?

Maybe with some Font Awesome integration or anything you may prefer.

**Comment by he-sb** [comment]
The theme already included this feature, check out the `config.toml` at [this block](https://github.com/reuixiy/hugo-theme-meme/blob/master/config-examples/en/config.toml#L1091-L1111)

**Comment by guinuxbr** [comment]
> The theme already included this feature, check out the `config.toml` at [this block](https://github.com/reuixiy/hugo-theme-meme/blob/master/config-examples/en/config.toml#L1091-L1111)

I'm not talking about the "share posts" section. I mean icons at the footer. Maybe I did not express myself very well, sorry for this.
Here goes an example: https://i.imgur.com/r2VvLyA.png

**Comment by he-sb** [comment]
> 
> 
> > The theme already included this feature, check out the `config.toml` at [this block](https://github.com/reuixiy/hugo-theme-meme/blob/master/config-examples/en/config.toml#L1091-L1111)
> 
> I'm not talking about the "share posts" section. I mean icons at the footer. Maybe I did not express myself very well, sorry for this.
> Here goes an example: https://i.imgur.com/r2VvLyA.png

If you look at the block of code which I mentioned above more carefully, you would find out there are icons you configured at the page's footer.

![图片](https://user-images.githubusercontent.com/26474615/80365990-0f966d80-88bb-11ea-9822-09e83490f91b.png)

The example above is from [here](https://io-oi.me/en/about/)

**Comment by guinuxbr** [comment]
Sorry, but I think that you have misunderstood me.
Following your example, here goes what I'm talking about:
https://i.imgur.com/LH2AAVM.png

**Comment by reuixiy** [comment]
@he-sb, Hmmmm, hold on... I think you misunderstood something... The screenshot you uploaded is actually `post-share`, not what @guinuxbr asked for.

@guinuxbr Your request sounds reasonable, I'll take a look.

**Comment by he-sb** [comment]
> 
> 
> Sorry, but I think that you have misunderstood me.
> Following your example, here goes what I'm talking about:
> https://i.imgur.com/LH2AAVM.png

Sorry, I did misunderstood you.

You want the icons shown at the bottom of the page, not the bottom of the article.

**Comment by guinuxbr** [comment]
@reuixiy, thank you for your attention.

@he-sb, no problem! This is exactly what I meant. Thank you anyway! :smiley:

**Comment by reuixiy** [comment]
@guinuxbr Just supported this feature! Please [update theme](https://github.com/reuixiy/hugo-theme-meme#update-meme) to test it!

**Comment by guinuxbr** [comment]
After a little adjustment in my personal CSS, it worked perfectly.
Thank you!
