### ISSUE TITLE
我在本地无法启动运行，提示报错，求大神帮助，感谢！

### ISSUE THREAD

**Issue by bao-wei** [reuixiy/hugo-theme-meme#124]
`Error: Error building site: TOCSS: failed to transform "zh/styles/main-rendered.scss" (text/x-scss): resource "scss/scss/main.scss_a059ebc49e8302e6cfbf0e02020b9d85" not found in file cache`

**Comment by FFRaycoder** [comment]
怎么又来一个不看readme的，，，作者都说了要用拓展版hugo

**Comment by bao-wei** [comment]
你好FFRaycoder ，感谢你的回复，实在不好意思，我第一次搭博客，还不太会，我之前看readme没看到，请问扩展版安装也是一样的安装吗？也是在官网下载吗？感谢你的回复

**Comment by FFRaycoder** [comment]
嗯对，release页<https://github.com/gohugoio/hugo/releases/tag/v0.69.2>里边最下面有extended的就是，根据系统下载

**Comment by bao-wei** [comment]
> 怎么又来一个不看readme的，，，作者都说了要用拓展版hugo

你好FFRaycoder ，感谢你的回复，实在不好意思，我第一次搭博客，还不太会，我之前看readme没看到，请问扩展版安装也是一样的安装吗？也是在官网下载吗？感谢你的回复

**Comment by FFRaycoder** [comment]
啥，你根据系统下载呀:smirk:

**Comment by bao-wei** [comment]
> 啥，你根据系统下载呀😏

好的，感谢感谢！！！多谢提醒

**Comment by bao-wei** [comment]
> 啥，你根据系统下载呀😏

![image](https://user-images.githubusercontent.com/63962745/80353553-1a93d280-88a8-11ea-87f5-301658cb27f8.png)
不好意思，还要再请教你一下😂请问我windows系统下载这个是扩展版吗?

**Comment by FFRaycoder** [comment]
不是

**Comment by FFRaycoder** [comment]
![image](https://user-images.githubusercontent.com/58381667/80353760-621a5e80-88a8-11ea-8ca1-a79c3917e810.png)
这个

**Comment by bao-wei** [comment]
> ![image](https://user-images.githubusercontent.com/58381667/80353760-621a5e80-88a8-11ea-8ca1-a79c3917e810.png)
> 这个

好的，非常感谢！！！

**Comment by FFRaycoder** [comment]
嗯

**Comment by bao-wei** [comment]
> 嗯

不好意思大神，又来打搅你了，还需要向你求助最后两个问题😂，还麻烦你在有空时指点一下：
![image](https://user-images.githubusercontent.com/63962745/80359895-19b36e80-88b1-11ea-9e1a-a725f3dd8ef3.png)
- 请问上图的诗句我该如何填如？我直接写入内容不行，在文件里面没有找到可以修改的地方；

![image](https://user-images.githubusercontent.com/63962745/80360215-92b2c600-88b1-11ea-8a9e-9f7418b473c3.png)
![image](https://user-images.githubusercontent.com/63962745/80360241-9fcfb500-88b1-11ea-86f2-cd46454e3390.png)
- 背景颜色位置这个地方的参数我修改了以后在预览网页中刷新了页没有变化，我按照说明网址中的去看方法，但由于没有CSS语言的基础，不是很明白，请问我直接修改原来参数无法改变颜色吗？

实在不好意思，向你求助最后两个问题，十分感谢！

**Comment by FFRaycoder** [comment]
> 背景颜色位置这个地方的参数我修改了以后在预览网页中刷新了页没有变化
可以修改的，我这里有效
![image](https://user-images.githubusercontent.com/58381667/80432272-4786ca80-8926-11ea-84e1-d530cb56c381.png)

**Comment by FFRaycoder** [comment]
> > 嗯
> 
> 不好意思大神，又来打搅你了，还需要向你求助最后一个问题😂，还麻烦你在有空时指点一下：
> ![image](https://user-images.githubusercontent.com/63962745/80360215-92b2c600-88b1-11ea-8a9e-9f7418b473c3.png)
> ![image](https://user-images.githubusercontent.com/63962745/80360241-9fcfb500-88b1-11ea-86f2-cd46454e3390.png)
> 
> * 背景颜色位置这个地方的参数我修改了以后在预览网页中刷新了页没有变化，我按照说明网址中的去看方法，但由于没有CSS语言的基础，不是很明白，请问我直接修改原来参数无法改变颜色吗？
> 
> 实在不好意思，向你求助最后一个问题，十分感谢！

嗯看到你的博客了，关于博客自动部署这个我写了篇文章，欢迎来看。
[Travis CI自动部署Hugo博客](https://www.raycoder.me/p/travis-ci-automatically-deploys-hugo-blog/)
而且你博客的字体使用谷歌的源，国内访问不了。

**Comment by bao-wei** [comment]
> > > 嗯
> > 
> > 
> > 不好意思大神，又来打搅你了，还需要向你求助最后一个问题😂，还麻烦你在有空时指点一下：
> > ![image](https://user-images.githubusercontent.com/63962745/80360215-92b2c600-88b1-11ea-8a9e-9f7418b473c3.png)
> > ![image](https://user-images.githubusercontent.com/63962745/80360241-9fcfb500-88b1-11ea-86f2-cd46454e3390.png)
> > 
> > * 背景颜色位置这个地方的参数我修改了以后在预览网页中刷新了页没有变化，我按照说明网址中的去看方法，但由于没有CSS语言的基础，不是很明白，请问我直接修改原来参数无法改变颜色吗？
> > 
> > 实在不好意思，向你求助最后一个问题，十分感谢！
> 
> 嗯看到你的博客了，关于博客自动部署这个我写了篇文章，欢迎来看。
> [Travis CI自动部署Hugo博客](https://www.raycoder.me/p/travis-ci-automatically-deploys-hugo-blog/)
> 而且你博客的字体使用谷歌的源，国内访问不了。

谢谢大神的回复，那我的字体是不是更改配置文件中的字体链接就可以了？但是我看主题作者说目前仅支持google font的链接，我去找其他的链接可行吗？
![image](https://user-images.githubusercontent.com/63962745/80446821-6e56f800-894a-11ea-86b7-dd03e2061c5d.png)

**Comment by FFRaycoder** [comment]
> > > > 嗯
> > > 
> > > 
> > > 不好意思大神，又来打搅你了，还需要向你求助最后一个问题😂，还麻烦你在有空时指点一下：
> > > ![image](https://user-images.githubusercontent.com/63962745/80360215-92b2c600-88b1-11ea-8a9e-9f7418b473c3.png)
> > > ![image](https://user-images.githubusercontent.com/63962745/80360241-9fcfb500-88b1-11ea-86f2-cd46454e3390.png)
> > > 
> > > * 背景颜色位置这个地方的参数我修改了以后在预览网页中刷新了页没有变化，我按照说明网址中的去看方法，但由于没有CSS语言的基础，不是很明白，请问我直接修改原来参数无法改变颜色吗？
> > > 
> > > 实在不好意思，向你求助最后一个问题，十分感谢！
> > 
> > 
> > 嗯看到你的博客了，关于博客自动部署这个我写了篇文章，欢迎来看。
> > [Travis CI自动部署Hugo博客](https://www.raycoder.me/p/travis-ci-automatically-deploys-hugo-blog/)
> > 而且你博客的字体使用谷歌的源，国内访问不了。
> 
> 谢谢大神的回复，那我的字体是不是更改配置文件中的字体链接就可以了？但是我看主题作者说目前仅支持google font的链接，我去找其他的链接可行吗？
> ![image](https://user-images.githubusercontent.com/63962745/80446821-6e56f800-894a-11ea-86b7-dd03e2061c5d.png)

Google fonts格式即可

**Comment by reuixiy** [comment]
> 但是我看主题作者说目前仅支持google font的链接，我去找其他的链接可行吗？

修改为镜像地址即可，即将链接中的 `fonts.googleapis.com` 替换即可，比如替换为[烧饼博客](https://sb.sb/)提供的 `loli.net`。

但前段时间好像有读者反馈说 Google 的在国内能用且比镜像的还要快，但我也没测试，也不清楚。

**Comment by FFRaycoder** [comment]
> > 但是我看主题作者说目前仅支持google font的链接，我去找其他的链接可行吗？
> 
> 修改为镜像地址即可，即将链接中的 `fonts.googleapis.com` 替换即可，比如替换为[烧饼博客](https://sb.sb/)提供的 `loli.net`。
> 
> 但前段时间好像有读者反馈说 Google 的在国内能用且比镜像的还要快，但我也没测试，也不清楚。

国内现在是可以访问，但是广电就:trollface:
