### ISSUE TITLE
小白请教：如何使内容在网页居中，同时也不影响markdown的使用？

### ISSUE THREAD

**Issue by bao-wei** [reuixiy/hugo-theme-meme#125]
我看有的主题可以使用{{% center %}}这样的shortcode，但我在meme主题中无法使用，是我哪个地方没有设置对吗？

**Comment by reuixiy** [comment]
去你说的这个主题的 `layouts/shortcodes/` 下将相应文件借鉴过来即可。

**Comment by FFRaycoder** [comment]
自定义css
