### ISSUE TITLE
svg图标在Firesfox和MicrosoftEdge无法正常显示问题

### ISSUE THREAD

**Issue by Gaotianhe** [reuixiy/hugo-theme-meme#126]
如下图所示：
![image](https://user-images.githubusercontent.com/52186032/80896736-06c2f300-8d24-11ea-90fc-db6dd1f309a1.png)

问题描述：
svg图标过大，填充到整个网页页面，导致其他部件不能正常渲染。这个问题，出现在Firefox和Edge，Google Chrome显示正常。Android移动端显示正常

**Comment by ayalhw** [comment]
之前在我这里偶现，并且Firefox，Chrom*都曾复现过，个人猜测和网络有关
（我在手机的Chromium上成功复现过几次

**Comment by Gaotianhe** [comment]
> 之前在我这里偶现，并且Firefox，Chrom*都曾复现过，个人猜测和网络有关
> （我在手机的Chromium上成功复现过几次

我使用Cloudflare解析域名，会不会是这个原因？我以前在阿里云解析，没见过这种情况

**Comment by ayalhw** [comment]
![图片](https://user-images.githubusercontent.com/43064781/80896904-de3bf880-8d25-11ea-8d6f-aeda7b78bb76.png)

**Comment by ayalhw** [comment]
> 我使用Cloudflare解析域名，会不会是这个原因？我以前在阿里云解析，没见过这种情况

你CF是不是开了js/css压缩？

**Comment by Gaotianhe** [comment]
![image](https://user-images.githubusercontent.com/52186032/80897010-1abc2400-8d27-11ea-9ff7-63976189bf45.png)

是它的原因吗？我不知道，它可能是默认开启的，我没有操作过

**Comment by ayalhw** [comment]
> ![image](https://user-images.githubusercontent.com/52186032/80897010-1abc2400-8d27-11ea-9ff7-63976189bf45.png)
> 
> 是它的原因吗？我不知道，它可能是默认开启的，我没有操作过

不是，我想的可能是这个造成的问题
![图片](https://user-images.githubusercontent.com/43064781/80897052-8d2d0400-8d27-11ea-9405-3f09bf65b2e7.png)

**Comment by Gaotianhe** [comment]
![image](https://user-images.githubusercontent.com/52186032/80897128-3411a000-8d28-11ea-8b9b-159d134cb831.png)

我3个都勾选了，这不是我弄的 :joy:

**Comment by ayalhw** [comment]
> ![image](https://user-images.githubusercontent.com/52186032/80897128-3411a000-8d28-11ea-8b9b-159d134cb831.png)
> 
> 我3个都勾选了，这不是我弄的 joy

关掉，然后清除缓存试试

**Comment by Gaotianhe** [comment]
清除缓存指的是 浏览器缓存 还是 Cloudflare 缓存啊？

**Comment by ayalhw** [comment]
> 清除缓存指的是 浏览器缓存 还是 Cloudflare 缓存啊？

都清理下吧

**Comment by Gaotianhe** [comment]
可以了：
<img width="960" alt="yidajiabei" src="https://user-images.githubusercontent.com/52186032/80897253-80a9ab00-8d29-11ea-9507-4be3fec229a7.png">

Edge和Firefox都恢复正常了

谢谢你！
