### ISSUE TITLE
Android phone chrome browser multilingual icon cannot be displayed

### ISSUE THREAD

**Issue by Gaotianhe** [reuixiy/hugo-theme-meme#128]
Show in system browser:
![博客](https://user-images.githubusercontent.com/52186032/81137036-e8612f80-8f8f-11ea-89e2-cd84392d36b1.png)

Show in chrome browser:
![1博客](https://user-images.githubusercontent.com/52186032/81137062-fca52c80-8f8f-11ea-804d-550525f71aa0.png)

Can I use letters instead?

**Comment by he-sb** [comment]
You can edit [this parameter](https://github.com/reuixiy/hugo-theme-meme/blob/master/config-examples/en/config.toml#L262), by increasing its value appropriately.

**Comment by Gaotianhe** [comment]
> You can edit [this parameter](https://github.com/reuixiy/hugo-theme-meme/blob/master/config-examples/en/config.toml#L262), by increasing its value appropriately.

It's fine. Thank you! I change it to 10em, just like this picture:
![image](https://user-images.githubusercontent.com/52186032/81142561-8eb63080-8fa2-11ea-9217-dccbbf3dd7c2.png)

It used to be 9em

**Comment by reuixiy** [comment]
@Gaotianhe Hmm, I don't really understand what problem you have.

The multilingual dropdown menu or language list will be displayed when there is a [`mouseover`](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseover_event) event. And obviously there is no mouse on the phone... You may have to *touch* it for a moment if you want to toggle it on Chrome Mobile.

> Can I use letters instead?

Sure! Just modify the `languageName` param!

**Comment by he-sb** [comment]
> 
> 
> @Gaotianhe Hmm, I don't really understand what problem you have.
> 
> The multilingual dropdown menu or language list will be displayed when there is a [`mouseover`](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseover_event) event. And obviously there is no mouse on the phone... You may have to _touch_ it for a moment if you want to toggle it on Chrome Mobile.
> 
> > Can I use letters instead?
> 
> Sure! Just modify the `languageName` param!

In above case, the problem is that when the dropdown menu expanded, the buttons in the bottom would not be displayed properly. It's because the `navHeight` parameter's value is not large enough. Now he already fixed it.
