### ISSUE TITLE
如何默认加载 Valine 评论

### ISSUE THREAD

**Issue by XeonChow** [reuixiy/hugo-theme-meme#129]
已成功启用 Valine 评论功能，希望可以默认直接加载评论，按照这个 [issue](https://github.com/reuixiy/hugo-theme-meme/issues/83#issuecomment-600648603) 里作者的回答，无论是在 `~/blog/assets/js/custom.js` 里还是在 `~/blog/themes/meme/assets/js/custom.js` 里添加以下内容
```
if (commentsToggle !== null) {
    loadComments();
    commentsToggle.style = "display: none";
}
```
均无法默认加载评论，希望作者可以解答，谢谢。

**Comment by FFRaycoder** [comment]
直接在comments.html里面partial

**Comment by XeonChow** [comment]
@FFRaycoder 可否更详细一点，我找到了 `~/themes/meme/layouts/partials/components/comments.html` 这个文件，里面默认内容如下
```
{{ if and (.Params.comments | default .Site.Params.enableComments) (eq hugo.Environment "production") }}
    {{ if or (in .Site.Params.mainSections .Section) .Params.comments }}

        <div class="load-comments">
            <div id="load-comments">{{ i18n "loadComments" }}</div>
        </div>

        {{ if .Site.Params.enableDisqus }}
            <div id="disqus_thread"></div>
        {{ end }}

        {{ if .Site.Params.enableValine }}
            <div id="vcomments"></div>
        {{ end }}

        {{ if .Site.Params.enableUtterances }}
            <div id="utterances"></div>
        {{ end }}

    {{ end }}
{{ end }}
```
请问是修改这个文件吗，以及如何修改。谢谢。

**Comment by FFRaycoder** [comment]
我很暴躁
```html
{{ if and (.Params.comments | default .Site.Params.enableComments) (eq hugo.Environment "production") }}
    {{ if or (in .Site.Params.mainSections .Section) .Params.comments }}

        
		<!--<div class="load-comments">
            <div id="load-comments">{{ i18n "loadComments" }}</div>
        </div>-->
		

        {{ if .Site.Params.enableDisqus }}
            <div id="disqus_thread"></div>
        {{ end }}

        {{ if .Site.Params.enableValine }}
            <div id="vcomments"></div>
        {{ end }}

        {{ if .Site.Params.enableUtterances }}
            <div id="utterances"></div>
        {{ end }}

    {{ end }}
{{ end }}
```

**Comment by XeonChow** [comment]
@FFRaycoder 多谢，尽管作者不推荐直接改主题代码，但确实解决了问题，再次感谢！

**Comment by reuixiy** [comment]
@XeonChow 我的失误，按原方法，新建 `~/blog/assets/js/custom.js`，加入：

```js
window.onload = function() {
    if (commentsToggle !== null) {
        loadComments();
        commentsToggle.style = "display: none";
    }
}
```

**Comment by XeonChow** [comment]
@reuixiy 感谢作者，这个问题已解决，顺便再问一个困扰我挺久的问题。我的博客采取和作者博客类似的布局，也分了「技术」、「生活」等多个页面。`config.toml` 中设置 `categoryBy = "sections"`，并按照说明将配置文件中的类别（taxonomies）中的 `categories` 删除，新建了`content/categories/_index.md` 文件。并且我开起了显示文章上下篇 `enablePostNav = true`，问题是我只有「生活」页面里的文章有上下篇导航按钮，其他区都没有，是不是我哪里设置的问题。我对照了作者博客的配置文件，也没有发现问题在哪儿，希望得到解答，谢谢！我的博客地址是 [XEON CHOW](https://enit.xyz)

**Comment by reuixiy** [comment]
@XeonChow 没事儿。

不知你有没有修改 [`mainSections`](https://github.com/reuixiy/hugo-theme-meme/blob/aa1461f7d110f97311195c37450ebd611b7cacb1/config-examples/zh-cn/config.toml#L444) 参数，你的情况，应该修改为：

```toml
mainSections = ["tech", "life", "review"]
```

注意要将前面的注释符 `#` 删除。

**Comment by XeonChow** [comment]
@reuixiy 果然是这个问题，我修改了 `mainSections` 参数，但是没有去掉 `#` 注释，问题已解决，再次感谢作者，看来以后还是要细心一点
