### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Xuezenghuigithub** [reuixiy/hugo-theme-meme#13]
一休儿你好👋，关注你的博客一个月左右了，搭建hexo博客参考了很多你文章中的想法，现在博客遇到问题了，想和你交流一下，不知方便否？

**Comment by reuixiy** [comment]
@Xuezenghuigithub 你好，

感谢你的关注，如果有什么能够帮上的，我很乐意提供帮助 :smile_cat: ~

但这里是 MemE 主题的 Issues 区，所以请去我的[博客仓库](https://github.com/reuixiy/io-oi.me/issues)提问交流，这里我就先关闭了。

谢谢理解 :smiley_cat:
