### ISSUE TITLE
Photos are dimmed in dark mode

### ISSUE THREAD

**Issue by RylandDeGregory** [reuixiy/hugo-theme-meme#130]
This is less of an issue and more just asking for help.

What is the setting in `config.toml` that will allow me to control embedded images being dimmed in dark mode?

Example in light mode: ![Example image in light mode](https://user-images.githubusercontent.com/18073815/81233194-398b1680-8fc4-11ea-94be-edc0e28fa533.png)

Example in dark mode: ![Example image in dark mode](https://user-images.githubusercontent.com/18073815/81233198-3bed7080-8fc4-11ea-8cb3-b2ae16b016e3.png)

Thanks :)

**Comment by reuixiy** [comment]
I see, it's a [CSS filter](https://github.com/reuixiy/hugo-theme-meme/blob/aa1461f7d110f97311195c37450ebd611b7cacb1/assets/scss/components/_dark-mode.scss#L7-L10) and you can [customize](https://github.com/reuixiy/hugo-theme-meme#customize-meme) it.

`~/blog/assets/scss/custom/_custom.scss`:

```css
[data-theme="dark"] img {
    filter: none;
}
```
