### ISSUE TITLE
Allow for custom post metadata?

### ISSUE THREAD

**Issue by palant** [reuixiy/hugo-theme-meme#136]
I have to display comment count in the post metadata. Currently, I have to override all of `post-meta.html` for that. Maybe `post-meta.html` could load a partial like `custom-post-meta.html` which is empty by default but can be overridden by the blog owner?

**Comment by reuixiy** [comment]
Yes, you can create an empty `post-meta.html` under `layouts/partials/custom/`. PR welcome!
