### ISSUE TITLE
The icon of theme and multilingual can't display on GoogleChrome on linux

### ISSUE THREAD

**Issue by Gaotianhe** [reuixiy/hugo-theme-meme#139]
just as you see it 

<img width="138" alt="hugo主题使用问题-在Linux Chrome中不能正常显示" src="https://user-images.githubusercontent.com/52186032/81784295-3c8b8700-952f-11ea-93cf-20d40e0db63c.png">

env:

Chrome: 81.0.4044.138 (Official Build) (64-bit)

Linux:

```bash
System:    
           Kernel: 4.19.0-6-amd64 x86_64 bits: 64 compiler: gcc v: 8.3.0 
           parameters: BOOT_IMAGE=/boot/vmlinuz-4.19.0-6-amd64 
           root=UUID=dc4e6e4a-c8a2-44e4-aee1-e677ad07eada ro quiet splash 
           Desktop: Xfce 4.14.2 tk: Gtk 3.24.5 info: xfce4-panel wm: xfwm4 dm: LightDM 1.26.0 
           Distro: MX-19.1_x64 patito feo February 15  2020 base: Debian GNU/Linux 10 (buster) 
Machine:   
           Type: Virtualbox System: innotek product: VirtualBox v: 1.2 serial: <filter> 
           Chassis: Oracle Corporation type: 1 serial: <filter> 
           Mobo: Oracle model: VirtualBox v: 1.2 serial: <filter> BIOS: innotek v: VirtualBox 
           date: 12/01/2006 
```

**Comment by reuixiy** [comment]
This theme uses emoji for these switches, so please install related fonts, e.g.

```sh
apt install fonts-noto-color-emoji
```

**Comment by Gaotianhe** [comment]
why it display normal on firefox with Linux, I can't understand

after install through `apt install fonts-noto-color-emoji` can't work, and I google search "Google Noto Fonts" , download [Noto Emoji](https://noto-website-2.storage.googleapis.com/pkgs/NotoEmoji-unhinted.zip) . I'm going to watch its result

In addition, if I want to change the emoji with letters like cn or en, what can I do?

**Comment by Gaotianhe** [comment]
haha, it wordked after I install the two fonts: Noto Color Emoji and Noto Emoji. But it displayed with no color:

<img width="152" alt="hugo主题使用问题-在Linux Chrome中不能正常显示1" src="https://user-images.githubusercontent.com/52186032/81808688-a9644880-9552-11ea-81ec-d8c1963010fa.png">

**Comment by Gaotianhe** [comment]
ok, it have color now!

**Comment by reuixiy** [comment]
> In addition, if I want to change the emoji with letters like cn or en, what can I do?

I'v answered this question before, see https://github.com/reuixiy/hugo-theme-meme/issues/128#issuecomment-624739400

**Comment by Gaotianhe** [comment]
:joy: thank you!

**Comment by reuixiy** [comment]
No problem!
