### ISSUE TITLE
Found another curious bug!

### ISSUE THREAD

**Issue by ZhaoTim** [reuixiy/hugo-theme-meme#14]
HI:
It's me again.....And I found a bug , it makes me confuse....
here is my blog : [HomePage](https://zhaomeicheng.com)

here is the situation:
when I texted a code block after a ordered list / unordered list, the code indent will be something wrong....

![t](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fee2dc146-bec9-4844-9218-14c332aca089%2FUntitled.png?table=block&id=7c748ee6-3fcc-4b81-9a11-1d0a22da7386&width=2020&cache=v2)

![t](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F05f9ab3a-ec1a-406d-9909-df6c3c3a643b%2FUntitled.png?table=block&id=313f01c1-f0ec-4339-9f50-ca6d523f62f8&width=3790&cache=v2)

But when I delete the ordered list , everything will be fine?????

![t](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F697b6a5f-44d9-423d-918e-b0e46ed839ad%2FUntitled.png?table=block&id=28974e32-bb71-45a1-9ca5-a094a7eb0b56&width=2590&cache=v2)

![t](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F6170e0db-799e-40ea-a1d6-a81f12745cf5%2FUntitled.png?table=block&id=c6f4c02f-9f53-45c7-985c-93cfd0c25d96&width=3730&cache=v2)

And I also want to know how to change the code theme....

Thx a lot!

**Comment by reuixiy** [comment]
Hi @ZhaoTim,

For the code indent problem, I think that may be the problem of Hugo's Markdown rendering engine [blackfriday](https://github.com/russross/blackfriday). So perhaps you should submit an issue there or in [Hugo](https://github.com/gohugoio/hugo).

For code highlighting theme, you can easily customize that.

1. Go to https://xyproto.github.io/splash/docs/longer/all.html to find a theme you enjoy.
2. Run the following command (modify `monokai` to the name of the theme you choose).
    ```
    ~/blog $ hugo gen chromastyles --style=monokai > light/dark.scss
    ```
3. Move the generated `light.scss` file to `~/blog/assets/scss/_common/_highlight/` directory, which will override MemE’s `light.scss`.

Similarly, change `light.scss` to `dark.scss` if you want to customize MemE’s code highlighting theme for dark mode. In addition, be sure to replace all `.chroma` in the `dark.scss` file with `.chroma-dark`.

---

For more https://gohugo.io/content-management/syntax-highlighting/
