### ISSUE TITLE
Example configuration should probably disable default RSS

### ISSUE THREAD

**Issue by palant** [reuixiy/hugo-theme-meme#143]
With the example configuration the default RSS feed will still be generated as `index.xml`. It might be a good idea to add a setting to disable it:

    disableKinds = ["RSS"]

**Comment by reuixiy** [comment]
Actually, MemE has already disabled it via [`outputs`](https://github.com/reuixiy/hugo-theme-meme/blob/5353fec9e80320cb47754b936667ef927c97f80a/config-examples/en/config.toml#L139-L148) in the example configuration.

**Comment by palant** [comment]
My bad then. I was too lazy to mess with the default `outputs` config.
