### ISSUE TITLE
Inconsistent display of the theme switcher icon

### ISSUE THREAD

**Issue by palant** [reuixiy/hugo-theme-meme#144]
The theme switcher icon relies on the system font which can vary a lot. I set `font-size: 140%` for mine (it was barely visible in Chrome on Linux) and here is what I got:

![Windows](https://i.imgur.com/RsdqFOJ.png)![Linux Firefox](https://i.imgur.com/jUhlbxm.png)![Linux Chrome](https://i.imgur.com/RXpSTfA.png)
![Windows](https://i.imgur.com/VIz4YLa.png)![Linux Firefox](https://i.imgur.com/C7drkiw.png)![Linux Chrome](https://i.imgur.com/pdxOBr0.png)

From left to right: Windows (both Firefox and Chrome), Linux (Firefox), Linux (Chrome). Not only does the color vary, the size isn't consistent either. So I now have it overly large on Windows, but at least it should be visible in any browser.

Maybe it's a good idea to use an SVG icon for this, at least optionally?

**Comment by dawnow** [comment]
@palant  I have the same needs, and I discovered the country flag that language switcher icon only show two characters on my Windows device. But it's normal on my Android phone.

**Comment by reuixiy** [comment]
Okay, let's do this. Meanwhile, improve the accessibility(#111) of them also.

**Comment by reuixiy** [comment]
What do you think of this toggle? https://codepen.io/bnthor/pen/WQBNxO

**Comment by palant** [comment]
Looks nice but takes up too much space. And isn't as nice any more when scaled down.

**Comment by reuixiy** [comment]
Agreed.

**Comment by reuixiy** [comment]
I'm working on it now. You can test it in branch [`theme-switcher`](https://github.com/reuixiy/hugo-theme-meme/tree/theme-switcher).

**Comment by reuixiy** [comment]
> I discovered the country flag that language switcher icon

@dawnow The multilingual switcher, however, its content comes directly from the `languageName` param currently, so it‘s a bit more complicated to handle. I need more time to think about it, maybe I will solve this while dealing with #111.

**Comment by palant** [comment]
The code on the branch looks good to me now. I didn't see it in action however.
