### ISSUE TITLE
Inline scripts break Content Security Policy

### ISSUE THREAD

**Issue by palant** [reuixiy/hugo-theme-meme#145]
For security reasons, it's a good idea to have a [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) saying something like `script-src: 'self'` - only scripts from this website allowed, and no inline scripts. This offers a good protection layer against Cross-Site Scripting attacks.

Now this doesn't quite work with MemE, two scripts are potentially defined inline: theme switcher and HTTPS switcher. It seems that the possible solutions are:

* Disable both features - possible but I actually liked the theme switcher.
* Allow these scripts in CSP based on their SHA-256 hash - possible but complicated, might also break when the theme is updated (slight changes to the script).
* Move the scripts for these features into a separate script file - adds one more request for a tiny file.
* Merge these scripts into the existing script file and include it at the top of the page - will delay page load minimally but is my preferred solution so far.

What do you think?

**Comment by reuixiy** [comment]
This is basically beyond my knowledge 😅. But I prefer the 4th solution too.

**Comment by palant** [comment]
I've set CSP to `script-src 'self' 'sha256-Gm1oTy0TqoHcwUBUhFG0IWdfrLSxxxdn1G0rEFl6x2g='` for now - this allows the theme switcher script to work, but it feels like a temporary solution.
