### ISSUE TITLE
Fixed position header messes up internal linking

### ISSUE THREAD

**Issue by palant** [reuixiy/hugo-theme-meme#146]
A link to a blog entry might go to a specific heading, e.g. when clicking a ToC table entry. With MemE this will currently result in the heading being hidden below the header rather than visible below it. It's a common issue and I only found [this solution](https://stackoverflow.com/a/28824157/785541) and variations of it. The issue here: it only works if header size is a known fixed value.

So it seems that the possible solutions are:

* Make the header non-fixed - it will become invisible when you scroll down.
* Implement some dynamic switching between fixed/non-fixed as seen on some websites - personally, I consider that behavior highly annoying.
* Calculate the header height based on the height of the largest element, for me it will be calc(2em + 38px) - that's making lots of assumptions, in particular that the header elements don't wrap.
* Set a CSS variable dynamically, similar to how width of `.main-inner` is currently being measured.

I've added the following custom CSS now:

```
[id]::before
{
  content: "";
  display: block;
  visibility: hidden;
  height: calc(38px + 2em);
  margin: calc(-38px - 2em) 0 0;
}
```

This seems to work pretty well. I can only see an issue if I switch to text-only zoom in Firefox and make the text big enough for the header to wrap onto two lines - and even then the heading is still readable. But measuring header height dynamically in addition might still be a good idea.

**Comment by palant** [comment]
Found an issue with this approach - it messes up inline elements with `id` attribute, in particular footnotes. With the code above the footnote reference would be displayed on the next line. So I changed the selector to `[id]:not(sup)::before` - going back from a footnote will now hide the text under the header but this is the smaller of the two evils.

**Comment by reuixiy** [comment]
Yes, your solution is nice and simple!

Previously(#93, non-English), I suggested @he-sb just enable a third-party plugin [Medium Zoom](https://github.com/reuixiy/hugo-theme-meme/blob/f3d9ad04035b4f0631002a847ada05c3f07e9a1f/config-examples/en/config.toml#L1285-L1289), which handles this well but seems a bit heavy. Maybe you can dig into its code and create a PR in MemE? (If you have time.)

Btw, your site looks awesome! I know this is off-topic, but I just want to say it!

**Comment by palant** [comment]
You meant smooth-scroll apparently, which is deprecated. It completely replaces the browser's scrolling mechanism and [corrects its scrolling by the header height](https://github.com/cferdinandi/smooth-scroll/blob/master/src/core.js#L400) (header selector defined in settings). And it only works when an anchor link is clicked on the page, not when going to a different page with an anchor (e.g. on https://palant.info/ there are "comments" links pointing to page#comments). All in all: no, this is not a real solution.

**Comment by palant** [comment]
I went through my generated output and verified that `<sup>` and `<input>` are the only inline elements that have `id` attributes, the latter are unproblematic however. One could list the allowed tags explicitly however to avoid issues:

```
p, div, ul, form, main, footer, nav, h1, h2, h3, h4, h5, h6
{
  &::before
  {
    content: "";
    display: block;
    visibility: hidden;
    height: calc(38px + 2em);
    margin: calc(-38px - 2em) 0 0;
  }
}
```

**Comment by reuixiy** [comment]
> You meant smooth-scroll apparently

Oops! Yes, my mistake.

> not when going to a different page with an anchor

Yep, indeed.

So guess we can fix this issue too - in another PR.
