### ISSUE TITLE
Error building site: TOCSS: failed to

### ISSUE THREAD

**Issue by Escher1108** [reuixiy/hugo-theme-meme#149]
Error building site: TOCSS: failed to transform "en/styles/main-rendered.scss" (text/x-scss): resource "scss/scss/main.scss_a899b346ffc3a4bc65b84e40528dea51" not found in file cache

**Comment by reuixiy** [comment]
Try to install `extended` version of Hugo.

**Comment by Escher1108** [comment]
Thanks for your answers, I didn't have time to reply, I will try it

**Comment by igorkulman** [comment]
Similar problem here 

```
Error: Error building site: TOCSS: failed to transform "en/styles/main-rendered.scss" (text/x-scss): SCSS processing failed: file "stdin", line 223, col 17: Invalid CSS after "$fofPoster: url(": expected expression (e.g. 1px, bold), was "<no value>);"
```

with Hugo extended:

```
hugo version
Hugo Static Site Generator v0.71.0-06150C87/extended darwin/amd64 BuildDate: 2020-05-18T16:13:04Z
```

**Comment by reuixiy** [comment]
@Escher1108 No problem!

@igorkulman Did you forget [the first step](https://github.com/reuixiy/hugo-theme-meme#blogging)?

**Comment by ericpar** [comment]
I am having the exact same issue when using the 'meme' theme on gitlab pages. Unfortunately, I am not able to install the extended Hugo on the Docker image the Gitlab pages pipeline uses.
Is there any workaround?

**Comment by tensafefrogs** [comment]
@ericpar run this line (it's in the "Blogging" section of the readme, which is confusing, but seems to be required even if not blogging)

`$ rm config.toml && cp themes/meme/config-examples/en/config.toml config.toml`

After running this the error above was fixed.

**Comment by ankush981** [comment]
@tensafefrogs Wow, thanks for the tip! I was very disappointed after trying several static site generators and trying to get their themes behave; however, it looks like fortune is finally smiling on me! 😄 

I wonder if this is worth adding to the top of the theme instructions page . . .
