### ISSUE TITLE
Can't set "About" to Home

### ISSUE THREAD

**Issue by syclops** [reuixiy/hugo-theme-meme#15]
The `homeLayout` variable only allows posts, poetry, or footage as possible options. This would seem to indicate that there is no way to set the content of a page like "About" to the content that is displayed at the root/home of the site.

Ideally, there would be a variable in the config that would just refer to a folder within the content, and the homepage would simply show the content of that folder's `index.md`, but I can't find this option.

**Comment by reuixiy** [comment]
Hi @syclops,

I just submitted a commit to support that. What you need to do is:

1. update MemE
2. set `homeLayout` equal to `page`
3. add `_index.md` to customize the content

Please update MemE to the latest version to test it. :smiley_cat:
