### ISSUE TITLE
How to correctly config icon?

### ISSUE THREAD

**Issue by shorca** [reuixiy/hugo-theme-meme#154]
I've updated png files in `/static/icons/`, and `favicon.ico` in `/static/`, and also added the `manifest.json` file; the icon shows on my local machine but not after Netflix deploys it. 

Am I missing something? Thank you for your help!

**Comment by reuixiy** [comment]
It actually works. You didn't see it because of the browser's cache, so just try `ctrl`+`shift`+`r`.

**Comment by shorca** [comment]
Wow thank you so much... such a trivial problem costed me a few hours lol. talking about learning :)
