### ISSUE TITLE
Syntax error in a file

### ISSUE THREAD

**Issue by Gaotianhe** [reuixiy/hugo-theme-meme#157]
This is the address ：[hugo-theme-meme/exampleSite/config.toml](https://github.com/reuixiy/hugo-theme-meme/blob/master/exampleSite/config.toml)

The content of the file is:

```
../config-examples/en/config.toml
```

The following error appears in VSCode:

```
Expected "#", "'", "[", "\"", "\n", "\r", [ \t], [A-Za-z0-9_\-] or end of input but "." found.
```

This does not affect the use of meme, but I am still curious why this error occurs.

**Comment by palant** [comment]
I tested the config with https://www.toml-lint.com/ and it is valid. Wonder what VSCode is complaining about. It seems to be upset about a line starting with a dot, but there are no such lines in the example config. Hard to tell however without having a line number at least.
