### ISSUE TITLE
Run-time error

### ISSUE THREAD

**Issue by Xuezenghuigithub** [reuixiy/hugo-theme-meme#16]
hello, yixiuer!
I just started trying Hugo, but when i follow the step in README and report the error as follows:
```
Error: Error building site: failed to render pages: render of "home" failed: "/Users/zander/xuezenghui.com/themes/meme/layouts/index.sectionsatom.xml:6:19": execute of template failed: template: index.sectionsatom.xml:6:19: executing "index.sectionsatom.xml" at <.Site.Config.Service...>: can't evaluate field RSS in type services.Config
```
this happened after i ran `hugo server -D`. 😢

**Comment by reuixiy** [comment]
Hi @Xuezenghuigithub,

Can you please paste your `config.toml` and the output info of `hugo version`?

**Comment by Xuezenghuigithub** [comment]
`config.toml` I just copy yours and have not  any change.
`hugo version` : `Hugo Static Site Generator v0.54.0/extended darwin/amd64 BuildDate: unknown`
thx!

**Comment by Xuezenghuigithub** [comment]
It looks like because RSS or something about it , but I still get errors after deleting these two files directly(forgive me for taking a solution to the original violence😰

**Comment by reuixiy** [comment]
Please try to update [Hugo](https://github.com/gohugoio/hugo/releases) to the latest version.

**Comment by Xuezenghuigithub** [comment]
Could u tell me what is the shell order for the upgrade? I haven't found it for a long time...🥵

**Comment by reuixiy** [comment]
`brew upgrade hugo`

**Comment by Xuezenghuigithub** [comment]
MAC 10.15 seems like can't upgrade new version..

**Comment by Xuezenghuigithub** [comment]
The good news is that it is not RSS error, but `Building sites … ERROR 2019/10/29 08:45:55 Failed to read Git log: fatal: 您的当前分支 'master' 尚无任何提交
Total in 132 ms
Error: Error building site: logged 1 error(s)`

**Comment by Xuezenghuigithub** [comment]
It works, thx!! 刚看你博客的时候一度怀疑你是个女生...🤨

**Comment by reuixiy** [comment]
:joy:...
