### ISSUE TITLE
Move list-read-more link to the right 

### ISSUE THREAD

**Issue by reuixiy** [reuixiy/hugo-theme-meme#162]
Currently, the list-read-more link is on the left, I think it would be more comfortable if we move its position to the right, what do you think? @palant

**Comment by palant** [comment]
Not sure, it looks strange this way somehow. Probably because the reading flow isn't clear:

![screenshot](https://i.imgur.com/Z9Zd9Zd.png)

Maybe centered like it is with the articles?

![screenshot](https://i.imgur.com/PACmbHq.png)

**Comment by he-sb** [comment]
Personally, I prefer the right edition.

**Comment by reuixiy** [comment]
So maybe we should keep it as it was and leave it to users, after all, it's simple to customize styles in MemE.

Issue closed.
