### ISSUE TITLE
Add search functionality?

### ISSUE THREAD

**Issue by palant** [reuixiy/hugo-theme-meme#163]
Would it make sense to contribute the search functionality from palant.info? Hugo website recommends hugo-lunr for lunr.js integration which is an unnecessarily complicated way to do it and will fail in some scenarios. This functionality can be easily integrated into a theme, with lunr.js script as the only external dependency. The search itself will work on the client side then, without any server-side support (search index generated as a JSON file by Hugo itself).

**Comment by he-sb** [comment]
It would be awesome!🎉

**Comment by reuixiy** [comment]
Then guess we can do it.

**Comment by dawnow** [comment]
@reuixiy Is this child's wish coming true? https://github.com/reuixiy/hugo-theme-meme/issues/84

**Comment by reuixiy** [comment]
@dawnow Hmmm, not sure, as that issue is lack of description... Anyway, maybe we can close it when we close this. 🤔

**Comment by palant** [comment]
Ok, I'm generalizing the code, will create a pull request shortly.

**Comment by palant** [comment]
Pull request is #165.
