### ISSUE TITLE
Error building site: Failed to find a valid digest in the 'integrity' attribute for resource

### ISSUE THREAD

**Issue by kgSuzuki1994** [reuixiy/hugo-theme-meme#164]
the css on my page isn’t loaded because of:
`Failed to find a valid digest in the 'integrity' attribute for resource 'https://kgsuzuki1994.github.io/css/meme.min.294ec2fab8a894a1c31d932058865b79d877c06dfa671581a68e4df1874321f2.css' with computed SHA-256 integrity 'U83LE/+SbeYfdn7+6S0GVbtbfDF7YVMqCp27+I04Li4='. The resource has been blocked.`  

MyPage: https://kgsuzuki1994.github.io/
MyRepository: https://github.com/kgSuzuki1994/kgSuzuki1994.github.io
Please help.

**Comment by reuixiy** [comment]
Don't know why, but you can solve this by disabling [`enableFingerprint`](https://github.com/reuixiy/hugo-theme-meme/blob/0cd2733fbfe15271e5d7a235fa1c358714f6205e/config-examples/en/config.toml#L1260).

**Comment by kgSuzuki1994** [comment]
Thanks to that method, it was solved.
Tyhank you!
