### ISSUE TITLE
Failed to transform "styles/main-rendered.scss"

### ISSUE THREAD

**Issue by CiscoSong** [reuixiy/hugo-theme-meme#17]
This is my first time to use HUGO and the following ERROR appears after the "hugo server -D" commend:
Building sites … ERROR 2019/11/02 01:22:55 Transformation failed: TOCSS: failed to transform "styles/main-rendered.scss" (text/x-scss): this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
ERROR 2019/11/02 01:22:55 Transformation failed: TOCSS: failed to transform "styles/main-rendered.scss" (text/x-scss): this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Total in 49 ms
Error: Error building site: logged 2 error(s)

The Hugo version for me is:
Hugo Static Site Generator v0.59.1-D5DAB232 windows/amd64 BuildDate: 2019-10-31T15:22:43Z
I thought it is the newest one.
Please help me check this problem. Thanks!

**Comment by reuixiy** [comment]
Hi @CiscoSong,

Please try to install the `extended` version of Hugo.

https://gohugo.io/troubleshooting/faq/#i-get-tocss-this-feature-is-not-available-in-your-current-hugo-version

**Comment by CiscoSong** [comment]
Thanks a lot !!!!!!!!
