### ISSUE TITLE
更新 v4.4.0 后遇到的问题：

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#175]
![image](https://user-images.githubusercontent.com/46470508/82731731-75034000-9d3b-11ea-8d68-d67a70023c34.png)

已按照历史记录更新了我的  `Config.toml`

- 首先是主题切换按钮，第一次打开是正常的，但是点击一次后再切换回来图标便消失了

- Search 的图标在 PC 上不显示，只是一个圆圈。（手机上正常）

也不知道是哪里出问题了😅

[仓库地址](https://github.com/dawnow/blog)

**Comment by reuixiy** [comment]
两个都是图标的问题，两个都是自定义的样式导致的，[见此处](https://github.com/dawnow/blog/blob/451b323a407684805f243991f22c9f4c0fd90768/assets/scss/custom/_custom.scss#L17-L19)。

你可以将之删除，以简单解决。或者，你想要保留目前桌面端不显示图标的效果，参考我的博客该文件的[更改历史](https://github.com/reuixiy/io-oi.me/commits/master/assets/scss/custom/_custom.scss)。

此外，搜索暂时不支持中文😅，建议关闭。

**Comment by dawnow** [comment]
@reuixiy wow! It works, big thanks to reuixiy.👍

**Comment by dawnow** [comment]
![image](https://user-images.githubusercontent.com/46470508/82744833-4d9a8a80-9db0-11ea-8fd9-a87b8d706cc5.png)

又按照 reuixiy 的历史记录换回了之前的 emoji 图标。图中这个地方不能再用 `.icon` 了，必须对应菜单栏中图标的 Class 名，不然还是点击一次小太阳再切换回去图标就没了。😅

不过在窄视图下图标也不显示了，另外白天主题下小太阳和小月亮咋同时出现了😮? @reuixiy 你的咋就没这个问题。

![image](https://user-images.githubusercontent.com/46470508/82744996-057c6780-9db2-11ea-8dc1-02c6bfa8c8ec.png)

![image](https://user-images.githubusercontent.com/46470508/82745018-365c9c80-9db2-11ea-81f1-cd84758a29f8.png)

**Comment by reuixiy** [comment]
额，你再往那文件上面的历史找找，尝试尝试，应该能有答案。

**Comment by dawnow** [comment]
> 额，你再往那文件上面的历史找找，尝试尝试，应该能有答案。

找到图标的错误了，忘记把旧的的代码删除干净了。🙂
