### ISSUE TITLE
关于同步以前post的文章

### ISSUE THREAD

**Issue by QuakeWang** [reuixiy/hugo-theme-meme#178]
之前使用的是hugo其他的主题，在看见meme之后，就更新为meme主题，结果以前的文章链接打不开了，应该怎么处理呢？？

**Comment by reuixiy** [comment]
具体是怎么打不开了呢？

**Comment by QuakeWang** [comment]
可以显示文章的大概标题浏览，但是打开之后是空白网页

**Comment by reuixiy** [comment]
截图或在线链接，不然我无法判断原因。

**Comment by QuakeWang** [comment]
这个是博客地址https://quakewang.github.io/
这个是post文章的地址https://quakewang.github.io/post/arrayqueue/

**Comment by reuixiy** [comment]
可以尝试编辑一下配置文件中的 mainSections，将前面的注释符删除，然后将 posts 修改为 post。

**Comment by QuakeWang** [comment]
我试了一下，还是不行
