### ISSUE TITLE
Use markdownify for title?

### ISSUE THREAD

**Issue by Syralist** [reuixiy/hugo-theme-meme#179]
I want to use ndashes in my page titles. In the content of the post a double hyphen -- is automatically converted by markdownify. Since titles are not processed through markdownify the double hyphen is preserved.
Is there a reason not to apply markdownify to titles? If there is not I will open a pull-request with my suggested changes. :)

**Comment by palant** [comment]
The main reason should be that titles will be used in a bunch of places expecting plain text, e.g. the page's `<title>` tag. And while [Hugo's `plainify` function](https://gohugo.io/functions/plainify/) can strip out HTML tags, it won't turn HTML entities into their plain text equivalent. So you'll end up with `&nbsp;` displayed as text in the page title...

**Comment by palant** [comment]
Then again, `$title | plainify | htmlUnescape` will take care of those HTML entities as well. So I guess that this could be done.
