### ISSUE TITLE
Error: render of "section" failed

### ISSUE THREAD

**Issue by tobip** [reuixiy/hugo-theme-meme#18]
I just got this error:

`Error: Error building site: failed to render pages: render of "section" failed: execute of template failed: template: _default/list.html:85:35: executing "main" at <partial "list-item.html" .>: error calling partial: "/home/tobias/hugo/quickstart/themes/meme/layouts/partials/list-item.html:4:149": execute of template failed: template: partials/list-item.html:4:149: executing "partials/list-item.html" at <.Site.Params.listdateformat>: invalid value; expected string`

hugo v0.59.0

**Comment by reuixiy** [comment]
Hi @tobip,

Would you please paste your `listDateFormat` value in `config.toml`?

**Comment by tobip** [comment]
Alright, I missed the part to copy the config.toml file after downloading the theme package.

After doing this, everything works fine. Thanks a lot! 
The Theme is **awesome** :-)

**Comment by reuixiy** [comment]
:smiley_cat:
