### ISSUE TITLE
Document browser requirements

### ISSUE THREAD

**Issue by palant** [reuixiy/hugo-theme-meme#181]
Whenever I use a new JavaScript feature in this theme, I have to check that its browser support is at least as good as that of some other feature already in use. It's also hard to decide whether a particular polyfill is really required. It might be better to document the supported browser versions and to adjust these explicitly when necessary.

It seems that currently the following features are relevant:

* [let statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let): Chrome 49, Edge 14, Firefox 44, IE 11, Opera 17, Safari 10.
* [navigator.clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) (polyfilled): Chrome 66, Edge 79, Firefox 63, Opera 53, Safari 13.1
* [storage event](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event): Doesn't seem to be supported on IE but it will merely result in this feature not working.
* [addEventListener() without useCapture parameter](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters): Chrome 1, Edge 12, Firefox 6, IE 9, Opera 11.6, Safari 13.1.
* [addEventListener({once: true})](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters): Chrome 55, Edge 18, Firefox 50, Opera 42, Safari 13.4 - incompatible browsers should interpret the value as `true`, no breakage.
* [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/var): Chrome 49, Edge 15, Firefox 31, Opera 36, Safari 9.1, no IE support.

Not sure whether I found everything, but from the above it seems that the baseline is:
* Chrome 49 (let statement and CSS variables)
* Edge 15 (CSS variables)
* Firefox 44 (let statement)
* IE not supported (CSS variables)
* Opera 36 (CSS variables)
* Safari 13.1 (addEventListener without useCapture parameter)

**Comment by palant** [comment]
Actually, caniuse.com says "Support unknown" rather than "Not supported" for addEventListener without useCapture parameter in Safari. So it's quite likely that older Safari versions will work as well.

**Comment by palant** [comment]
In fact, Chrome supposedly supports addEventListener without useCapture parameter from day one. And given that it was originally based on WebKit like Safari, Safari must have behaved similarly for quite a while as well - if not always. So the baseline is Safari 10 after all (let statement).

**Comment by reuixiy** [comment]
Thanks for this reminder.

Someone told me that theme switcher and multilingual switcher don't work on Safari. Guess this is the reason.

Feel free to fix them if you have the time! Time is not on my side lately :(

**Comment by palant** [comment]
Fixing anything on Safari is complicated. Apple made sure that their browser can only be tested on their hardware and I don't have any.

**Comment by palant** [comment]
Actually, using Epiphany browser I can probably see the issue: [MediaQueryList](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList) has no `addEventListener` function, Safari only supports `addListener` (other browsers also do, for backwards compatibility).

**Comment by palant** [comment]
With Epiphany 3.36.1 (WebKit version matches Safari 11.1) I don't see any significant issues other than #184. Display is messed up on hi-dpi screens but I'm pretty certain that Safari doesn't have such issues :smile:. And responsive mode doesn't kick in when I make the window smaller, so we get horizontal scrolling and wrapping in the menu - but it works after reloading the page. I strongly suspect that this is also an Epiphany bug that doesn't affect Safari.
