### ISSUE TITLE
弱弱地问一下，能不能提个需求？

### ISSUE THREAD

**Issue by alexcdever** [reuixiy/hugo-theme-meme#182]
是这样的，国内的服务器放博客是有要求要在网站页脚处显示备案号，且备案号能跳转到工信部。能不能考虑下加个这方面的配置项😂

**Comment by reuixiy** [comment]
可以自定义的，你在配置文件找找页脚的相关内容。

**Comment by alexcdever** [comment]
谢谢，才留意到`customFooter`这个属性还能这样用😂
