### ISSUE TITLE
关于打赏二维码

### ISSUE THREAD

**Issue by HeroadZ** [reuixiy/hugo-theme-meme#186]
您好，感谢您开发的主题，我目前在用，非常漂亮。
就是不知道可以不可以开发一个打赏二维码放在每个文章后面。
非常感谢。

**Comment by he-sb** [comment]
这个你可以把收款码图片用 markdown 引用来嵌入到每篇文章后面。

嫌每次都加这么一行比较麻烦的话，可以修改一下模板文件，位置在 `~/blogs/archetypes/default.md` 。

**Comment by HeroadZ** [comment]
> 这个你可以把收款码图片用 markdown 引用来嵌入到每篇文章后面。
> 
> 嫌每次都加这么一行比较麻烦的话，可以修改一下模板文件，位置在 `~/blogs/archetypes/default.md` 。

非常感谢！
