### ISSUE TITLE
Failure of css file load

### ISSUE THREAD

**Issue by HeroadZ** [reuixiy/hugo-theme-meme#189]
hi, it seems like that there is a problem for the css file load.

![image](https://user-images.githubusercontent.com/17962682/83753333-09a75f80-a6a5-11ea-9e04-43e6ba9b64d7.png)

But I didn't change anything related to css. 
I just change the default.md in archetypes.

Also I update the meme theme, but no help.

Could you give me some help?

**Comment by Syralist** [comment]
I have the same problem on github.io.

**Comment by Syralist** [comment]
The problem seems to be with git and windows. I found out that setting
*git config --global core.autocrlf false* (for example with git bash)
resolves the issue.
If this is set to true as by default the linebreaks will be changed on commit. That messes with the checksums.

**Comment by HeroadZ** [comment]
@Syralist Thank you very much! It works.
