### ISSUE TITLE
[question] can i search

### ISSUE THREAD

**Issue by leela52452** [reuixiy/hugo-theme-meme#19]
@reuixiy 
everything looks great

however i feel there must be some kind of search. i mean to search post or page titles or contents.

thank you

ps: can i configure sitemap

**Comment by reuixiy** [comment]
Hi @leela52452,

## Search

I used to have a plan for search, and added some links in my bookmarks:

1. https://gohugo.io/tools/search/
2. https://www.josephearl.co.uk/post/static-sites-search-hugo/
3. https://verummeum.com/hugo-advanced-features/
4. https://xdeb.org/post/2017/06/11/make-hugo-generate-a-json-search-index-and-json-feed/

However, I have not finished it yet and don’t know if I have time to do it recently.... Perhaps you can try it yourself...

## Sitemap

MemE uses Hugo build-in sitemap template, check:

1. https://gohugo.io/templates/sitemap-template/
2. https://github.com/gohugoio/hugo/tree/master/tpl/tplimpl/embedded/templates/_default
