### ISSUE TITLE
求助贴，hugo server 一切正常，部署后异常

### ISSUE THREAD

**Issue by gears233** [reuixiy/hugo-theme-meme#191]
首先感谢作者做了这么棒的主题，设置页面 介绍也灰常详细，已star支持！

我个人在使用中遇到了点问题，希望看到帖子的人能给点建议，主要问题是我在 hugo server 下预览的时候，页面一切正常。但是实际部署后，在chrome 下显示异常，图标巨大，完全不能看，但是 ie 下勉强能看，只是部分样式有点异常。 碍于个人水平十分有限，无法发现问题所在，请求帮助！

有关信息：
站点链接：https://refun.eu.org 
hugo 版本：0.72 extended  ，  windows 64 
theme-meme：4.4.0  只修改了 config.toml 、Socials.toml内部分内容

遇到的大致问题截图如下：
![0](https://user-images.githubusercontent.com/57064324/83938745-c0bceb80-a809-11ea-8d28-ec30076f1d6c.jpg)
![2](https://user-images.githubusercontent.com/57064324/83938747-c61a3600-a809-11ea-9ab4-461939bea6e0.jpg)
![1](https://user-images.githubusercontent.com/57064324/83938749-c9152680-a809-11ea-8477-fa5cd43fbea9.jpg)

**Comment by Syralist** [comment]
This looks like the same problem as mentioned here: #189 
are you using git and windows?

**Comment by gears233** [comment]
> This looks like the same problem as mentioned here: #189
> are you using git and windows?

yes and I will try the method you mentioned in #189, thank you！

**Comment by gears233** [comment]
> This looks like the same problem as mentioned here: #189
> are you using git and windows?

It works！

**Comment by gears233** [comment]
请参考#189中 Syralist 提出的解决方案，设置：
`git config --global core.autocrlf false`

由于问题已解决，遂关闭。
