### ISSUE TITLE
较窄宽度下 菜单按钮的显示问题

### ISSUE THREAD

**Issue by gears233** [reuixiy/hugo-theme-meme#193]
![0](https://user-images.githubusercontent.com/57064324/83969239-6c953280-a901-11ea-8822-4dc308a7d492.jpg)

```
    enableNavToggle = true

    navHeight = "12em"
    # 说明：菜单栏展开时的高度
```

如图，我菜单栏项目有点多，算上深色模式开关，一共有7个按钮。于是我调节了下菜单栏展开高度有关设置。但是实际部署后，开关显示样式似乎有点问题，烦请查看下。

另外还遇到个小问题是，文章末分享链接部分， 通过二维码分享的功能，我没有改动过有关设置项，但是不知道为什么不能正常显示出二维码。我有查看过其他使用该主题的人的网站，但似乎都是正常的。😂

博客地址：https://gears233.github.io
Hugo版本：0.72 extended  win-64
Meme主题版本为最新。

**Comment by reuixiy** [comment]
你应该是参考 #129 定制了评论直接加载吧，目前需要修改下代码：

```js
window.addEventListener("DOMContentLoaded", event => {
    const commentsToggle = document.getElementById('load-comments');

    if (commentsToggle !== null) {
        loadComments();
        commentsToggle.style = "display: none";
    }
}, {once: true});
```

**Comment by gears233** [comment]
> 你应该是参考 #129 定制了评论直接加载吧，目前需要修改下代码：
> 
> ```js
> window.addEventListener("DOMContentLoaded", event => {
>     const commentsToggle = document.getElementById('load-comments');
> 
>     if (commentsToggle !== null) {
>         loadComments();
>         commentsToggle.style = "display: none";
>     }
> }, {once: true});
> ```

你好，是的。另外麻烦问下，这部分需要修改的代码应该在哪边修改？没有系统学习过编程相关的知识，所以有时候不一定能准确理解到。

另外，我在看 valine 评论模块有关的内容的时候，我看到 valine.html 里面 valine 的版本是写死的 1.3.10 版本，目前valine 已经更新到了 1.4.14 了，有个比较明显的改进是 深色模式 下提交评论的按钮也变成深色的了，这样在深色模式下 观感要好些。希望作者您有空的时候也可以考虑稍微更新下。

**Comment by reuixiy** [comment]
`assets/js/custom.js`

**Comment by gears233** [comment]
> `assets/js/custom.js`

🤣 感谢，发现意外解决了评论加载的需求~

**Comment by reuixiy** [comment]
至于菜单栏的问题，你确定你使用的是最新版主题吗？为什么生成的 HTML 代码都不一样？而且 `assets/js/custom.js` 默认应该是没有的啊？你是基于别人的仓库进行修改的吗？

**Comment by gears233** [comment]
> 至于菜单栏的问题，你确定你使用的是最新版主题吗？为什么生成的 HTML 代码都不一样？而且 `assets/js/custom.js` 默认应该是没有的啊？你是基于别人的仓库进行修改的吗？

你好，我确认是的. 关于 assets/js/custom.js 这个 ，就是参考了您 上面评论里面说的【  参考 #129 定制了评论直接加载 】 有关内容，自定义了custom.js 
另外由于我之前还遇到了 【Failure of css file load #189】 有关的问题，我尝试在mac os 下也重新生成了遍，但是网站呈现出来的效果还是如此。
而我在本地运行 hugo server 的时候，相关的问题却不会出现，故而特向您请求帮助。

![3](https://user-images.githubusercontent.com/57064324/83991906-ef110700-a980-11ea-9dac-18112319feb0.jpg)
![1](https://user-images.githubusercontent.com/57064324/83991908-f1736100-a980-11ea-875a-9434c3a292f5.jpg)
![2](https://user-images.githubusercontent.com/57064324/83991910-f3d5bb00-a980-11ea-9b1f-6474a1e4fa33.jpg)

**Comment by gears233** [comment]
> 至于菜单栏的问题，你确定你使用的是最新版主题吗？为什么生成的 HTML 代码都不一样？而且 `assets/js/custom.js` 默认应该是没有的啊？你是基于别人的仓库进行修改的吗？

另外我看到网页实际显示中， nav-toggle 部分，如果把 display:block  去掉似乎就不会有一开始截图内的 那个柱状的条了。
![4](https://user-images.githubusercontent.com/57064324/83993463-1a4a2500-a986-11ea-896c-4ba8ae32a4f5.jpg)

**Comment by reuixiy** [comment]
从你的截图中就可以看出问题，两个 `<label>` 标签应该是并列的，而不是父子的。

![2020-06-08-12-54-59](https://user-images.githubusercontent.com/28993043/83993919-7d888700-a987-11ea-9be8-5a32ef455541.png)

查看下源码，如上图，不知为何被处理错误了。

你有额外使用其它的工具压缩 HTML 代码吗？

正常的 Hugo 直接压缩后的应该是如下的。

![2020-06-08-12-55-15](https://user-images.githubusercontent.com/28993043/83993924-81b4a480-a987-11ea-9fd1-58ffbd238990.png)

**Comment by gears233** [comment]
> 从你的截图中就可以看出问题，两个 `<label>` 标签应该是并列的，而不是父子的。
> 
> ![2020-06-08-12-54-59](https://user-images.githubusercontent.com/28993043/83993919-7d888700-a987-11ea-9be8-5a32ef455541.png)
> 
> 查看下源码，如上图，不知为何被处理错误了。
> 
> 你有额外使用其它的工具压缩 HTML 代码吗？
> 
> 正常的 Hugo 直接压缩后的应该是如下的。
> 
> ![2020-06-08-12-55-15](https://user-images.githubusercontent.com/28993043/83993924-81b4a480-a987-11ea-9fd1-58ffbd238990.png)

感谢您的帮助！
我并没有使用其他的工具，一般都是直接使用命令 hugo --gc --minify 来生成。
但是我刚刚试着不添加  --minify 参数后又上传了一遍，显示确实正常了。

**Comment by reuixiy** [comment]
没事。已更新相关参数，[更新主题及配置](https://github.com/reuixiy/hugo-theme-meme/blob/master/README.zh-cn.md#%E6%9B%B4%E6%96%B0-meme)即可。
