### ISSUE TITLE
起初我以为是我配置问题，看了你们的404页面发现都有问题

### ISSUE THREAD

**Issue by movny** [reuixiy/hugo-theme-meme#199]
所有的相对路径应该为绝对路径

**Comment by movny** [comment]
不是用ipfs的，随便输个url看一看，看了你们博客我只发现少数是没问题

**Comment by movny** [comment]
![20200614-1](https://user-images.githubusercontent.com/58254971/84575721-f5204100-ade1-11ea-9e7e-7468e4e57b44.jpg)
![20200614-2](https://user-images.githubusercontent.com/58254971/84575739-226cef00-ade2-11ea-86b0-c04c679047c1.jpg)

**Comment by movny** [comment]
额我没看懂404的逻辑，一个`/en/404.html`一个`/404.html`，如何确保随便一个错误url访问到对应的语言呢`domain.com/a/b/xxx`
404页面中，我虽然在config里面写的地址是`/`开头的，但`domain.com/a/b/xxx`中仍然是`./`
![20200614-4](https://user-images.githubusercontent.com/58254971/84590797-188fce00-ae6c-11ea-9b9c-2fd502954564.jpg)

![20200614-3](https://user-images.githubusercontent.com/58254971/84590775-f0a06a80-ae6b-11ea-91e2-b14c0961707c.jpg)

**Comment by reuixiy** [comment]
如果你要将路径修改为绝对路径，将 `relativeURLs` 修改为 `false` 即可。

P.S. 看了一下，貌似你是克隆的我的博客仓库，可是我看一下好像我的博客没有这个问题，所以我也是摸不着头脑了。

**Comment by movny** [comment]
谢谢啦
