### ISSUE TITLE
[feature request] can you please create repo on gitlab

### ISSUE THREAD

**Issue by leela52452** [reuixiy/hugo-theme-meme#20]
@reuixiy 
please create repo on gitlab. it is easy for gitlab users to fork and use your theme

thank you

**Comment by leela52452** [comment]
@reuixiy 
fyi, its great
- [achecker -Congratulations! No known problems.](https://achecker.ca/checker/index.php#output_div)
- [w3 -Document checking completed. No errors or warnings to show.](https://validator.w3.org/nu/?doc=http%3A%2F%2Fvalidator.w3.org%2F)
- [CSS level 3 errors](http://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fmeme-test.netlify.com%2F&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en)

**Comment by reuixiy** [comment]
Hi @leela52452,

I just imported MemE into GitLab, see https://gitlab.com/reuixiy/hugo-theme-meme

> fyi, its great

Thx :)

**Comment by leela52452** [comment]
hello https://github.com/reuixiy
i am afraid it requires gitlabci.yml for deploying theme and pages, https://gitlab.com/help/user/project/pages/index.md

**Comment by leela52452** [comment]
hello @reuixiy 
**excuse**
it is lacking .gitlab-ci.yml
https://gitlab.com/help/user/project/pages/index.md
