### ISSUE TITLE
建议：目录可以接受标题使用html代码以实现url美观

### ISSUE THREAD

**Issue by movny** [reuixiy/hugo-theme-meme#203]
```html
<h2 id="head-1">说明&准备</h2>
```
现在的目录似乎只能展示markdown式的标题

**Comment by movny** [comment]
最好是可以自定义目录
```html
<a name="head-1"></a>
<h2>说明&准备</h2>
<p>
...
```

**Comment by reuixiy** [comment]
是的。目录目前直接取自 Hugo 的内建变量 [`.TableOfContents`](https://gohugo.io/content-management/toc/)，所以你的这个需求，主题层面上难以实现。

而且，不知你的这个需求的目的是什么呢？

**Comment by reuixiy** [comment]
哦，懂了，你是想自定义标题的 id 属性。

Markdown 有类似的在讨论中的语法，且 Hugo 的 Markdown 渲染器 [Goldmark](https://github.com/yuin/goldmark#attributes) 也支持，你可以这样写：

```
## 标题二 {#heading-2}
```

即可。

**Comment by movny** [comment]
谢谢
