### ISSUE TITLE
Mermaid charts are vague when switch to dark theme

### ISSUE THREAD

**Issue by Minys233** [reuixiy/hugo-theme-meme#205]
## Summary
I note when switching themes between dark/light, the background color is also changing, aka `data-theme="dark"`. But things are different when it comes to mermaid charts. There is neither option to set mermaid color theme, nor dynamic reload when you change page theme from light to dark. This makes the black lines nearly disappear in the dark theme.

## Description
Mermaid is introduced in file [layouts/partials/third-party/mermaid.html](https://github.com/reuixiy/hugo-theme-meme/blob/master/layouts/partials/third-party/mermaid.html). There should be an option to specify `theme` in one of four candidates: `["default", "forest", "dark", "neutral"]`, refer to [mermaid source code](https://github.com/mermaid-js/mermaid/blob/d2c47bb1531f8bc92244e061a36c910167b53635/src/mermaidAPI.js#L89-L105). When MEME load mermaid, the chart will be displayed in `default` color theme, which will make the black lines almost vanish! For example, [in my blog](https://blog.minys.online/posts/test-my-site/), the last chart in dark theme.

## Suggestions
I did some Googling and tests in and find two ways to solve it. The first one is easy but kind of stupid, while the second one is superior but needs more coding.

- In mermaid.html mentioned above, directly specify `theme: 'forest'`. Or add an option in `config.toml` and let users decide.
- Re-render charts when switch page theme
    - Available approaches do this by this function: [mermaid.init](https://github.com/mermaid-js/mermaid/blob/a4d96b032e43bea442d4b909668e03afa6be88c8/src/mermaid.js#L9-L29). First remove `data-processed` property, which make mermaid thinks the DOM nodes are not processed. Then, render them with new parameters.
        - https://markdownmonster.west-wind.com/docs/_5ef0x96or.htm
        - https://github.com/gcushen/hugo-academic/issues/1111

Thank you for your time and this excellent theme!

**Comment by reuixiy** [comment]
Thanks for your detailed feedback.

I'v looked into this and found the 2nd approach does not work with mermaid v8.5.2 anymore.

But I think I found a solution for this. :)
