### ISSUE TITLE
站点能在本地能够正常显示，但是无法在github pages 中正常显示

### ISSUE THREAD

**Issue by messcode** [reuixiy/hugo-theme-meme#206]
非常感谢 MEME 这个很酷的主题。 

通过命令 `hugo server -D`, 我可以在本地正常地预览我的站点。
![图像 1](https://user-images.githubusercontent.com/7353095/85360245-71471280-b4cd-11ea-8f87-6ce40536d191.png)

我把生成的 `public`  文件夹上传到了https://github.com/messcode/messcode.github.io.  但是我的GitHub 页面无法正常显示。

![图像 2](https://user-images.githubusercontent.com/7353095/85360356-c71bba80-b4cd-11ea-9e67-9a1bbe80d8bf.png)

我的配置是按照教程复制了模板中的`config.tomal`. 并且设置了 `baseURL = "https://messcode.github.io"`.  我的完整 `config.tomal ` 文件如下。
https://gist.github.com/messcode/805086b7887b0d660218b9d3049e33b4

我在网上搜索了几天，尝试把 `baseURL`  设为 "http://messcode.github.io"。不过也没有作用。
我对 hugo 的机制还有前端都不熟悉，不知道是哪里出了问题。感谢帮助！

**Comment by reuixiy** [comment]
尝试删除 `public` 后再上传

**Comment by reuixiy** [comment]
另，本地预览的命令为 `hugo server -D`，生成生产版 public 的命令为 `hugo`，加上清理和压缩的参数，可以用 `hugo --gc --minify --cleanDestinationDir`。

**Comment by messcode** [comment]
感谢，我再试试看 : )

**Comment by Syralist** [comment]
How does it look when you use `hugo server` locally? Without `-D`? If your posts do not show you must set `draft: false` in the frontmatter. :)

**Comment by messcode** [comment]
> How does it look when you use `hugo server` locally? Without `-D`? If your posts do not show you must set `draft: false` in the frontmatter. :)

It worked locally. I did change the `draft` in the frontmatter to true. It still did not work, however. Thanks @Syralist !

**Comment by Syralist** [comment]
I looked at your Repo. There shouldn't be a `public` folder in https://github.com/messcode/messcode.github.io. It seems, that github is displaying whats in that folder and that is pointing to the first commit, which is empty.
Did you follow this page: https://gohugo.io/hosting-and-deployment/hosting-on-github/ ? I think you mixed up the repos. ;)

**Comment by aozaki-kuro** [comment]
这个问题我同样遇到了，在Windows 10下部署的环境。VScode内用Git Bash进行部署，结果也是`hugo server -D`后正常，但部署至Github Pages后CSS样式报错，报错内容 Failed to find a valid digest in the 'integrity' attribute for resource 'xxxxxxx.css' with computed SHA-256 integrity. The resource has been blocked 。

查了相关资料后考虑为CRLF/LF的问题，改为WSL下运行`hugo --gc --minify --cleanDestinationDir`后部署，一切正常。

**Comment by reuixiy** [comment]
Coincidentally, I just deployed my blog to GitHub Pages yesterday, via GitHub Actions.

FYI,

- https://github.com/reuixiy/io-oi.me/tree/master/.github
- https://github.com/reuixiy/io-oi.me/issues/90

**Comment by mianzhang** [comment]
所以楼主最后是怎样解决的呢？

**Comment by realchoi** [comment]
> 

我允许这个命令后，全都 404 了，怎么补救啊？重新生成没有文件变化。

**Comment by realchoi** [comment]
> 这个问题我同样遇到了，在Windows 10下部署的环境。VScode内用Git Bash进行部署，结果也是`hugo server -D`后正常，但部署至Github Pages后CSS样式报错，报错内容 Failed to find a valid digest in the 'integrity' attribute for resource 'xxxxxxx.css' with computed SHA-256 integrity. The resource has been blocked 。
> 
> 查了相关资料后考虑为CRLF/LF的问题，改为WSL下运行`hugo --gc --minify --cleanDestinationDir`后部署，一切正常。

我用这个方法也不行，晚上还专门安装了 WSL2

**Comment by realchoi** [comment]
@mianzhang @messcode 
我找到解决方法了，关于 `Failed to find a valid digest in the 'integrity' attribute for resource 'xxxxxxx.css' with computed SHA-256 integrity. The resource has been blocked.` 的错误解决方法，我补一个链接：https://smc.im/post/resolve-integrity-error-in-hugoe/

**Comment by Gushmono** [comment]
说一下我的情况，预览命令：hugo server -D  生成命令：hugo  主题：PaperMod
先是在windows上本地预览正常，上传到Github仓库后无法加载CSS，显示不正常
改为在WSL2 Ubuntu20.04 中生成且Git同步到仓库后正常
注意不要在WSL2中生成后复制到Windows中上传，也会出现问题（好像是）
问题解决

**Comment by athllx** [comment]
一、原因：这种清空大概率通过按F12开发工具浏览器console控制台会有报错，发现有This request has been blocked; the content must be served over HTTPS.意思是HTTP和HTTPS混用导致的浏览器安全拦截非HTTPS的CSS特效文件等请求。

二、解决方案：在标签中添加 <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"/> 将HTTP请求统一升级为HTTPS安全请求。hugo是分模块管理，可以在类似路径的文件中更改hugo-themes/layouts/partials/head.html，在head.html文件meta部分添加，以达到所有页面统一的效果。最后就可以git hugo更新public并重新部署云端。

PS:若上述方案个别页面并无生效，请自行查找未生效页面的head标签部分，看是否有HTTPS升级代码。

**Comment by originem0** [comment]
>在这个报错信息下，根据这位答主提供的更改位置，添加下面这段代码 
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
解决了我的问题

**Comment by YixingNetwork** [comment]
> 说一下我的情况，预览命令：hugo server -D 生成命令：hugo 主题：PaperMod 先是在windows上本地预览正常，上传到Github仓库后无法加载CSS，显示不正常 改为在WSL2 Ubuntu20.04中生成且Git同步到仓库后正常 注意不要在WSL2中生成后复制到Windows中上传，同时出现问题（好像是） 问题解决

不仅是上传到仓库不正常 本地直接打开public文件夹下也丢失样式（好像是废话）但是如何解决呢

**Comment by YixingNetwork** [comment]
我尝试了很多个主题 好像使用Hugo拓展版生成的最终页面都会丢失（基础版运行不了我喜欢的模板www

**Comment by hengzhifu** [comment]
> 说一下我的情况，预览命令：hugo server -D 生成命令：hugo 主题：PaperMod 先是在windows上本地预览正常，上传到Github仓库后无法加载CSS，显示不正常 改为在WSL2 Ubuntu20.04 中生成且Git同步到仓库后正常 注意不要在WSL2中生成后复制到Windows中上传，也会出现问题（好像是） 问题解决

我也是使用这个PaperMod 主题，也会出现这个问题。不知道改如何解决？
