### ISSUE TITLE
PNG图片大屏显示为空的问题

### ISSUE THREAD

**Issue by JinhangZhu** [reuixiy/hugo-theme-meme#208]
Hi一休儿你好！我碰到的问题是：png图片在正常阅读时是可以显示的，不过在点击大屏显示时是一片空白。

## 效果
> 注：图片是一张人脸，背景较黑，可能需要预警。

见[图片位置](https://jinhang.work/tech/review-mtcnn/#%E4%BB%A3%E7%A0%81%E8%A7%A3%E8%AF%BB)，点击标题为`24×24边界框切片`的图片。

## 背景

- 我插入图片的代码：
```html
<img src="https://i.loli.net/2020/06/24/J9tj1d3FnRmirES.png" style="zoom:80%;" title="24×24边界框切片">
```

- 我的repo没有上传原始CSS等文件，只上传了public文件夹，如果需要看我的custom.css或者我修改的覆盖的文件，就麻烦你说一声。

**Comment by reuixiy** [comment]
你好啊！见 https://github.com/reuixiy/hugo-theme-meme/issues/80#issuecomment-600036438

**Comment by JinhangZhu** [comment]
太赞了！我通过修改custom.scss添加class解决了。
