### ISSUE TITLE
[bug]middle click link,it can change to light mode

### ISSUE THREAD

**Issue by jerry011235** [reuixiy/hugo-theme-meme#21]
When in the dark mode, middle click any link in the page, it can auto change to the light mode.

**Comment by reuixiy** [comment]
Hi @jerry011235,

I cannot reproduce this bug [on my blog](https://io-oi.me/) with Google Chrome in Linux.

What browser are you using? What is your operating system?

**Comment by jerry011235** [comment]
@reuixiy sorry, it's a not rigorous test.
after re-test,maybe the key is the stylus extension.
when the stylus extension installed, it reproduced on chrome 78 and firefox 69, win10;
when the stylus extension uninstalled, it can't reproduced.
