### ISSUE TITLE
正文的首个字符特大显示问题

### ISSUE THREAD

**Issue by LWP-PING** [reuixiy/hugo-theme-meme#210]
![image](https://user-images.githubusercontent.com/6804734/85950659-aef5e080-b990-11ea-8462-1efce800a723.png)
怎么可以取消这种大显示

**Comment by reuixiy** [comment]
https://github.com/reuixiy/hugo-theme-meme/blob/8ebbfa81a5a517038b24e20768b8db2dda812649/config-examples/zh-cn/config.toml#L950-L956
