### ISSUE TITLE
图片上阴影有办法去掉吗

### ISSUE THREAD

**Issue by georgehao** [reuixiy/hugo-theme-meme#211]
![image](https://user-images.githubusercontent.com/6947653/86012439-8d5c2e00-ba50-11ea-8f36-784ea360c176.png)
![image](https://user-images.githubusercontent.com/6947653/86012453-94833c00-ba50-11ea-8548-92cf4da09f61.png)

在白色模式下, 这些阴影太突兀了, 有开关吗

**Comment by georgehao** [comment]
或者能否做成自适应的

在白色模式下, 去掉这些阴影, 在dark模式下, 开启这些阴影

**Comment by reuixiy** [comment]
无法复现，可能是一个之前的 bug，请更新到最新版 MemE 后测试。
