### ISSUE TITLE
Search does not work on post page

### ISSUE THREAD

**Issue by charupatelmua** [reuixiy/hugo-theme-meme#214]
Steps to reproduce.
1. Create a default site.
2. Create one post.
3. Go to Home Page and search - Works
4. Go to one of the post and then search - Does not work

# Error
`Failed to load resource: the server responded with a status of 404 ()`
https://www.thedevbytes.com/posts/getting-started-with-git-a-step-by-step-guide-to-git/search.json

**Comment by reuixiy** [comment]
Unfortunately, I can't reproduce this with the *latest* Hugo and MemE.

**Comment by atul05kumar** [comment]
Working fine after updating to latest MemE.

**Comment by arkadianriver** [comment]
For anyone who stumbles across this from Google, another important step for search to work on pages other than the home page is to ensure the `baseURL` has a trailing slash. That fixed this issue for me (using the version at the `97cb67e` commit of master - Apr 15, 2021). Maybe that's a standard Hugo convention I wasn't fully aware of, but it tripped me up for a while.
