### ISSUE TITLE
关于  # 4. page普通页面的首页布局模式的疑问

### ISSUE THREAD

**Issue by gears233** [reuixiy/hugo-theme-meme#217]
你好，
       我在编辑主题配置文件的过程中，看到 MemE 主题提供有以下四种首页布局：
-  poetry    诗意人生
-  footage   视频片段
-  posts     文章摘要
-  page      普通页面

尝试选择了 page 首页布局的方式，进行预览，感觉和新建了一篇文章一样的感觉。
请问下如果想要编辑这个页面的话，应该编辑哪个文件？

**Comment by reuixiy** [comment]
content 下的 _index.md（需新建）
