### ISSUE TITLE
svg.toml help - included my Hugo build info

### ISSUE THREAD

**Issue by ctsdownloads** [reuixiy/hugo-theme-meme#219]
Hugo Version: Hugo Static Site Generator v0.73.0-428907CC/extended linux/amd64

Theme: themes.gohugo.io/hugo-theme-meme

Issue: Need to render my own svg logo, not sure how to edit svg.toml without breaking anything.

Stored in: siteroot/themes/meme/data

The SVG.toml file in question: https://justpaste.it/6qznx
(As you can see, there is one path d=)

My created svg image: https://justpaste.it/45mwn
(My created svg has multiple path d= which mean all attempts to using my svg have broken the theme as I run it locally on my local hugo instance)

What I need to do is get logo.svg into the SVG.toml file and do I then move the SVG.toml file from /siteroot/themes/meme/data/ into /siteroot/data/?

Thanks so much, been banging my head into this for sometime. In a static page, I’d just do this inline and be done with it. But this is confusing to me as I'm still learning how one uses a toml file for an svg.

Thank you

**Comment by JinhangZhu** [comment]
Yep, your description of copying and pasting the `SVG.toml` is right. And you only need to edit the new `SVG.toml`.

BTW you may check the author's another repo to compare the structure of files to yours. The link is here: https://github.com/reuixiy/io-oi.me/tree/master/data

**Comment by reuixiy** [comment]
@ctsdownloads,

Sorry for the delay. Just try to wrap your svg image with three quotation marks, see <https://toml.io>
