### ISSUE TITLE
Is it considered to include Valine in MemE?

### ISSUE THREAD

**Issue by Xuezenghuigithub** [reuixiy/hugo-theme-meme#22]

**Comment by reuixiy** [comment]
Hi @Xuezenghuigithub,

I just submitted a commit to support Valine, but I'm not sure if it works — I don’t use Valine now.

Also, I’m not sure about its compatibility with InstantClick.

**Comment by Xuezenghuigithub** [comment]
@reuixiy , thx, I followed the tutorial to add Valine in MemE but it doesn't work(or is my operation's fault). I will try again...

**Comment by reuixiy** [comment]
Hi @Xuezenghuigithub,

I just submitted a commit to fix that. Please refer to [this commit](https://github.com/reuixiy/hugo-theme-meme/commit/935c9d5bb7376bfc582784bb25d14d26f2cae77a) to modify your `config.toml` file.

Note that comments is only rendered in production environment. You can use `hugo server -D --environment production` if you want to test it in your local environment. And add `http://localhost:1313` to LeanCloud’s web secure domains list if you have enabled web secure domains. Also, make sure you have set `enableComments = true` in config.toml. One last reminder, comments won’t be added in non-mainSections page (e.g. about) unless you set `comments = true` in that page’s Front Matter.

**Comment by huangdiv** [comment]
> comments won’t be added in non-mainSections page (e.g. about) unless you set comments = true in that page’s Front Matter.

Hey, I have testing MemE themes for a while ,and thank you for adding valine support. When I set `enableComments = true` in config.toml, comment didn't work in my posts unless I mannually set `comments = true` in page's Front Matter. NOTICE I have set `category = "section" ` in config.toml, so which folder is my mainSection? How can I set comments true for all my posts? Thanks a lot.

**Comment by reuixiy** [comment]
Hi @huangdiv,

```diff
    ######################################
    # 文章分区范围


    # 说明：分区的名字即站点的 content 目录下
    #      的文件夹的名字。


-   # mainSections = ["posts"]
+   mainSections = ["posts"]
```

**Comment by Xuezenghuigithub** [comment]
@huangdiv hello, Could I talk with you about how to add Valine to MemE? I tried, but it always doesn't work.😥

**Comment by huangdiv** [comment]
@reuixiy still the same , 
I have a `tech` folder with some posts  in content dir as in you blog and have set
`mainSections = ["tech"]`
 in config.toml. Comments not show as default in posts in `tech` folder for me.
BTW, since ur blog have changed to category by section, why not do so in MemE? ths a lot.

**Comment by reuixiy** [comment]
@huangdiv `hugo server -D --environment production`

**Comment by reuixiy** [comment]
And if it still doesn't work, please update MemE to the latest version.

---

> BTW, since ur blog have changed to category by section, why not do so in MemE?

It’s better but not the choice for *most* people. Most people put their posts in a single folder (_posts, posts, post) and category them by `categories` in post’s Front Matter. Users will need more time to fit Hugo if I set `categoryBy` to `sections`... And I need more words to explain that...

**Comment by huangdiv** [comment]
![IMG_20191130_153722](https://user-images.githubusercontent.com/55480312/69897513-b2e65500-1312-11ea-83cb-6ba996c9a031.jpg)
Valine is ok now...
I have forgotten to open this main switch...

**Comment by huangdiv** [comment]
@reuixiy, May you add a feature in config.toml to let the users set comments default to work in specific sections?
Thank u for your reply.

**Comment by huangdiv** [comment]
@Xuezenghuigithub, Sure, just describe what trouble you have met？

**Comment by reuixiy** [comment]
@huangdiv I’m afraid I won't do that... Perhaps you can do it yourself!

1. Refer to [this commit](https://github.com/reuixiy/hugo-theme-meme/commit/15a86acb78a6af75885e8b57c17556368aa17e28)
2. Copy the relevant files from theme directory to the site directory, e.g.
    ```
    ~/blog/themes/meme/layouts/partials/comments.html -> ~/blog/layouts/partials/comments.html
    ```
3. Modify as you need

**Comment by Xuezenghuigithub** [comment]
@huangdiv Do you have updated MemE to the latest version to use Valine? I added about Valine's code in the old version, but it doesn't work. I want to know that the specific steps for you to add Valine  ...

**Comment by huangdiv** [comment]
1.FOLLOW https://valine.js.org/quickstart.html#获取APP-ID-和-APP-Key to register your LeanCloud app. You may need to do real name verification unless you select International Edition. If you have done that, don't forget  to set secure domain name in LeanCloud app settings. Refer to this:
![5d0c995bddd4f99219](https://user-images.githubusercontent.com/55480312/69935718-5c585280-149b-11ea-9643-50c2c8c9c299.jpg)
2. Enable Valine comments in site's config.toml:`enableComments=true`, `enableValine=true`, `valineAppId=*`, `valineAppKey=*`. Replace  `*` in `valineAppId` and `valineAppKey` with the help of first step.Others just leave as default.
3. Valine will default to work in mainSection posts now.  But if you want test valine comments locally, you should add `https://localhost:1313` in your secure domain name in step 2, and run `hugo server -D --environment production`.

**Comment by Xuezenghuigithub** [comment]
@huangdiv thx, after I updated MemE to the latest version, Valley worked~✌️
