### ISSUE TITLE
theme的版本要求？

### ISSUE THREAD

**Issue by summerwithnostory** [reuixiy/hugo-theme-meme#221]
用的是Hugo Static Site Generator v0.60.1/extended darwin/amd64 BuildDate: unknown

然后在跟教程走的时候就遇到了这个
Error: add site dependencies: load resources: loading templates: "/*****/themes/meme/layouts/partials/third-party/lunr-search.html:8:1": parse failed: template: partials/third-party/lunr-search.html:8: function "warnf" not defined

**Comment by gears233** [comment]
最近更新的 theme.toml 里面明确写了 ：  min_version = "0.73.0"
另外 hugo 最新更新到 0.74 了

**Comment by reuixiy** [comment]
是的，见 theme.toml
