### ISSUE TITLE
Safari mysterious font rendering bug

### ISSUE THREAD

**Issue by driftingdream** [reuixiy/hugo-theme-meme#224]
https://xuezenghui.com/posts/principle-of-vue-two-way-data-binding/#较完整实现
如在这这链接中，在段首会出现方框中有个叉叉的符号与文字重叠了（图一）。这可能与1. 2. 3. 这样的排版有关，在我的本地blog测试中也出现了问题，见图2。
这个问题用Mac的Safari会出现，chrome，firefox均无问题，iOS设备没有测试
<img width="727" alt="image" src="https://user-images.githubusercontent.com/16973422/87847943-78b3dd00-c90e-11ea-843a-b0102b003cd8.png">
<img width="620" alt="image" src="https://user-images.githubusercontent.com/16973422/87848012-fed02380-c90e-11ea-8d88-99de54ac7e5f.png">

**Comment by reuixiy** [comment]
See #109.
