### ISSUE TITLE
Pin posts on top of the list

### ISSUE THREAD

**Issue by AngangGuo** [reuixiy/hugo-theme-meme#225]
Please add feature to pin favourite posts on top of the list which are always available at first page.
Thanks.

**Comment by JinhangZhu** [comment]
@AngangGuo You can implement it by configuring the `weight` option in the front-matter.

**Comment by AngangGuo** [comment]
I added different `weight` to two of my files but the order is the same.
(eg. `weight: 3` and `weight: 5`)
```
---
title: "Notes - Linux"
date: 2020-07-14T10:07:09-07:00
categories:
 - Tech
 - OS
tags:
 - Ubuntu
weight: 3
draft: false
---
```

**Comment by JinhangZhu** [comment]
@AngangGuo Sorry for the late reply. In my case, I could not reproduce your issue. So we may look forward to another reply.

**Comment by AngangGuo** [comment]
Sorry, my fault, the posts changed the order in my home page. 
Last time I just checked the posts list page and the order doesn't change.
Thanks.
