### ISSUE TITLE
希望或建议对文章目录布局的位置进行改变

### ISSUE THREAD

**Issue by linwhitehat** [reuixiy/hugo-theme-meme#228]
目前在尝试使用最新版的meme主题，尽管还不太熟悉，但是从目前的阅读效果来看，个人想提个关于目录的建议。
当前的文章目录是出现在文章最上方的位置，但是对于阅读到文章中间部分想跳转到其他部分时需要先点击回到最顶部然后再从目录跳转，建议可以把文章目录区域移动到左侧或右侧固定区域，类似这种效果：
![image](https://user-images.githubusercontent.com/20349381/88398693-503d4e80-cdf8-11ea-8033-1b4eaedab3c8.png)

**Comment by he-sb** [comment]
个人也有同感，但是这个主题的设计就是单列的极简排版，这个功能应该是不会加了 🙈

**Comment by JinhangZhu** [comment]
+1，作者说过他的设计理念https://github.com/reuixiy/hugo-theme-meme/issues/64#issuecomment-585802485 ，所以应该是不会添加功能了，想实现的得自己写代码了

**Comment by cmwode** [comment]
+1
