### ISSUE TITLE
Strange characters at the top of posts in mobile

### ISSUE THREAD

**Issue by guinuxbr** [reuixiy/hugo-theme-meme#229]
Hi, I'm facing some strange characters at the top of posts in mobile browsers.

I've tested Firefox and Chrome and both of them shows this strange characters.

Can you please take a look?
https://i.imgur.com/zdUZ4FH.png

**Comment by reuixiy** [comment]
That's weird. Have you added these “strange characters” somewhere?

**Comment by guinuxbr** [comment]
Hi.

I've updated the theme and rebuilt the whole site from scratch and everything is ok now.
Maybe was some mess made by me.
