### ISSUE TITLE
Google-Ad-Sense

### ISSUE THREAD

**Issue by theflyingfool** [reuixiy/hugo-theme-meme#23]
Maybe I just missed the option in the config file, but would it be possible to add google-ad-sense.

**Comment by reuixiy** [comment]
Hi @theflyingfool,

I just submitted a commit to support Google AdSense, but I'm not sure if it works — I have never used Google AdSense.

Also, I’m not sure about its compatibility with InstantClick.

**Comment by theflyingfool** [comment]
I've got it turned on, Will report back after google "verifies" my site "This usually takes a few days, but in some cases can take up to 2 weeks".

**Comment by theflyingfool** [comment]
I think its almost right.  I think the code should end up :
<script data-ad-client={{ .Site.Params.googleAdClient }} async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
between the <head></head>

From what I can tell by view source on my live site it is in the right space but split into the async at the top and, the ad-client id later.

![image](https://user-images.githubusercontent.com/2403507/69996948-18a82c00-1521-11ea-8bd9-78bffd7606a4.png)

**Comment by reuixiy** [comment]
I think that should be fine. First, [load the script](https://github.com/reuixiy/hugo-theme-meme/blob/master/layouts/partials/third-party/google-adsense.html); Second, [push your ad client](https://github.com/reuixiy/hugo-theme-meme/blob/master/layouts/partials/third-party/google-adsense-auto.html). So the ad client is not missing.

I just visited your site and saw some ads. It displays well but seems quite chaos... Then I found out you disabled the `GoogleAutoAds` but enabled the `GoogleAdUnits` without `googleAdSlot`... Note that the ad units is different from auto ads and it requires an ad slot id.

Also, it seems that AdSense does not work well with InstantClick. But first of all, please make sure your configuration is right. Then I knew what things I could do for this.
