### ISSUE TITLE
简码的css样式无法覆盖浏览器的用户代理样式表

### ISSUE THREAD

**Issue by linwhitehat** [reuixiy/hugo-theme-meme#230]
在简码中增加了checkbox，想针对此进行css修改设置，设置了checkbox背景和边框色彩，但是仍然默认用户代理样式表内容。
![image](https://user-images.githubusercontent.com/20349381/88511622-bce26400-d017-11ea-9d1d-e6d43a913458.png)
![image](https://user-images.githubusercontent.com/20349381/88511635-c370db80-d017-11ea-9e5e-79b192dc8a6f.png)

**Comment by reuixiy** [comment]
往 `~/blog/assets/scss/custom/_custom.scss` 添加 CSS，自行定制

**Comment by linwhitehat** [comment]
> 往 `~/blog/assets/scss/custom/_custom.scss` 添加 CSS，自行定制
> 
> https://github.com/reuixiy/hugo-theme-meme#customize-meme

我在_custom.scss添加了自己的css代码，但是在浏览器中渲染会显示“用户代理样式表”或者直接没有效果，为何我添加的渲染代码都没有效果😢
比如我添加了复选框，然后对其背景颜色进行修改，可是没有渲染效果
![image](https://user-images.githubusercontent.com/20349381/89714295-1fe8d900-d9d0-11ea-9181-d1a111bef22f.png)

**Comment by reuixiy** [comment]
CSS 问题，建议搜索相关文章 DIY
