### ISSUE TITLE
关于markdown的一些疑问

### ISSUE THREAD

**Issue by cym2050** [reuixiy/hugo-theme-meme#236]
![image](https://user-images.githubusercontent.com/28197412/89646823-150a4780-d8ef-11ea-9bc4-f46d7968aa59.png)
![image](https://user-images.githubusercontent.com/28197412/89646878-28b5ae00-d8ef-11ea-9aa9-19a7576c0a74.png)
回车不自动换行，只能使用空一行换行，请问这是配置里面可以修改的吗？

**Comment by he-sb** [comment]
这是 Markdown 格式的 feature 不是 bug 🤣

**Comment by reuixiy** [comment]
@cym2050 `hardWraps`

**Comment by cym2050** [comment]
> @cym2050 `hardWraps`

谢谢,修改hardWraps能解决我的问题

**Comment by cym2050** [comment]
> 这是 Markdown 格式的 feature 不是 bug 🤣

懂了，以前用的编辑器可以回车换行让我误以为这是个feature了，不过这个主题挺好的，有配置可以修改这个
