### ISSUE TITLE
鼠标移出时，导航栏显示不正常

### ISSUE THREAD

**Issue by aigooman** [reuixiy/hugo-theme-meme#240]
当鼠标移出页面时，导航栏上有时会出现黑色阴影，如下图所示。
浏览器版本为Microsoft Edge 84.0.522.58 (官方内部版本) (64 位)，已关闭除SwitchyOmega外所有扩展，测试页面为[https://io-oi.me/tech/timelapse-with-raspi/](https://io-oi.me/tech/timelapse-with-raspi/)
![3](https://user-images.githubusercontent.com/32329730/89973332-ab918c80-dc92-11ea-97aa-dfd5af3e4095.png)
![1](https://user-images.githubusercontent.com/32329730/89973344-b0eed700-dc92-11ea-8e89-35870e47fa6c.png)
![2](https://user-images.githubusercontent.com/32329730/89973356-b6e4b800-dc92-11ea-961e-c814a8ca0c23.png)

**Comment by Borber** [comment]
我之前也有遇到过 但是后来不知道怎么就没了
