### ISSUE TITLE
怎么增加页面显示宽度呢？

### ISSUE THREAD

**Issue by chengshuyi** [reuixiy/hugo-theme-meme#241]
怎么增加页面显示宽度呢？

**Comment by Borber** [comment]
应该是这里  [页面宽度](https://github.com/reuixiy/hugo-theme-meme/blob/5470cbe6c4c8e726e81bba7cb5dc45863678281f/config-examples/zh-cn/config.toml#L400)

**Comment by chengshuyi** [comment]
> 应该是这里 [页面宽度](https://github.com/reuixiy/hugo-theme-meme/blob/5470cbe6c4c8e726e81bba7cb5dc45863678281f/config-examples/zh-cn/config.toml#L400)

是的，谢谢。
