### ISSUE TITLE
valine评论 想要类似这样的的表情效果

### ISSUE THREAD

**Issue by Borber** [reuixiy/hugo-theme-meme#243]
![image](https://user-images.githubusercontent.com/30563826/90599663-d4cc9280-e227-11ea-87e2-1ccc5f5cd9d3.png)

感觉很舒服 比较顺滑 附上地址 https://www.catct.cn/

**Comment by JinhangZhu** [comment]
https://github.com/JinhangZhu/jinhang.work/commit/55d6e8265a2558c1ad87cf0434a5a47550a41f4c 仅供参考

**Comment by Borber** [comment]
> [JinhangZhu/jinhang.work@55d6e82](https://github.com/JinhangZhu/jinhang.work/commit/55d6e8265a2558c1ad87cf0434a5a47550a41f4c) 仅供参考

额 你注意到 标签有个框框框着嘛? 就是分成一块一块的 还有 hover效果 我加了表情 希望效果比较顺滑

**Comment by JinhangZhu** [comment]
@Borber 演示的评论确实很好看，不过我觉得这个issue应该在https://github.com/xCss/Valine/issues 提，这个仓库不涉及valine评论框的风格设计，只提供接口。

**Comment by Borber** [comment]
> @Borber 演示的评论确实很好看，不过我觉得这个issue应该在https://github.com/xCss/Valine/issues 提，这个仓库不涉及valine评论框的风格设计，只提供接口。

哦哦 我以为 作者大大是自己写的 valine 主题
