### ISSUE TITLE
hugo server -D         failed

### ISSUE THREAD

**Issue by VegeBun-csj** [reuixiy/hugo-theme-meme#245]
when i click this command 
$ hugo server -D
--------------------
this error eixsted after the command
Building sites … Built in 56 ms
Error: Error building site: TOCSS: failed to transform "zh/styles/main-rendered.scss" (text/x-scss): resource "scss/scss/main.scss_a059ebc49e8302e6cfbf0e02020b9d85" not found in file cache

**Comment by chuckleong21** [comment]
## Error building site

```
Start building sites …
Built in 49 ms
Error: Error building site: TOCSS: failed to transform "en/styles/main-rendered.scss" (text/x-scss): SCSS processi
ng failed: file "stdin", line 245, col 17: Invalid CSS after "$fofPoster: url(": expected expression (e.g. 1px, bo
ld), was "<no value>);"

% hugo version
Hugo Static Site Generator v0.80.0/extended darwin/amd64 BuildDate: unknown
```

It still fails after a reinstallation of hugo via homebrew, what seems to be the problem?

**Comment by chuckleong21** [comment]
> ## Error building site
> ```
> Start building sites …
> Built in 49 ms
> Error: Error building site: TOCSS: failed to transform "en/styles/main-rendered.scss" (text/x-scss): SCSS processi
> ng failed: file "stdin", line 245, col 17: Invalid CSS after "$fofPoster: url(": expected expression (e.g. 1px, bo
> ld), was "<no value>);"
> 
> % hugo version
> Hugo Static Site Generator v0.80.0/extended darwin/amd64 BuildDate: unknown
> ```
> 
> It still fails after a reinstallation of hugo via homebrew, what seems to be the problem?

Fixed. Users need to download the extended version from [Github](https://github.com/gohugoio/hugo/releases) while the binary doesn't work via Homebrew.

```
hugo version
Hugo Static Site Generator v0.80.0-792EF0F4/extended darwin/amd64 BuildDate: 2020-12-31T13:44:15Z
```
