### ISSUE TITLE
CSS生成失败

### ISSUE THREAD

**Issue by chensu92** [reuixiy/hugo-theme-meme#248]
Building sites … ERROR 2020/08/27 13:57:06 TOCSS: failed to transform "en-us/styles/main-rendered.scss" (text/x-scss): resource "scss/scss/main.scss_7c1638c5361dae205d19f92030523cc2" not found in file cache
Total in 144 ms
Error: Error building site: TOCSS: failed to transform "zh-cn/styles/main-rendered.scss" (text/x-scss): resource "scss/scss/main.scss_97694fc9387dd6504ca8bcd452f8e3cf" not found in file cache

**Comment by reuixiy** [comment]
See #245.
