### ISSUE TITLE
请问修改main.scss_a899b346ffc3a4bc65b84e40528dea51.content文件前端css直接乱了。

### ISSUE THREAD

**Issue by cscwdxgg** [reuixiy/hugo-theme-meme#251]
请问修改main.scss_a899b346ffc3a4bc65b84e40528dea51.content里面的--color-bg:hsl(0, 0%, 100%);修改为hsl(45,100%,98.4%)。之后前端直接乱掉了。

前端报错信息
Failed to find a valid digest in the 'integrity' attribute for resource 'http://h.918q.top/css/meme.min.e85645f1a691e2b7781894b893994d6a26ce7c51ae5fcf5507b1833063cc6b3c.css' with computed SHA-256 integrity 'AIPe/8FsPvdwVELlc5jp4sg7BeHhS9kX1sbyvu2zJAg='. The resource has been blocked.

**Comment by reuixiy** [comment]
这个是自动生成的文件，不宜修改。

如果想要自定义样式，见[定制 MemE](https://github.com/reuixiy/hugo-theme-meme/blob/master/README.zh-cn.md#%E5%AE%9A%E5%88%B6-meme)。
