### ISSUE TITLE
请问SVG图标应该怎么使用呢？

### ISSUE THREAD

**Issue by timewaitsfor** [reuixiy/hugo-theme-meme#255]
一休儿你好~
真的超喜欢这个博客，简洁又好看，我看文档里有“MemE 无需加载任何图标库——主题的图标是通过 Hugo 的数据模板直接将 SVG 嵌入到 HTML 中实现”这样的说法，但是应该怎么使用呢？具体怎么操作。是不是有什么代码块，可以直接调用SVG.toml中的关键字就可以使用SVG图标了呢？期待你的回复~

**Comment by reuixiy** [comment]
你好，

是这样的，但只限于配置文件中的使用

如果你想在文章中使用的话，可能需要自己新建一个 Hugo 的 shortcode 实现
