### ISSUE TITLE
请问如何实现两张图片的并列排版呢？

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#258]
小白求教：就比如说两张16:9的手机截图，默认是放大至文章内容边距，能不能让这两张图片并列排布呢？这样也能更好地利用空间。

**Comment by ZhaoTim** [comment]
<div style='display: flex;'>
 <img src='' />
 <img src='' />
</div>

**Comment by ZhaoTim** [comment]
可以使用HTML:
```html
<div style='display: flex;'>
    <img src='' />
    <img src='' />
</div>
```

**Comment by reuixiy** [comment]
我记得有其它主题有相关的 shortcode

可以搜索参考一下

当然，直接写 HTML 也可以的
