### ISSUE TITLE
Error building site

### ISSUE THREAD

**Issue by S1nus** [reuixiy/hugo-theme-meme#259]
after running `hugo server -D`

I get

`Error: Error building site: TOCSS: failed to transform "en/styles/main-rendered.scss" (text/x-scss): resource "scss/scss/main.scss_a899b346ffc3a4bc65b84e40528dea51" not found in file cache`

**Comment by reuixiy** [comment]
See #245

**Comment by wangxinzhi0** [comment]
Had you fix this problem?
