### ISSUE TITLE
Hugo v0.60.0 (compatibility with goldmark)

### ISSUE THREAD

**Issue by reuixiy** [reuixiy/hugo-theme-meme#26]
Hugo [v0.60.0](https://github.com/gohugoio/hugo/releases/tag/v0.60.0) replaced the **default** Markdown renderer [blackfriday](https://github.com/russross/blackfriday) with [goldmark](https://github.com/yuin/goldmark/). I just tried v0.60.0 with goldmark and found some problems. These issues **cannot** be resolved at this time. I will fix them when Hugo releases a more **stable** version in the future...

**Comment by reuixiy** [comment]
If you have installed the latest version of Hugo, you can add the following code to the config.toml file to use the old blackfriday instead of the new goldmark...

```toml
[markup]
    defaultMarkdownHandler = "blackfriday"
```

More info https://gohugo.io/getting-started/configuration-markup/

**Comment by theflyingfool** [comment]
I'm using a test box:
```
hugo version
Hugo Static Site Generator v0.61.0/extended linux/amd64 BuildDate: unknown

hugo server -D --disableFastRender
```
When I look at the output in chrome at localhost:1313 I'm not noticing anything strange. Could you please eleberate as to what it is doing

Granted it could have to do with having the following in my config.toml:
```

# Markdown rendering engine
[blackfriday]
  # Enable smart punctuation substitutions?
  smartypants = true
  # Open external links in a new window or tab?
  hrefTargetBlank = true
  # Disable some Blackfriday's Markdown extensions
  extensionsmask = ["hardLineBreak", "backslashLineBreak"]

```  

I have not added the workaround listed above to my config file yet

Was not able to copy and paste anything there may be typo's above

**Comment by reuixiy** [comment]
I see... It’s okay to use new default Markdown renderer goldmark if you have not encountered any strange changes. I recommend using old blackfriday because there are currently some issues ([here](https://github.com/gohugoio/hugo/issues?utf8=%E2%9C%93&q=goldmark) and [here](https://discourse.gohugo.io/search?q=goldmark)) related to goldmark. But since you have not encountered any strange changes, just use the brand new goldmark!
