### ISSUE TITLE
Styling the Post Meta Info

### ISSUE THREAD

**Issue by craigsimon** [reuixiy/hugo-theme-meme#260]
Hello,

This is a great theme!   I am wondering where / how I can style the post meta info on the homepage.  When it's displayed in dark mode the meta info is styled as completely black.  I'd like to change the colors of the text and icons there.

Is that possible?
Thanks

**Comment by reuixiy** [comment]
Hi,

> Is that possible?

Yes, see #108 

> When it's displayed in dark mode the meta info is styled as completely black.

That's not the expected behavior, could you paste a live link or a image here?
