### ISSUE TITLE
请问 gitinfo 正确开启方式是什么？

### ISSUE THREAD

**Issue by RivTian** [reuixiy/hugo-theme-meme#261]
目前不知道为什么只有一篇Hello World才开启了这个
![1](https://cdn.jsdelivr.net/gh/Kanna-jiahe/blogimage/img/20201025193340.png)
而其他却没有显示。
![2](https://cdn.jsdelivr.net/gh/Kanna-jiahe/blogimage/img/20201025193417.png)

**Comment by reuixiy** [comment]
尝试下 #27
