### ISSUE TITLE
categoryby为categories时，分类页面的「阅读更多」为空白

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#262]
请 reuixiy 有时间帮我看看是咋回事了？

[分类页面](https://dawner.top/categories/about-tech/)

**Comment by reuixiy** [comment]
更新到最新版本的 Hugo 即可解决

**Comment by dawnow** [comment]
@reuixiy 好了，谢谢 reuixiy 解答！
