### ISSUE TITLE
代码横向滚动条的问题

### ISSUE THREAD

**Issue by Wjiajie** [reuixiy/hugo-theme-meme#263]
你好，meme主题的代码的横向滚动条可以在当前显示页面显示吗，比如下图：

[图一](https://i.loli.net/2020/11/06/UDzO4W7S1yvGdPA.png)

这是下拉到代码块的最后面才显示的横向滚动条，但在其他位置是不显示的：

[图二](https://i.loli.net/2020/11/06/ultSBT6y2oCinrk.png)

我想的是如果能随时显示滚动条，看代码会方便一些～

**Comment by reuixiy** [comment]
这应该是多数人的预期行为，实现滚动条在视图底部的固定可能反而会让用户感觉很奇怪，所以我应该不会去实现。

不管怎么说，这应该是一个超长超宽代码块的显示设计问题，我目前发现的比较好的方案是 dev.to 的网页全屏显示，见 <https://github.com/reuixiy/hugo-theme-meme/issues/288>。
