### ISSUE TITLE
Error: Error building site: TOCSS

### ISSUE THREAD

**Issue by wangxinzhi0** [reuixiy/hugo-theme-meme#264]
Hello, I have an error when using this theme. Please do me a favor, thank you!

Error: Error building site: TOCSS: failed to transform "zh/styles/main-rendered.scss" (text/x-scss): resource "scss/scss/main.scss_a059ebc49e8302e6cfbf0e02020b9d85" not found in file cache

**Comment by reuixiy** [comment]
See https://github.com/reuixiy/hugo-theme-meme/issues/245
