### ISSUE TITLE
[Feature] Request to support both zh-CN and zh-TW

### ISSUE THREAD

**Issue by ayalhw** [reuixiy/hugo-theme-meme#265]
now only a zh...

**Comment by xdhuxc** [comment]
@ayalhw what is zh-TW?

**Comment by ayalhw** [comment]
> @ayalhw what is zh-TW?

zh-Hant-TW，台湾标准的繁体中文

**Comment by reuixiy** [comment]
@ayalhw 

Considering the simplicity and number of users, MemE uses `zh` as an alias for `zh-cn`.

Feel free to add an `zh-tw.toml` file under `i18n/` to support it. And create a pull request, if you wish.

**Comment by ayalhw** [comment]
ok, I will have a try and then create a pull request
