### ISSUE TITLE
关闭网络字体时 Firefox 下脚注字间距异常

### ISSUE THREAD

**Issue by 1sixth** [reuixiy/hugo-theme-meme#267]
## 复现步骤

1. 输入以下命令：

```bash
hugo new site test
cd test
git init
git submodule add --depth 1 https://github.com/reuixiy/hugo-theme-meme.git themes/meme
cp themes/meme/config-examples/zh-cn/config.toml config.toml
hugo new "posts/hello-world.md"
```

2. 编辑 `config.toml`，将 `fontsLink` 留空。

3. 向 `hello-world.md` 中添加以下内容：

```markdown
[^1]
[^1]: https://wiki.archlinux.org/index.php/Hardware_video_acceleration#Application_support
```

4. 输入 `hugo server -D`，使用 Firefox 打开 <http://localhost:1313/posts/hello-world/>

这是 Arch Linux 下 Firefox 的显示情况：
![Screenshot_2020-11-22 Hello World](https://user-images.githubusercontent.com/67363572/99896452-a8fbf580-2ccb-11eb-9771-3b2737c474ba.png)

Windows 10 下 Firefox 显示情况类似，字间距也有问题。

## 测试时发现的事

1. 开启网络字体时，Firefox 显示正常。
2. 如果使用英文的示例配置（即 `themes/meme/config-examples/en/config.toml`），将 `fontsLink` 留空后，Firefox 下也显示正常。
3. 在所有情况下，Chromium 显示正常。

## 测试环境

1. Arch Linux

- WM: Sway
- Firefox: 83.0-1
- Chromium: 86.0.4240.183-1
- Hugo: 0.78.1-1
- 安装的部分字体：`noto-fonts`、`noto-fonts-cjk`
- Firefox Inspect 脚注时观察到使用了 `Noto Serif` 字体

2. Windows 10 专业版 20H2

- Firefox: 83.0
- Chrome: 86.0.4240.198
- Hugo: 0.78.2
- 未额外安装任何字体
- Firefox Inspect 脚注时观察到使用了 `SimSun` 字体

**Comment by reuixiy** [comment]
把两端对齐关闭即可

https://github.com/reuixiy/hugo-theme-meme/blob/33d03e8292d55f46fecc3e5a89e88dfe30df4069/config-examples/zh-cn/config.toml#L944

**Comment by 1sixth** [comment]
关闭两段对齐后字间距正常了，感谢。
