### ISSUE TITLE
[QUESTION] Disable anchor link generation in single page

### ISSUE THREAD

**Issue by michael0liver** [reuixiy/hugo-theme-meme#276]
Hi, first off great theme 👍🏻 😄 

Is there a way i can disable anchor link for a single page? I would like to disable for my about page. Thanks

**Comment by reuixiy** [comment]
Unfortunately, there is no such option for that temporarily. But we can implement it!

**Comment by michael0liver** [comment]
@reuixiy Awesome, thanks for the quick turn around. 😎
