### ISSUE TITLE
编译-hugo和hugo server -D运行结果不符

### ISSUE THREAD

**Issue by Kurby96** [reuixiy/hugo-theme-meme#28]
hello，reuixiy

我直接用中文了，我提2个问题。
1、我用的是 poetry    诗意人生的主题，我把你的life文件夹重命名为read，在里面添加一些内容，
问题1.1：当我运行 hugo server -D 时，可以显示出read栏的内容，当hugo server 时，网页没有显示出来，提示404 page not found。
问题1.2：而且当我 执行 hugo时，在public中也是没有read文件夹的。
还有个疑问：编译hugo 和运行本地测试hugo执行的命令分别是什么，是不是我运行命令的问题。
2、
![MV26VF72 )B B_ZBH1 }KVY](https://user-images.githubusercontent.com/58101763/69909362-6e9fa580-1435-11ea-9a13-7845f82bb514.png)
图片中的字体怎么更改格式和字体的大小，我昨天搞了4-5个小时，没弄出来.........

**Comment by reuixiy** [comment]
## 命令

参数 `-D` 的意思是包括草稿，Hugo 默认会为 `hugo new` 新建的文章的 Front Matter 中添加 `draft: true`，即为草稿，你可以自行打开文章看看。将之删除或设置为 `false`，即可解决你的问题。

你也可以修改[默认模板](https://github.com/reuixiy/io-oi.me/tree/master/archetypes)，将 `draft: true` 删除，这样你每次新建的文章里面就不会有该项，你的文章也就不是草稿，你也就不用每次都添加 `-D` 参数了。

https://gohugo.io/commands/hugo/
https://gohugo.io/commands/hugo_server/

## 字体

对于网页上的字体显示，是取决于网页的样式（CSS）和系统字体的。

你可以在 CSS 中指定你想要的字体，在 MemE 中这可以直接在 `config.toml` 中[配置](https://github.com/reuixiy/hugo-theme-meme/blob/dce3462123144fdfc9acebdc2107ee1da1173a35/config-examples/zh-cn/config.toml#L774-L810)。如果没有在 CSS 中指定，用的肯定是系统默认的字体。对于你的情况，即列表标题的字体，可以在 `fontFamilyTitle` 项中配置。

但是，如果你指定的字体在用户的操作系统中压根没有安装，那么它肯定是不可能被正确渲染的。因此，要确保你的用户看到的一定是你指定的字体，就要启用网络字体，见 MemE 主题的配置示例中的说明。

**Comment by reuixiy** [comment]
## 字号

对于字号，即字体的大小，MemE 不支持在配置文件 config.toml 中配置。在 MemE 中，各元素的字号是直接按比例设计的——都是基于正文的字号的。

如果你需要指定某一元素的字体，浏览器按下 F12，找元素（流程可参考我的[这篇老文章](https://io-oi.me/tech/hexo-next-optimization/#优化-网页样式布局)，但注意那篇文章是在 Hexo 而不是在 Hugo 中），然后将 CSS 代码复制到 `~/blog/assets/_custom/costom.styl`（没有自建）。

对于你的情况，即列表标题的字号，即将

```css
.list-title {
    font-size: 3em;
}
```

加入到 `costom.styl` 文件中去。当然，字号的值你可以自己定义了，数字可以变，单位也可以变，比如 `28px`。

**Comment by Kurby96** [comment]
hello,reuixiy
哇哦~真的是一语中地，之前的问题完美解决，我今天看你的博客发现了下面这部分，我把这部分的代码铐到我本地测试，发现艺术字和视频都没有显示，如下图：
![image](https://user-images.githubusercontent.com/58101763/69911983-3cef0480-145e-11ea-9700-56e5c7efda29.png)
![image](https://user-images.githubusercontent.com/58101763/69911992-5ee88700-145e-11ea-96ba-8e1f580c05c1.png)
![image](https://user-images.githubusercontent.com/58101763/69912067-7b38f380-145f-11ea-9779-2fdd821e36ce.png)
![image](https://user-images.githubusercontent.com/58101763/69912083-a3c0ed80-145f-11ea-88ea-11b9b10b0b28.png)
有2个问题：
1、Front Matter中设置的video路径和在正文中用html来设置有区别吗？有什么区别？ 
2、我如果想要添加艺术字和视频，应该如何操作，看来你之前的博文，知道用[DTube](https://d.tube/) 但是还不知道具体如何操作，

菜鸡一枚，
劳烦了

**Comment by reuixiy** [comment]
> 1、Front Matter中设置的video路径和在正文中用html来设置有区别吗？有什么区别？

我为 Coldplay 分区下的文章自定义了布局模板，所以我可以在 Front Matter 中用 `video` 来指定视频地址，见 https://github.com/reuixiy/io-oi.me/tree/master/layouts/coldplay

> 2、我如果想要添加艺术字和视频，应该如何操作

1. 艺术字
添加个 `class`，往 `custom.styl` 中加 CSS 代码即可。这里我是自己添加了一个 `viva-la-vida` 的 Class，然后在 [`custom.styl`](https://github.com/reuixiy/io-oi.me/blob/fe1017cf1cbccac0fdd47a45d48f52cc2842bdeb/assets/scss/_custom/custom.scss#L1-L9) 中指定了它的字体和渐变色样式。当然，要保证字体一定能完美显示，就要加网络字体，即确保你 config.toml 中的 `fontsLink` 有该字体。

2. 视频
我现在是直接在 [Pinata](https://www.pinata.cloud/) 上传的视频，然后获取到 Hash 值，在文章中手动插入 HTML 代码
    ```html
    <video src="QmZgXJwFNRAyUEuU36jReXtyjESeTWEGZpcJGuWSnbRTf1" ...
    ```
    最后在 config.toml 中配置下视频的[外链地址](https://github.com/reuixiy/io-oi.me/blob/fe1017cf1cbccac0fdd47a45d48f52cc2842bdeb/config.toml#L780-L792)。

> `draft = false`

最后，看到你的最后一张截图，顺便提醒下：Hugo 默认的 `draft` 的值是 `false`，故没有必要添加 `draft = false`，删除即可。

**Comment by reuixiy** [comment]
## 搬运邮件上的内容

> 你好， 我把你的链接填成你的，xxx.md的哈希值也是你视频的，填好这2个视频还是没加载出来，还需要更改custom.styl的内容嘛？

注意上方的「仅在生产环境下渲染」，故如果你要用 `hugo server` 命令本地预览，还需添加 `--environment production` 参数，即 `hugo server -D --environment production`；对于生成 public 文件夹的 `hugo` 命令，则不用，它默认就是生产环境。

> 我刚刚用生产环境测试了一下，还是没效果(pinate的链接和哈希值都用你博客里的)，另外问一句，pinate  (https://gateway.pinata.cloud/ipfs/ )这个链接gateway是你自己起的名字嘛？还是是固定的

Pinata 是一个 IPFS 服务提供商，你可以将链接替换为任何 IPFS 服务提供商的地址。

如果仍然无法显示，可以是你使用的是 v0.60.0 版本以上的 Hugo，而这些版本的 Hugo 的默认的 Markdown 渲染器 Goldmark 默认不会渲染 HTML。因此，请使用旧的 Blackfriday 渲染器，往 config.toml 中添加一项即可。

如果你不理解第一段，请看我写的那篇文章。如果你不知道应该添加什么内容，请查看 MemE 的示例配置的改动历史，我博客上的 MemE 文档一文对此有说明。

最后，邮件不再回复，若还有问题请移步 GitHub。望理解！

**Comment by reuixiy** [comment]
更正：是 `custom.scss` 而非 `custom.styl`……
