### ISSUE TITLE
代码块渲染问题

### ISSUE THREAD

**Issue by cmwode** [reuixiy/hugo-theme-meme#284]
问题:
如图, 这是在typora中的( != ):
![图片](https://user-images.githubusercontent.com/42599739/102693319-b8337c00-4254-11eb-8821-1fe14d112dc7.png)

但是在meme中变成:
![图片](https://user-images.githubusercontent.com/42599739/102693348-e6b15700-4254-11eb-8afb-c191595f4900.png)

在meme中复制的代码也是这种不等号, 这在程序中是错误的

请问如何保证源代码发布后不变.

**Comment by he-sb** [comment]
是因为你在主题配置中使用了支持连字的字体，换个字体就可以了

**Comment by cmwode** [comment]
> 是因为你在主题配置中使用了支持连字的字体，换个字体就可以了

好的 谢谢
