### ISSUE TITLE
2021年，页脚的copyright没有自动更新

### ISSUE THREAD

**Issue by HeroadZ** [reuixiy/hugo-theme-meme#292]
是静态写死的吗？我这边本地hugo重新push一下才是2021。

**Comment by reuixiy** [comment]
不是 hard-coded 的

https://github.com/reuixiy/hugo-theme-meme/blob/28bcb78fd9f396204930ae288e0581f00fa42705/layouts/partials/footer.html#L12

有两种可能：

1. 服务器或浏览器缓存
2. 时区，如果使用了 CI 服务，运行的服务器默认时区可能是 UTC，所以时间要比我们 UTC+8 晚 8 个小时
