### ISSUE TITLE
Hide Flex on Scroll

### ISSUE THREAD

**Issue by colorizer** [reuixiy/hugo-theme-meme#293]
Hi,

Is there a way to hide the flex header on scroll?

Thanks!

**Comment by reuixiy** [comment]
Not supported yet. But we can implement it though.

**Comment by reuixiy** [comment]
Just implemented it.

Please update MemE to the latest version and update your `config.toml` and
set `enableHeaderAutoHide` to `true` to verify this feature.

**Comment by colorizer** [comment]
It works perfectly. Thanks!👍
