### ISSUE TITLE
关于博客中插入图片的小问题

### ISSUE THREAD

**Issue by Xuezenghuigithub** [reuixiy/hugo-theme-meme#30]
众所周知，在 MemE 中插入图片是极为方便的：`![](url "title")` 但是当我想插入的图片较小时是不能使用这个方式的，因为没办法设置图片的宽度，所以我的方式是直接在 Markdown 中使用`<img src="" width="">`来调整图片，但是又想添加图片的说明文字，不知道有什么好的办法吗？

**Comment by Xuezenghuigithub** [comment]
之前在`<img />`下使用`<center>◎title</center>`的方式很憨🌚强迫症患者 哎

**Comment by reuixiy** [comment]
<img src="" width="" ... title="">
