### ISSUE TITLE
有没有博文置顶功能？

### ISSUE THREAD

**Issue by Acytoo** [reuixiy/hugo-theme-meme#302]
<b>
在 LIFE 与 2021 之间添加可以设置为“置顶”的文章
</b>

&nbsp;

![image](https://user-images.githubusercontent.com/18031762/106561729-2bbeed80-6564-11eb-88f9-937bc80c9bc0.png)

**Comment by reuixiy** [comment]
MemE 可能不会支持该特性

但是可以尝试[自己定制](https://github.com/reuixiy/hugo-theme-meme/blob/master/README.zh-cn.md#%E5%AE%9A%E5%88%B6-meme)一下 https://github.com/reuixiy/hugo-theme-meme/blob/master/layouts/_default/list.html
