### ISSUE TITLE
长毛象的链接认证

### ISSUE THREAD

**Issue by Borber** [reuixiy/hugo-theme-meme#303]
您可以 验证自己是个人资料元数据中的某个链接的所有者。 为此，被链接网站必须包含一个到您的 Mastodon 主页的链接。链接中 必须 包括 rel="me" 属性。链接的文本内容可以随意填写。

比如我需要在我的主页上放上这个 a 标签/</ a rel="me" href="https://wxw.moe/@BORBER">Mastodon/<//a/>

Socials.toml 好像就没法满足

**Comment by Candinya** [comment]
路过想到的一种改进方式： `hugo-theme-meme/layouts/partials/components/socials.html` 文件第6行的 `rel="external noopener"` 段，如果用户在设置（`data/Socials.toml`）中指定了rel参数则直接使用`{{ .rel }}`的内容
（我不知道相关的语法，因而只能想到这方案而没法直接给出结果，还请见谅 😃

**Comment by Borber** [comment]
因为用github action编译 所以其实是直接引用的官方仓库，没有clone下来，所以可能还是得等作者适配吧, 或者得fork然后改完pr

**Comment by Borber** [comment]
> 路过想到的一种改进方式： `hugo-theme-meme/layouts/partials/components/socials.html` 文件第6行的 `rel="external noopener"` 段，如果用户在设置（`data/Socials.toml`）中指定了rel参数则直接使用`{{ .rel }}`的内容
> （我不知道相关的语法，因而只能想到这方案而没法直接给出结果，还请见谅

看了一下确实是应该这样解决 超棒

**Comment by reuixiy** [comment]
> 因为用github action编译 所以其实是直接引用的官方仓库，没有clone下来，所以可能还是得等作者适配吧, 或者得fork然后改完pr

将主题目录下的文件复制一份到 Hugo 站点目录下，就会 override 主题的相应文件，就可以实现定制

见 https://github.com/reuixiy/hugo-theme-meme/blob/master/README.zh-cn.md#定制-meme

**Comment by Borber** [comment]
[Hugo Meme 主题 添加 Mastodon 认证](https://blog.borber.top/tech/hugo-meme-mastodon/) 时隔两年终于动手了... 顺便输出一篇博客
