### ISSUE TITLE
this feature is not available in your current Hugo version

### ISSUE THREAD

**Issue by yaleax** [reuixiy/hugo-theme-meme#31]
Hugo版本 v0.6.0.1 和 v0.5.9.1 
执行的步骤
1.安装 hugo
2.下载主题
3.移动config.toml文件到网站根目录
4.当我执行`hugo -D`的时候，会出现下面提示。

```bash
Building sites … ERROR 2019/12/05 12:57:06 Transformation failed: TOCSS: failed to transform "styles/main-rendered.scss" (text/x-scss): this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Total in 424 ms
```
访问我的网站地址，主题已经生效，但是缺少了 CSS 样式。
现在不知道如何排错，请求帮助，谢谢。

**Comment by reuixiy** [comment]
见 #10。

**Comment by yaleax** [comment]
简单并完美的解决了问题。下载hugo_extended_0.60.1_Linux-64bit.deb，也就是前面带hugo_extended的版本。
我刚刚还在尝试用 npm安装PostCSS.
谢谢
