### ISSUE TITLE
可不可以选择把目录放到侧边栏 像书签那样 文章一长得从顶上找...

### ISSUE THREAD

**Issue by traumtanzer** [reuixiy/hugo-theme-meme#313]
文章如果比较长，需要手动返回到顶部的目录选择跳转，不是很方便。能不能像电子书的书签那样，放在侧栏，这样阅读的时候就不需要在顶部找书签了，就在当下的那个区域的侧边就能找。（目录短的时候放在顶部没问题，但是文章一长，就比较...） 谢谢。另外顺便同求一下waline(issues里面已经有人提过了) 作者大大辛苦~ 蟹蟹

**Comment by SpringLych** [comment]
+1，希望放到侧边

**Comment by ganttee** [comment]
+2

**Comment by reuixiy** [comment]
移步 #64
