### ISSUE TITLE
windows 安装 meme 主题时失败

### ISSUE THREAD

**Issue by latin-xiao-mao** [reuixiy/hugo-theme-meme#315]
![image](https://user-images.githubusercontent.com/66651472/110234732-170cb580-7f67-11eb-9ca9-dc8dde9279b9.png)

**Comment by he-sb** [comment]
安装扩展版的 hugo，也就是带 extended 后缀的版本。

**Comment by latin-xiao-mao** [comment]
谢谢哦，已解决。
