### ISSUE TITLE
代码区域全部展开

### ISSUE THREAD

**Issue by latin-xiao-mao** [reuixiy/hugo-theme-meme#317]
有人知道怎么设置代码区域竖向不显示滚动条，而是让他全部展开，怎么设置样式嘛？

**Comment by reuixiy** [comment]
将

https://github.com/reuixiy/hugo-theme-meme/blob/ef2cd86dac94c1c46a9cc778dbf87e593941bf19/config-examples/zh-cn/config.toml#L1239-L1240

修改为 `false` 即可

**Comment by latin-xiao-mao** [comment]
好的，谢谢！

**Comment by changxvv** [comment]
你好，我设置了enableOverflowY选项，可是代码并没有完全展开🤣，maxHeight显示为unset，请问还需要注意什么么？

**Comment by changxvv** [comment]
> 你好，我设置了enableOverflowY选项，可是代码并没有完全展开🤣，maxHeight显示为unset，请问还需要注意什么么？

我通过把blog下的resource文件删掉并更新hugo版本将问题解决了，虽然不知道为什么这样就行了😂
