### ISSUE TITLE
诗意人生模式下首页诗句显示错误

### ISSUE THREAD

**Issue by CarlMarx1989** [reuixiy/hugo-theme-meme#319]
非常感谢reuixiy大大这个精美的hugo主题，在使用过程中我遇到了一个问题
在本地 使用 hugo server -D时首页诗句正常显示如下图
![image](https://user-images.githubusercontent.com/73773227/111287861-993f5d00-867e-11eb-9c8d-362afdc78848.png)
而将其部署到Github上时，首页诗句显示错误：即只有PAGE四个字
![image](https://user-images.githubusercontent.com/73773227/111287996-bd02a300-867e-11eb-96ae-16532b76b331.png)

**Comment by reuixiy** [comment]
是通过 `cd public` 部署到 GitHub Pages 的吗？

尝试 `rm -rf public && hugo` 或 `hugo --gc --minify --cleanDestinationDir`，然后重新上传 public

原因是 `hugo server -D` 预览时页面是在内存中的，而不是在硬盘中的 public 文件夹下，所以要使部署的版本和预览的版本一致，需要清空 public 重新生成，然后部署

**Comment by reuixiy** [comment]
浏览器调试时，可使用 `ctrl + shift + r` 强制刷新网页以排除浏览器缓存对测试的影响

**Comment by CarlMarx1989** [comment]
!!!!!!!!!!!!解决了，感谢大佬
