### ISSUE TITLE
Comments bug report

### ISSUE THREAD

**Issue by huangdiv** [reuixiy/hugo-theme-meme#32]
@reuixiy :

Style of "load comments" button is not included in main.scss when specialy setting `comments: true` in a single post. Thus it looks like this in my About page:
![IMG_20191211_232453](https://user-images.githubusercontent.com/55480312/70635703-fd60af00-1bf9-11ea-919d-7fdfb507702e.jpg)

**Comment by reuixiy** [comment]
Hi @huangdiv,

I’m afraid this is not a bug.

I know I stated in `config.toml`:

> ```toml
> enableComments = false
> # Note: *global settings*
> #       `comments` in post’s Front Matter
> #       has a higher priority than here
> ```

But I also explained in README as following:

> comments | set `false` to disable comments in mainSections or set `true` to enable comments in non-mainSections

So here is the *principle* / *logic* of design of MemE:

1. Enable `enableComments` if you need comments;
2. Set `comments` to `false` in that post’s Front Matter if you don't need comments in that post.

In your case, all you have to do is twist your logic — set `enableComments = true` globally; set `comments: false`(LIFE section) or `comments: true`(about section) locally...

**Comment by huangdiv** [comment]
Ok I see, thanks a lot. I have another issue for my blog,
I have set mainSections and Home as this:

>     mainSections = ["life", "tech"]
and
>     homeLayout = "posts"

When running `hugo server -e production` for local test, the home page shows all posts from the 2 sections `life` and `tech`. 

But when I deploy to Netlify, it changes to only show posts from `tech` section. Why would this happen? I confirm the hugo version is the same v0.60.1.

Thanks for your answer.

**Comment by reuixiy** [comment]
Case sensitive maybe, try `mainSections = ["LIFE", "tech"]`

**Comment by huangdiv** [comment]
> Case sensitive maybe, try `mainSections = ["LIFE", "tech"]`
Yes, u r right. It have been fixed.Thx!
Issue closed.
