### ISSUE TITLE
  what is the difference between the “categoryBy = "sections""and "categoryBy = "categories"？

### ISSUE THREAD

**Issue by fakerpawnno1** [reuixiy/hugo-theme-meme#33]

**Comment by fakerpawnno1** [comment]
我直接用中文吧，不是很懂categoryBy sections和categories的实际效果有什么异同？by ssections是指在利用文件目录结构吗？而categories是指利用front matter吗？为什么我使用by sections用了nested sections 无法显示目录结构。如foo/bar/直接用中文吧，不是很懂categoryBy sections和categories的实际效果有什么异同？by ssections是指在利用文件目录结构吗？而categories是指利用front matter吗？为什么我使用by sections，而且用了nested sections 无法显示目录结构只能显示顶层的sections？

**Comment by reuixiy** [comment]
子文件夹必须包含 `_index.md`，Hugo 才会认为它是一个分区

https://gohugo.io/content-management/sections/#nested-sections

**Comment by fakerpawnno1** [comment]
我是这样做的啊

**Comment by reuixiy** [comment]
那奇怪了啊

**Comment by fakerpawnno1** [comment]
你可以给个例子吗？感觉我可能理解出错了。我主要感觉categories页面显示不太对，你说的bysection是指会在categories页面的显示与实际的文件目录结构一样，还是说要利用front matter中的categories来定义。显示的是也是你front matter定义的结构？

**Comment by reuixiy** [comment]
> 你说的bysection是指会在categories页面的显示与实际的文件目录结构一样

对，`categoryBy = "sections"` 的话，Front Matter 中的 `categories` 就没用了。

不知你有没有按「[注意](https://github.com/reuixiy/hugo-theme-meme/blob/56578acf35b02f57690f4aad92c9c3be97596437/config-examples/zh-cn/config.toml#L321-L325)」中的说明，将 taxonomies 中的 [categories](https://github.com/reuixiy/hugo-theme-meme/blob/56578acf35b02f57690f4aad92c9c3be97596437/config-examples/zh-cn/config.toml#L60) 删除或注释？

例子可见[我的博客](https://github.com/reuixiy/io-oi.me/blob/master/config.toml)或[这个](https://github.com/guanqr/blog/blob/master/config.toml)。

**Comment by fakerpawnno1** [comment]
我注释了之后会出现`categories`页面 404  。没有注释的话用`categoryBy = "sections"`并且在`front matter`中定义了·categories`的话，`categories`页面不会404，但感觉他的结构有些奇怪。

**Comment by reuixiy** [comment]
对了！注释后，你需要手动创建个 `content/categories/_index.md` 文件，不然不会有这个页面。

P.S. 这个我忘了说明

**Comment by fakerpawnno1** [comment]
thank you
