### ISSUE TITLE
homeLayout = "footage" no video

### ISSUE THREAD

**Issue by martinlindelof** [reuixiy/hugo-theme-meme#330]
Trying the footage layout and getting a vid.mp4 playing in fullscreen as background.
Where is the vid.mp4 supposed to be if not in content/vid.mp4

**Comment by reuixiy** [comment]
`static/videos/vid.mp4`

https://github.com/reuixiy/hugo-theme-meme/blob/97cb67e954e87b7a6dca145fd8b4d7430f2a39f7/config-examples/en/config.toml#L1375

then set `fofVideoMp4` to `/videos/vid.mp4`.

Also, it is recommended to provide a poster (first frame of your video maybe) and the webm alternative (file size is smaller) for the video.

**Comment by martinlindelof** [comment]
Thank you!
Is there a way to disable the overlay (with avatar, title, motto, description) over the video?
Can't find in the config.toml but I think it would be nice to have a boolean flag to set the overlay to false (hidden)
