### ISSUE TITLE
Menu icons cut off on mobile/narrow screen toggle mode

### ISSUE THREAD

**Issue by mike-shine** [reuixiy/hugo-theme-meme#331]
First of all, love the meme theme and all the details provided in the config.toml! It's made life much easier for me.

I'm running into an issue where some of my menu bar icons are cut off when viewing my website on mobile (specifically portrait orientation, landscape is fine). In my config.toml, my "enableNavToggle" is set to "true". I have four icons in total on my menu bar, and two are cut off with this issue. Screenshots: 

Menu bar on my small laptop (looks okay)

![laptop menu bar](https://user-images.githubusercontent.com/72827809/117853116-e255fc80-b23c-11eb-852c-d09c324402ae.jpg)

Menu bar on my iPhone, landscape orientation (also okay)

![menu bar mobile landscape](https://user-images.githubusercontent.com/72827809/117853229-0580ac00-b23d-11eb-9cce-5778bd7153ef.PNG)

Menu bar on my iPhone, portrait mode (the problem)

![menu bar mobile portrait](https://user-images.githubusercontent.com/72827809/117853292-16c9b880-b23d-11eb-93a6-11d248bb9555.jpg)

Is it a responsiveness issue? I looked through _responsive.scss to see if I could identify some style code to change, but everything looked good.

Thanks for the help!

**Comment by reuixiy** [comment]
Have you modified or added custom CSS styles?

![Screenshot from 2021-05-12 10-30-20](https://user-images.githubusercontent.com/28993043/117909610-1f89bf80-b30d-11eb-8887-06e7b67e2855.png)

The first `.header-inner` section is expected to not appear.

**Comment by mike-shine** [comment]
It must be something to do with my custom CSS, yes. I thought I was only fiddling with the opacity and position of the icons, but after I commented out all of my custom CSS it works properly... Can't believe I didn't try that earlier, thanks for your time identifying my bonehead mistake!
