### ISSUE TITLE
[question] 请问如何修改标题文字

### ISSUE THREAD

**Issue by kands-code** [reuixiy/hugo-theme-meme#336]
很抱歉再次打扰，但我想知道如何才能修改标题的文字，我没能找到对应的修改位置

![图片](https://user-images.githubusercontent.com/59006329/120881108-564bb080-c601-11eb-9d9e-8faf68bf9446.png)

我设置了菜单栏的文字，但是对应页面的标题却没有变化

**Comment by reuixiy** [comment]
新建一个 `content/post/_index.md` 文件，里面加上 Front matter，比如

```yaml
---
title: 文章
---
```

即可

**Comment by kands-code** [comment]
唔，我指的不是文章的标题，而是`tags`和`categories`这样的专题页面（不知道这样说对不对）
比如，我的分类页面，在菜单栏的文字被改成了`万华镜`，而点进去后，显示的页面题目还是`Categories`，而不是`万华镜`
![图片](https://user-images.githubusercontent.com/59006329/120882827-aaa85d80-c60c-11eb-819d-b422ae0302ee.png)

请问可以通过创建`content/categories.md'来设置`title`改变吗？或者，正确的设置方式是什么呢？

**Comment by kands-code** [comment]
已经解决了，谢谢您的细心回答
