### ISSUE TITLE
Change unvisited hyperlink colour in single page

### ISSUE THREAD

**Issue by acheronte** [reuixiy/hugo-theme-meme#337]
First of all, fantastic theme! And great documentation too.

But I have stumbled on the following issue, as per the title: I need to change the colour of unvisited hyperlinks in a single page.

What I did is create a ```_custom.scss``` which changed the colour of the anchor links, but it changed it for the entire site (including home page with the list of posts, and categories page, etc.).

At the moment hyperlinks are barely visible (the underline is noticeable but not immediately), unless when hovering.

In essence, I would like to have the same colour you get while hovering, but as default state and only in a single blog entry.

If this has already been addressed, feel free to close.

**Comment by reuixiy** [comment]
Hi @acheronte,

Just refer to the following code:

https://github.com/reuixiy/hugo-theme-meme/blob/159652eafbd79a1956174be36989354686f08654/assets/scss/layout/_single.scss#L22-L31

Hope this helps.

**Comment by acheronte** [comment]
I just tried that and it worked like a charm. Thanks!
