### ISSUE TITLE
Manifest 中的 icon 无法显示，浏览器右上角也不现实加号

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#339]
reuixiy 您好，我遇到了如题所述的问题：

**截图：**
![image](https://user-images.githubusercontent.com/46470508/123571316-8b13e780-d7fc-11eb-92f2-e227ef10aead.png)

对于PWA所需的图标和文件我都已经放在了正确的地方，不知道是哪里出问题了。

博客地址：https://dawner.top/

**Comment by reuixiy** [comment]
你的 static/manifest.json 中的 `src` 不对，应该是

https://github.com/reuixiy/hugo-theme-meme/blob/159652eafbd79a1956174be36989354686f08654/static/manifest.json#L6

**Comment by dawnow** [comment]
> 你的 static/manifest.json 中的 `src` 不对，应该是
> 
> https://github.com/reuixiy/hugo-theme-meme/blob/159652eafbd79a1956174be36989354686f08654/static/manifest.json#L6

**Comment by dawnow** [comment]
是我的问题，草率了，`src`填错了，刚才自己检查的时候也发现了，现在已解决，感谢 reuixiy！👋
