### ISSUE TITLE
Mathjax support

### ISSUE THREAD

**Issue by Scottdyt** [reuixiy/hugo-theme-meme#34]
Thanks for the clean and elegent theme, I really love it.

I am planning to transfer from hexo to hugo, and my blog contains many LaTex equations. It is really annoy to add `\` for every equations, and the LaTex cannot display correctly with extra `\` mark in my local editor Typora, too. 

In Mathjax, only add `<div><\div>` to the equation without modify the origin codes, and the equations can display correctly. I have tested it in this theme, it works.  However, in KATEX engine, it does not work. 

So I am wondering whether add the Mathjax support in this theme, or there are other options?

Thanks & best regrads,

Scott

**Comment by reuixiy** [comment]
Hi @Scottdyt,

I just submitted a commit to support MathJax, and it’s brand new version 3.0 of MathJax!

Please update MemE to the *latest* version and refer to [this commit](https://github.com/reuixiy/hugo-theme-meme/commit/8746889cbc92b35922bab31b01dca7e7275c3d87) to modify your `config.toml` file.

Try it out!

**Comment by Scottdyt** [comment]
You save my day! thanks a lot!
