### ISSUE TITLE
`$currentPage.IsMenuCurrent` seems not working anymore

### ISSUE THREAD

**Issue by reuixiy** [reuixiy/hugo-theme-meme#343]
https://github.com/reuixiy/hugo-theme-meme/blob/0e679a3d0b1b399b9e8e154826cbaf4c553bf6b6/layouts/partials/menu.html#L39

**Comment by palant** [comment]
I found out that this is https://github.com/gohugoio/hugo/issues/9150, a behavior that was introduced in Hugo 0.86. Turns out, the issue here is configuration. Using `pageref` instead of `url` in menu configuration makes things work correctly again.

**Comment by reuixiy** [comment]
So that's the reason!
