### ISSUE TITLE
宽度设置，没有起作用

### ISSUE THREAD

**Issue by ooknn** [reuixiy/hugo-theme-meme#347]
Google Chrome Version 92.0.4515.131 (Official Build) (64-bit)

hugo v0.87.0 linux/amd64 BuildDate=2021-08-03T13:10:04Z

config 中的设置

 listWidth = 72
 postWidth = 72

**Comment by reuixiy** [comment]
本地 `hugo server` 也不起作用吗？还是只是部署后

**Comment by ooknn** [comment]
本地 hugo server 命令，刷新浏览器缓存，更换浏览器都没有效果

**Comment by ooknn** [comment]
换了一台电脑可以，应该是哪里有缓存
