### ISSUE TITLE
mainSections option up to 2

### ISSUE THREAD

**Issue by Scottdyt** [reuixiy/hugo-theme-meme#35]
hi @reuixiy , thanks for your powerful theme!

I found that in the `config.toml`, `mainSections` can only add up to 2, for example, I have 2 sections like:

```
mainSections = ["reading","coding",]
```

which works fine. However, 3 sections falled into 1 section in the web.

```
mainSections = ["reading","coding","math"]
```

There are lots of space in the footer, so I think more sections could fit well.

**Comment by reuixiy** [comment]
Hi @Scottdyt,

I cannot reproduce this bug. Can you show me a screenshot?

**Comment by Scottdyt** [comment]
After I add `_index.md` file to the section, everthing goes well.

However, I found that in my blog, even I have set 

```
mainSections = ["reading","coding","math","cs"]
```

the web can only display the active section:

<img width="741" alt="Screen Shot 2019-12-15 at 10 02 07 AM" src="https://user-images.githubusercontent.com/33884966/70857029-71fd5b80-1f22-11ea-9085-e24e219d5958.png">

In my content file, there are those sections indeed:

<img width="423" alt="Screen Shot 2019-12-15 at 10 06 22 AM" src="https://user-images.githubusercontent.com/33884966/70857045-c86a9a00-1f22-11ea-8efd-711ded176f73.png">


and I want to display my main section like `reading | coding | math | cs`, is there any thing I miss?

**Comment by reuixiy** [comment]
Actually, this is expected behavior... A structure like `reading | coding | math | cs` will only be applied when there are only 2 sections...

Anyway, I will try to add a feature to support this :)

**Comment by Scottdyt** [comment]
Thanks for your reply, wait and see :)
Hope you have a good week~

**Comment by reuixiy** [comment]
Hi @Scottdyt,

I just submitted a commit to support that :)

Please [update](https://github.com/reuixiy/hugo-theme-meme#install-meme) MemE to the *latest* version and refer to this [commit](https://github.com/reuixiy/hugo-theme-meme/commit/12a326b41ead8371fb8bc7aa96f532fad4137820) to modify your config.toml file.

Also, set the new `enableVerticalBarStructure` to `true`.

Try it out!

**Comment by Scottdyt** [comment]
Hi @reuixiy , thanks for adding this option, it works!
