### ISSUE TITLE
更换主题至meme后出现以下错误

### ISSUE THREAD

**Issue by Lntanx** [reuixiy/hugo-theme-meme#355]
![image](https://user-images.githubusercontent.com/94236658/142128304-2b8e5bdf-c0e1-4b5b-b3f6-6d0c797628c0.png)
目前仅修改了config.toml，主题安装方式是直接将文件夹放入themes下，请问应如何解决。

**Comment by reuixiy** [comment]
贴一下你的 Hello World.md

**Comment by Lntanx** [comment]
+++
title: "今天又在摸鱼"
date: 2021-11-15T10:20:38+08:00
draft: false
enabletoc: true
tags:
  - tags
categories:
  - 笔记
+++
## 今天干了点什么呢？

以上。
实际上about/_index.md也报错了，总共就这两个文章XDD

+++
title: "About"
date: 2021-11-15T10:59:53+08:00
draft: false
+++

# about me
blablabla

**Comment by Lntanx** [comment]
运行`hugo new posts/test.md`并删除Hello world.md以及_index.md之后本地渲染成功。请问是编码问题吗？

**Comment by reuixiy** [comment]
`U+003D` 是 `=` 号

这是你的 Front Matter 的语法问题，如果你要使用 TOML，请将 `:` 替换为 `=`

或者使用 YAML 格式，将 `+++` 替换为 `---`

**Comment by Lntanx** [comment]
非常感谢！
