### ISSUE TITLE
请问底部的留白应该怎么控制

### ISSUE THREAD

**Issue by cloud-mist** [reuixiy/hugo-theme-meme#357]
![image](https://user-images.githubusercontent.com/49445212/142445811-3ea6f930-3339-47ba-be8b-df121bcffb73.jpeg)

- 感觉下面的留白好多，但是config里没找到，也可能是我错过了。 我看作者大大的网页控制的很好，不知道如何控制

**Comment by reuixiy** [comment]
https://github.com/reuixiy/io-oi.me/blob/2b5d88e336a6448afed2d9f13d108f8a40c75bea/assets/scss/custom/_custom.scss#L1-L3

**Comment by cloud-mist** [comment]
> https://github.com/reuixiy/io-oi.me/blob/2b5d88e336a6448afed2d9f13d108f8a40c75bea/assets/scss/custom/_custom.scss#L1-L3

谢谢😊
