### ISSUE TITLE
defaultTheme 預設是 dark 的情況下，切回 light 時，圖片的對比不會變回100%。

### ISSUE THREAD

**Issue by starspiritstorm** [reuixiy/hugo-theme-meme#365]
reuixiy 你好，

我發現了一個問題，
defaultTheme 預設是 dark 的情況下，切回 light 時，圖片的對比不會變回100%。

最後我找到在
https://github.com/reuixiy/hugo-theme-meme/blob/master/assets/scss/themes/_light.scss
這裡面也需要加上 

    img {
        filter: brightness(100%);
    }

![image](https://user-images.githubusercontent.com/24405574/149699718-a5976558-8026-4c9c-8f2f-e78ee1f589fe.png)

才會正常切換，此項修正需要 pull request 還是請你自行更新呢？

**Comment by reuixiy** [comment]
PR welcome!

**Comment by starspiritstorm** [comment]
不好意思剛剛用錯帳號commit了，請用#367的PR。
