### ISSUE TITLE
页脚只显示单个分类

### ISSUE THREAD

**Issue by tengxunkuku** [reuixiy/hugo-theme-meme#373]
我在文章的元数据设置了categories: ["物理", "知乎"]，但是页脚却只显示了单个分类。相关的issue也查过了，但是没有解决，我想像博主一样显示tech|life该怎么做呢？

**Comment by reuixiy** [comment]
`enableVerticalBarStructure = true` 时，主题假设 categories 是有层级的，然后只会取最高层级分类，也就是第一项。

我的博客只有两个分类，就是 tech 和 life，https://github.com/reuixiy/io-oi.me/tree/master/content/zh

此外，我是通过 `categoryBy = "sections"` 来组织文章的（也就是依文件夹结构），而不是 Front Matter 中的 `categories`。

**Comment by tengxunkuku** [comment]
在设置enableVerticalBarStructure = false后并列分类了，thanks。
