### ISSUE TITLE
请求支持畅言评论系统

### ISSUE THREAD

**Issue by lengyefenghan** [reuixiy/hugo-theme-meme#390]
感谢作者大大百忙之中点开看了一看
应该是少有的大陆云评论系统，方便管理啥的，搭建也方便，就是不太会折腾meme的主题,所以没有修改主题，只在一个文章底部直接贴了代码 [演示地址](https://lengyefenghan.top/blogs/2022-05-31/) [畅言云评官网](changyan.kuaizhan.com)
如果可以的话希望能够加上

**Comment by lengyefenghan** [comment]
已经放弃改为使用giscus

**Comment by lengyefenghan** [comment]
已经放弃改为使用giscus

**Comment by cynicalight** [comment]
现在和评论还能用吗，尝试添加 gitalk 和 valine 均失败
