### ISSUE TITLE
medium-zoom not work

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#392]
config 中已经打开，但是网站的图片无法进行放大。

网站：https://dawner.top/

config：https://github.com/dawnow/blog/blob/master/config.toml

**Comment by reuixiy** [comment]
需要额外将相应的 js 文件下载放到你的 static/js/ 目录下

**Comment by reuixiy** [comment]
参考 https://github.com/reuixiy/io-oi.me/tree/master/static/js

**Comment by dawnow** [comment]
> 参考 https://github.com/reuixiy/io-oi.me/tree/master/static/js

感谢 reuixiy，已解决！
