### ISSUE TITLE
希望能在config中开启不算子或者其他方式统计文章访问量统计

### ISSUE THREAD

**Issue by he-sb** [reuixiy/hugo-theme-meme#40]
大大好，本人目前在使用您开发的MemE主题，极简的风格非常符合我的审美，功能也非常完善，不知能不能增加一个“可在config文件中选择是否统计访问量”的功能呢，目前使用了Google Analytics，但是感觉不太直观，目前看到的不算子比较好看，但是苦于技术太菜不知如何手动集成进博客配置中，打扰之处莫怪 🙈

**Comment by reuixiy** [comment]
@he-sb 你好，

我刚刚提交了一个改动来支持不蒜子，请[更新主题](https://github.com/reuixiy/hugo-theme-meme/blob/master/README.zh-cn.md#安装-meme)到最新版，并参考[这个改动](https://github.com/reuixiy/hugo-theme-meme/commit/09e99769a473410aeeb8e4081f99274fbf81645f)往你的配置文件 config.toml 中添加内容，然后将相应选项设置为 `true` 以开启，即可。

注意：仅在生产环境（production）下渲染，所以要想本地调试，需加上 `--environment production` 参数，比如：`hugo server -D --environment production`。另，首页暂时不支持每一文章的访问量统计。

**Comment by he-sb** [comment]
太感动了，非常感谢！ :rofl:

**Comment by he-sb** [comment]
更新并修改了配置文件了之后，文章浏览量是正常的，但是站点访客数和浏览量是不是不太对。。
有什么办法能修改一下吗 🙈 

![image](https://user-images.githubusercontent.com/26474615/71222790-d6e2f800-230c-11ea-8ee3-8279ac47cd0b.png)

**Comment by reuixiy** [comment]
不蒜子是按 URL 计数的，本地的话肯定不对，部署后不准确就不知道为什么了，你部署后给我看看。

**Comment by he-sb** [comment]
我嚓，未做任何修改重新`git push`了一下正常了。。
打扰了 🙈

**Comment by linwhitehat** [comment]
你好，我按照你的做法配置之后在最新版的meme中出现无法正常显示的情况。请问能否帮忙查看是什么原因？阅读数量只出现一会然后就消失了。
这是我的博客地址：https://linwhitehat.github.io/Hugoblog/
