### ISSUE TITLE
Site brand link in header does not respect baseURL config

### ISSUE THREAD

**Issue by reuixiy** [reuixiy/hugo-theme-meme#407]
### Discussed in https://github.com/reuixiy/hugo-theme-meme/discussions/406

<div type='discussions-op-text'>

<sup>Originally posted by **chtsao** September  9, 2022</sup>
Thanks for creating meme theme. I have used it for years and just love it!

Just few days ago, I created a hugo site and served as a Gitlab page.  
Everything works well except that the title links to my Gitlab io (https://chtsao.gitlab.io/)
rather than the baseURL (https://chtsao.gitlab.io/i2p2022/)

What's wrong? 

Your kind help is deeply appreciated. 

Here is my config.toml (in part)

># Site Settings
>baseURL = "https://chtsao.gitlab.io/i2p2022/"
>title = "Intro to Probability 2022"</div>

**Comment by SleepDevil** [comment]
遇到这个问题了，请问预计啥时候修复

**Comment by SleepDevil** [comment]
提了个pr，看看可以吗
https://github.com/reuixiy/hugo-theme-meme/pull/408
