### ISSUE TITLE
关于诗意人生

### ISSUE THREAD

**Issue by Wjiajie** [reuixiy/hugo-theme-meme#41]
大大你好，诗意人生在配置文件里的markdown格式是怎样的呢？
就是这个：
homePoetry = []

不知道怎么配置（原谅我）

**Comment by reuixiy** [comment]
```
homePoetry = ["诗句一", "诗句二", "诗句三", "**粗体**"]
```

https://github.com/toml-lang/toml#array

**Comment by Wjiajie** [comment]
太感谢了！还有一个问题...
[[menu.home]]
        url = "/categories/"
        name = "博文结构"
        weight = 2
        pre = "internal"
        post = "th"

里面的参数: post = " th",在哪里可以找到参数和图标的对应关系呢？想自定义图标，但不知道参数怎么该～麻烦你了

**Comment by reuixiy** [comment]
https://io-oi.me/tech/documentation-of-hugo-theme-meme/#图标

**Comment by Wjiajie** [comment]
谢谢，打扰了！
