### ISSUE TITLE
Valine bugs on mobile

### ISSUE THREAD

**Issue by Wjiajie** [reuixiy/hugo-theme-meme#42]
我在加载valine评论的时候，在文章中写的评论，再次刷新文章后评论消失了。但在leancloud后台是有这个评论的。这是我个人配置的问题吗？

**Comment by reuixiy** [comment]
我刚去你站测试了一下，无法复现。

**Comment by Wjiajie** [comment]
@reuixiy 是的，但我看后台数据是存在的，不知道咋回事

**Comment by reuixiy** [comment]
emmm 我的意思是无法复现你说的问题 我刚去你博客评论测试了一下 显示正常

**Comment by Wjiajie** [comment]
> emmm 我的意思是无法复现你说的问题 我刚去你博客评论测试了一下 显示正常

你的评论还在，但我用手机，平板测试时，再次刷新就没有了。
我注意到你的评论显示你的账号头像，但我是相当于游客模式来评论的（没填写称昵，邮箱和网址）。我试了一次把这三个信息都填了的，刷新也不行。

**Comment by reuixiy** [comment]
已复现，待观察

**Comment by reuixiy** [comment]
麻烦你更新一下主题，然后再在移动端测试一下。

如果仍有问题，请将后台相应的那条评论数据截图给我看一下。

**Comment by Wjiajie** [comment]
> 麻烦你更新一下主题，然后再在移动端测试一下。
> 
> 如果仍有问题，请将后台相应的那条评论数据截图给我看一下。

找到问题了，是我个人配置的问题。我在leancloud云引擎配置了一个功能`Valine-Admin`用于管理发送的消息，其中一个参数设为需要人工审核。而这个人工审核是需要申请账号才能生效的（我没注册账号）。用户发送的消息每次都提示人工审核失败。另外在创建leancloud应用时忘了创建`Counter`这个class了...我的锅
