### ISSUE TITLE
Use Markdown Render Hooks for images and links

### ISSUE THREAD

**Issue by reuixiy** [reuixiy/hugo-theme-meme#43]
https://github.com/gohugoio/hugo/releases/tag/v0.62.0

**Comment by reuixiy** [comment]
> Note that this is only supported with the Goldmark renderer.
>
> — *https://gohugo.io/getting-started/configuration-markup/#markdown-render-hooks*

So I will work on this once [this issue](https://github.com/gohugoio/hugo/issues/6616) related to goldmark is resolved.

**Comment by reuixiy** [comment]
https://discourse.gohugo.io/t/simple-image-render-hook-template-for-responsive-images/22464

**Comment by reuixiy** [comment]
Annoying goldmark problems：

1. Linkify extension
    1. https://example.com/中文 -> `<a href="https://example.com/">https://example.com/</a>中文`
    2. 中文：https://www.google.com -> `中文：https://www.google.com`
2. Typographer extension
    https://github.com/yuin/goldmark/issues/39

**Comment by reuixiy** [comment]
Currently, I have encountered some problems in Hugo Markdown Render Hooks, such as it won't append to the links that handled by auto link. So temporary I won't work on this until Hugo release a more stable version. And close this issue temporarily.

**Comment by dawnow** [comment]
昨天Hugo和Meme都更新到了最新，我也是遇到同样的问题，发现图片链接里面有空格就渲染不了，我还改链接改了一篇，上来一查，果然是hugo的问题，现在用开发者的方法就可以了，感谢！
