### ISSUE TITLE
Build error caused by partials/components/fedishare.html

### ISSUE THREAD

**Issue by reuixiy** [reuixiy/hugo-theme-meme#455]
![Arc 2024-01-20 at 20 55 01@2x](https://github.com/reuixiy/hugo-theme-meme/assets/28993043/67aa33b3-e945-46ea-a11b-0876862e38b0)

Recently, our ci build has been failed, https://github.com/reuixiy/hugo-theme-meme/actions/runs/7594063103/job/20685180759

I debugged but can’t find the reason. Appreciate if you can help @palant!

![Code 2024-01-20 at 20 59 35@2x](https://github.com/reuixiy/hugo-theme-meme/assets/28993043/95f57b57-4d72-4a86-baff-327dc5c73129)

![Arc 2024-01-20 at 21 03 46@2x](https://github.com/reuixiy/hugo-theme-meme/assets/28993043/d4e810ff-8bab-4a60-97f9-c16c90c318e1)

**Comment by palant** [comment]
Ah, right. The server got more strict about the requests it accepts. I fixed that issue on my end but forgot to tell you. Here: https://github.com/palant/palant.info/commit/9f1f1a9334c8d97a030e4184c08687e14e9e4930

**Comment by reuixiy** [comment]
Thanks!
