### ISSUE TITLE
如何修改菜单栏的字体大小？

### ISSUE THREAD

**Issue by Cecilia404404** [reuixiy/hugo-theme-meme#457]
如题，只找到品牌栏可以设置字号，希望右边的菜单栏字体也可以调大。
![image](https://github.com/reuixiy/hugo-theme-meme/assets/152269094/3e3386ad-7b93-4873-966d-3aac3e34e77c)

**Comment by HushWay** [comment]
你可以新建`assets/scss/custom/_custom.scss`自定义样式：
```
.nav {
    font-size: 1.5em;
    margin-top: 0em;
}
```
> 参考：https://github.com/reuixiy/io-oi.me/blob/cacbff5d76ffb4cd946f49d37492bf414c0e34a0/assets/scss/custom/_custom.scss#L19

**Comment by Cecilia404404** [comment]
好的，非常感谢！

**Comment by cynicalight** [comment]
非常感谢！找了很久网上都没有相关资料
