### ISSUE TITLE
Pagination in section pages

### ISSUE THREAD

**Issue by Scottdyt** [reuixiy/hugo-theme-meme#46]
I have many posts in one section, can I set the number of posts per page?

**Comment by reuixiy** [comment]
It looks like a reasonable request, but I'm afraid I won't add pagination for list page...

See https://yihui.org/cn/2018/08/pagination/

**Comment by he-sb** [comment]
> It looks like a reasonable request, but I'm afraid I won't add pagination for list page...
> 
> See https://yihui.org/cn/2018/08/pagination/

Nice work, so that we can simply press Ctrl + F at the posts page to search the title of articles, even without thinking of the searching function of the theme. It's efficient enough for me.

**Comment by Scottdyt** [comment]
@reuixiy  I got your point, but I still think the section page would be clean and uniform with paginations, especially when you visit the website using mobile phone, which is annoying to scroll up and down for a long page.
But that's OK, I will customize it myself. Thanks~

**Comment by reuixiy** [comment]
@Scottdyt,

> I will customize it myself

Yep! And feel free to ask me if you encounter any problems.
