### ISSUE TITLE
能否自定义归档界面的标题?

### ISSUE THREAD

**Issue by Cecilia404404** [reuixiy/hugo-theme-meme#461]
![屏幕截图 2024-05-15 204437](https://github.com/reuixiy/hugo-theme-meme/assets/152269094/8ada1d2d-9043-430e-8f20-d2bb3d4e021e)
如图，能否通过代码实现把图中的“Posts”自定义为其他文字？使得我点进归档界面时最上方标题不是“Posts”而是自己想要的文字？谢谢！

**Comment by zhengxyz123** [comment]
这是一个查询Hugo文档即可解决的问题，不过我还是将解决方法详细地陈述一下。

在博客的`content/`的任意子目录下（这里是`posts`子目录）新建一个`_index.md`文件。

`content/posts/_index.md`文件内容为：
```markdown
---
title: "我想要的文字"
---
```

如此，就能达到阁下想要的效果。

**Comment by Cecilia404404** [comment]
懂了！非常感谢！
