### ISSUE TITLE
Latex公式渲染有问题

### ISSUE THREAD

**Issue by stmoonar** [reuixiy/hugo-theme-meme#462]
**这是我的markdown源码，在typora中渲染是没问题的，而且我把等式两边分开渲染都没问题，但是作为一行就是不能正常渲染了，**
![image](https://github.com/user-attachments/assets/b3b142dc-1399-44f3-a631-6919091f5fda)
**这是渲染后的效果，下面那行显示的latex原文而不是渲染后的公式。**
![image](https://github.com/user-attachments/assets/9b3dfcc9-8f5d-48c1-b7a4-ce30f4bf1fbb)
**有没有哪位大佬知道这是为什么，感谢！！！**

**Comment by reuixiy** [comment]
見 https://io-oi.me/tech/documentation-of-hugo-theme-meme/#katexmathjaxmermaid

**Comment by stmoonar** [comment]
> 見 https://io-oi.me/tech/documentation-of-hugo-theme-meme/#katexmathjaxmermaid

感谢
