### ISSUE TITLE
"Error building site"; format or syntax issue with list-item.html

### ISSUE THREAD

**Issue by johnalexhebert** [reuixiy/hugo-theme-meme#47]
Apologies if this is too verbose. I'm new to hugo and hugo themes and couldn't figure out how to fix the error.

I just upgraded to the extended version of Hugo:
`johnalexhebert@penguin:~/projects/hugo/test1$ hugo version`
`Hugo Static Site Generator v0.62.1-A1518704/extended linux/amd64 BuildDate: 2020-01-01T17:45:13Z`

Here is the error:
`johnalexhebert@penguin:~/projects/hugo/test1$ hugo server -D`
`Building sites … ERROR 2020/01/01 16:24:01 Transformation failed: SCSS processing failed: file "stdin", line 118, col 27: Invalid CSS after "...und-image: url(": expected expression (e.g. 1px, bold), was "<no value>);"
Built in 168 ms
Error: Error building site: failed to render pages: render of "section" failed: execute of template failed: template: _default/list.html:89:35: executing "main" at <partial "components/list-item.html" .>: error calling partial: "/home/johnalexhebert/projects/hugo/test1/themes/meme/layouts/partials/components/list-item.html:4:149": execute of template failed: template: partials/components/list-item.html:4:149: executing "partials/components/list-item.html" at <.Site.Params.listDateFormat>: invalid value; expected string`

`johnalexhebert@penguin:~/projects/hugo/test1/themes/meme/layouts/partials/components$ cat list-item.html`
`{{ range .Pages }}
    <li class="list-item">
        <a href="{{ .RelPermalink }}" class="list-item-title">{{ .LinkTitle }}</a>
        {{ printf `<time datetime="%s" class="list-item-time">%s</time>` (.PublishDate.Format "2006-01-02T15:04:05-07:00") (.PublishDate.Format .Site.Params.listDateFormat) | safeHTML }}
    </li>
{{ end }}`

**Comment by reuixiy** [comment]
Hi @johnalexhebert,

Did you forget [the first step](https://github.com/reuixiy/hugo-theme-meme/blob/master/README.md#blogging)? Try

```sh
~/blog $ rm config.toml && cp themes/meme/config-examples/en-us/config.toml config.toml
```

**Comment by johnalexhebert** [comment]
That was it. Thanks!
