### ISSUE TITLE
site brand SVG generate

### ISSUE THREAD

**Issue by Scottdyt** [reuixiy/hugo-theme-meme#48]
Hi @reuixiy , I want to generate my own brand SVG, and I found this [tool](https://danmarshall.github.io/google-font-to-svg-path/) to convert Google font to svg, which is great.

But I do not know how to generate multi-line text, like in your [web](https://io-oi.me/)(a web name and a slongan), could you kindly tell me is there any tool that can do this?

Thanks a lot!

**Comment by reuixiy** [comment]
FYI, I use [Inkscape](https://inkscape.org) to design the site brand.

**Comment by Scottdyt** [comment]
many thanks!
