### ISSUE TITLE
使用Hugo new posts新建文章。

### ISSUE THREAD

**Issue by wangxiaoerYah** [reuixiy/hugo-theme-meme#53]
使用hugo new posts新建文章。

archetype/default.md目录下的配置没有生效。

**Comment by reuixiy** [comment]
把具体信息贴一下，输入的命令，输出的结果。

小二 <notifications@github.com> 于 2020年1月12日周日 17:42写道：

**Comment by wangxiaoerYah** [comment]
archetype/default.md
```
---
title: "{{ replace .Name "-" " " | title }}"
date: {{ .Date }}
categories: [""]
tags: [""]
slug: ""
draft: true
---

```

`hugo new posts/hello`

```
---
title: "Hello"
date: 2020-01-12T10:18:04Z
draft: true
---
```
OK!My mistake，A false alarm 。
Correct command : `hugo new posts/hello.md`

多谢回复，谢谢<sup>❤❤❤</sup>!!!
