### ISSUE TITLE
在config.toml里 displayTOCTitle 设置为了true 但是并没有显示标题

### ISSUE THREAD

**Issue by reuixiy** [reuixiy/hugo-theme-meme#57]
我的：
![image](https://user-images.githubusercontent.com/16211800/73139111-8a29d400-40a5-11ea-86f5-52e57552e0f1.png)
希望的：
![image](https://user-images.githubusercontent.com/16211800/73139123-a75ea280-40a5-11ea-8c3b-360c251231d0.png)

**Comment by reuixiy** [comment]
@CurtainTears

请将 `hugo version` 命令的输出和 config.toml 中的 [`[markup]`](https://github.com/reuixiy/hugo-theme-meme/blob/af1de8b458cb7c41b4216bee9cd75393a0046e3d/config-examples/zh-cn/config.toml#L61-L90) 部分贴出来。

**Comment by CurtainTears** [comment]
markup的问题，已修改

**Comment by reuixiy** [comment]
OK
