### ISSUE TITLE
诗意人生，诗太长，页面会有兼容问题

### ISSUE THREAD

**Issue by HeroadZ** [reuixiy/hugo-theme-meme#59]
如题，诗太长的话，诗部分的元素不会撑开，应该是设定了固定高度。但是对于小屏手机不友好。
![image](https://user-images.githubusercontent.com/17962682/73595478-893cea80-455c-11ea-93be-e0a7ca7bb1f0.png)

**Comment by reuixiy** [comment]
@HeroadZ 已修复，请更新主题测试。

**Comment by HeroadZ** [comment]
您好，经过测试依然有问题。我看您在scss里面只是加了一点em，似乎在比较极端的情况下还是有问题。

**Comment by reuixiy** [comment]
请问你用的什么浏览器，我在最新版的 Chrome 浏览器中测试没问题，如下（注意滚动条的出现）：

![Peek 2020-02-02 11-47](https://user-images.githubusercontent.com/28993043/73602619-18282200-45b2-11ea-8e57-f3ba1babe423.gif)

**Comment by HeroadZ** [comment]
我也是用的chrome浏览器，诗的行数大概在10行左右。
现在的问题是，如果页面宽度很窄的情况下，有几行诗比较长，会自动换行，会往下走。同时，我在每个icon边上，添加了中文，比如“生活”“技术”“关于”这些。如果宽度很窄的话，这些符号也不能排列成一行，会往上跳。
以上这两种情况，会导致重叠。您可以尝试缩小页面宽度试试。

**Comment by reuixiy** [comment]
我还测试了一种极端情况，的确会有些问题：

![Peek 2020-02-02 11-53](https://user-images.githubusercontent.com/28993043/73602663-bc11cd80-45b2-11ea-8f3d-738ad9cc59eb.gif)

发现的确会有些问题，但这样的诗放首页实在太长了……我设计这个布局的初衷只是

> ```
> 1. poetry    A few lines of verse
> ```
>
> https://github.com/reuixiy/hugo-theme-meme/blob/master/config-examples/en-us/config.toml#L279

……Anyway，基于你的需求，建议自己[定制](https://io-oi.me/tech/documentation-of-hugo-theme-meme/#定制)一下样式。

当然，如果你在技术上有更好的通用的解决方案，还是非常欢迎提交 PR 的。

**Comment by HeroadZ** [comment]
好的好的，非常感谢，我去设置一下样化。

**Comment by reuixiy** [comment]
嗯，同时也谢谢你的反馈:smiley_cat:～
