### ISSUE TITLE
一个小问题：

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#60]
开发者你好，我注意到你[这篇文章](https://io-oi.me/tech/documentation-of-hugo-theme-meme/)的目录列表上面是有【目录】两个字的，但是我开启TOC后目录列表会自动置于文章顶部，且没有和下面标题同样大小的【目录】二字，只显示H2到H6的文字，如果想实现该怎么操作呢？其实我并没有这个功能的迫切需求，只是偶尔尝试发现了这个问题，也不知道我表述清楚没有，还请您解答我的疑惑。感谢！
![image](https://user-images.githubusercontent.com/46470508/73922277-d544b200-4903-11ea-9a48-8e01d1a8913c.png)

**Comment by reuixiy** [comment]
可能是你的主题不是最新版的原因吧，不知你是否是通过 README 中推荐的[更新方法](https://github.com/reuixiy/hugo-theme-meme/blob/master/README.zh-cn.md#%E5%AE%89%E8%A3%85-meme)更新主题的呢？

对于更新主题，推荐的更新流程如下：

1. 更新主题，`git submodule update --rebase --remote`
2. 更新配置，查看配置文件 config.toml 的[改动历史](https://github.com/reuixiy/hugo-theme-meme/commits/master/config-examples/zh-cn/config.toml)，并将相应修改同步到你的该文件中

如果你发现用第一条命令无法更新了，可以参见 #29 更新主题到最新版，然后复制一份最新版的示例配置，最后再花点时间重新配置一遍。

**Comment by dawnow** [comment]
> 可能是你的主题不是最新版的原因吧，不知你是否是通过 README 中推荐的[更新方法](https://github.com/reuixiy/hugo-theme-meme/blob/master/README.zh-cn.md#%E5%AE%89%E8%A3%85-meme)更新主题的呢？
> 
> 对于更新主题，推荐的更新流程如下：
> 
> 1. 更新主题，`git submodule update --rebase --remote`
> 2. 更新配置，查看配置文件 config.toml 的[改动历史](https://github.com/reuixiy/hugo-theme-meme/commits/master/config-examples/zh-cn/config.toml)，并将相应修改同步到你的该文件中
> 
> 如果你发现用第一条命令无法更新了，可以参见 #29 更新主题到最新版，然后复制一份最新版的示例配置，最后再花点时间重新配置一遍。

好的，我再按照那个问题里的方法配置一下，可能是我修改主题文件里的文件了。谢谢！
