### ISSUE TITLE
更换了品牌栏SVG后出现了以下错误：

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#65]
`$ hugo server -D
Building sites … ERROR 2020/02/14 15:17:47 failed to load data: failed to load data: "D:\Hugo\blog\data\SVG.toml:1:1": unmarshal failed: Near line 1 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got 'T' instead
`
之前更换都是正常的，请大佬解答。
感谢！😭

**Comment by reuixiy** [comment]
麻烦贴一下或截图相关代码

**Comment by dawnow** [comment]
> 麻烦贴一下或截图相关代码

这是git返回的相关代码：
![](https://dawnblog-1300625500.cos.ap-guangzhou.myqcloud.com/images/20200214154017.jpg)

**Comment by dawnow** [comment]
> 麻烦贴一下或截图相关代码

`$ hugo server -D
Building sites … ERROR 2020/02/14 15:26:08 failed to load data: failed to load data: "D:\Hugo\blog\data\SVG.toml:1:1": unmarshal failed: Near line 1 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got 'T' instead
ERROR 2020/02/14 15:26:08 failed to load data: failed to load data: "D:\Hugo\blog\data\SVG.toml:1:1": unmarshal failed: Near line 1 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got 'T' instead
ERROR 2020/02/14 15:26:08 failed to load data: failed to load data: "D:\Hugo\blog\data\SVG.toml:1:1": unmarshal failed: Near line 1 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got 'T' instead
ERROR 2020/02/14 15:26:08 failed to load data: failed to load data: "D:\Hugo\blog\data\SVG.toml:1:1": unmarshal failed: Near line 1 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got 'T' instead
ERROR 2020/02/14 15:26:08 render of "taxonomyTerm" failed: execute of template failed: template: taxonomy/category.terms.html:11:15: executing "taxonomy/category.terms.html" at <partial "back-to-top.html" .>: error calling partial: "D:\Hugo\blog\themes\meme\layouts\partials\back-to-top.html:3:23": execute of template failed: template: partials/back-to-top.html:3:23: executing "partials/back-to-top.html" at <index .Site.Data.SVG .Site.Params.backToTopIcon>: error calling index: index of untyped nil
ERROR 2020/02/14 15:26:08 render of "taxonomy" failed: "D:\Hugo\blog\themes\meme\layouts\_default\list.html:52:51": execute of template failed: template: _default/list.html:52:51: executing "main" at <index $.Site.Data.ChineseZodiac (string (mod .Key 12))>: error calling index: index of untyped nil
ERROR 2020/02/14 15:26:08 render of "taxonomy" failed: "D:\Hugo\blog\themes\meme\layouts\_default\list.html:52:51": execute of template failed: template: _default/list.html:52:51: executing "main" at <index $.Site.Data.ChineseZodiac (string (mod .Key 12))>: error calling index: index of untyped nil
ERROR 2020/02/14 15:26:08 render of "home" failed: execute of template failed: template: index.html:8:15: executing "index.html" at <partial "multilingual.html" .>: error calling partial: "D:\Hugo\blog\themes\meme\layouts\partials\multilingual.html:20:115": execute of template failed: template: partials/multilingual.html:20:115: executing "partials/multilingual.html" at <index $.Site.Data.Flags .Lang>: error calling index: index of untyped nil
Built in 540 ms
Error: Error building site: failed to load data: failed to load data: "D:\Hugo\blog\data\SVG.toml:1:1": unmarshal failed: Near line 1 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got 'T' instead
`

**Comment by dawnow** [comment]
![image](https://user-images.githubusercontent.com/46470508/74511474-0b57e680-4f41-11ea-8286-f9173ddb79ad.png)

**Comment by reuixiy** [comment]
不不，我是说 SVG.toml 文件

**Comment by dawnow** [comment]
这是我在这个[网页编辑器](https://svg.wxeditor.com/)里面制作的，下面是date文件夹中svg.toml的所有代码：
`brand = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 100" class="brand"><path fill="none" d="M-1-1h252v102H-1z"/><g><text font-weight="bold" font-family="'Times New Roman', Times, serif" font-size="72" y="65.071" x="3.028" stroke-width="0" stroke="#000">Dawner</text><text font-style="italic" font-weight="bold" font-family="'Times New Roman', Times, serif" font-size="10" y="92.979" x="61.531" stroke-width="0" stroke="#000">Powerful Mind in Strong Body</text></g></svg>'
grin-stars = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512" class="icon"><path d="M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm0 448c-110.3 0-200-89.7-200-200S137.7 56 248 56s200 89.7 200 200-89.7 200-200 200zm105.6-151.4c-25.9 8.3-64.4 13.1-105.6 13.1s-79.6-4.8-105.6-13.1c-9.8-3.1-19.4 5.3-17.7 15.3 7.9 47.2 71.3 80 123.3 80s115.3-32.9 123.3-80c1.6-9.8-7.7-18.4-17.7-15.3zm-227.9-57.5c-1 6.2 5.4 11 11 7.9l31.3-16.3 31.3 16.3c5.6 3.1 12-1.7 11-7.9l-6-34.9 25.4-24.6c4.5-4.5 1.9-12.2-4.3-13.2l-34.9-5-15.5-31.6c-2.9-5.8-11-5.8-13.9 0l-15.5 31.6-34.9 5c-6.2.9-8.9 8.6-4.3 13.2l25.4 24.6-6.1 34.9zm259.7-72.7l-34.9-5-15.5-31.6c-2.9-5.8-11-5.8-13.9 0l-15.5 31.6-34.9 5c-6.2.9-8.9 8.6-4.3 13.2l25.4 24.6-6 34.9c-1 6.2 5.4 11 11 7.9l31.3-16.3 31.3 16.3c5.6 3.1 12-1.7 11-7.9l-6-34.9 25.4-24.6c4.5-4.6 1.8-12.2-4.4-13.2z"/></svg>'
list-alt = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="icon"><path d="M464 32H48C21.49 32 0 53.49 0 80v352c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V80c0-26.51-21.49-48-48-48zm-6 400H54a6 6 0 0 1-6-6V86a6 6 0 0 1 6-6h404a6 6 0 0 1 6 6v340a6 6 0 0 1-6 6zm-42-92v24c0 6.627-5.373 12-12 12H204c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h200c6.627 0 12 5.373 12 12zm0-96v24c0 6.627-5.373 12-12 12H204c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h200c6.627 0 12 5.373 12 12zm0-96v24c0 6.627-5.373 12-12 12H204c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h200c6.627 0 12 5.373 12 12zm-252 12c0 19.882-16.118 36-36 36s-36-16.118-36-36 16.118-36 36-36 36 16.118 36 36zm0 96c0 19.882-16.118 36-36 36s-36-16.118-36-36 16.118-36 36-36 36 16.118 36 36zm0 96c0 19.882-16.118 36-36 36s-36-16.118-36-36 16.118-36 36-36 36 16.118 36 36z"/></svg>'
address-card = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" class="icon"><path d="M528 32H48C21.5 32 0 53.5 0 80v352c0 26.5 21.5 48 48 48h480c26.5 0 48-21.5 48-48V80c0-26.5-21.5-48-48-48zm0 400H48V80h480v352zM208 256c35.3 0 64-28.7 64-64s-28.7-64-64-64-64 28.7-64 64 28.7 64 64 64zm-89.6 128h179.2c12.4 0 22.4-8.6 22.4-19.2v-19.2c0-31.8-30.1-57.6-67.2-57.6-10.8 0-18.7 8-44.8 8-26.9 0-33.4-8-44.8-8-37.1 0-67.2 25.8-67.2 57.6v19.2c0 10.6 10 19.2 22.4 19.2zM360 320h112c4.4 0 8-3.6 8-8v-16c0-4.4-3.6-8-8-8H360c-4.4 0-8 3.6-8 8v16c0 4.4 3.6 8 8 8zm0-64h112c4.4 0 8-3.6 8-8v-16c0-4.4-3.6-8-8-8H360c-4.4 0-8 3.6-8 8v16c0 4.4 3.6 8 8 8zm0-64h112c4.4 0 8-3.6 8-8v-16c0-4.4-3.6-8-8-8H360c-4.4 0-8 3.6-8 8v16c0 4.4 3.6 8 8 8z"/></svg>'`

**Comment by dawnow** [comment]
> 这是我在这个[网页编辑器](https://svg.wxeditor.com/)里面制作的，下面是date文件夹中svg.toml的所有代码：
> `brand = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 100" class="brand"><path fill="none" d="M-1-1h252v102H-1z"/><g><text font-weight="bold" font-family="'Times New Roman', Times, serif" font-size="72" y="65.071" x="3.028" stroke-width="0" stroke="#000">Dawner</text><text font-style="italic" font-weight="bold" font-family="'Times New Roman', Times, serif" font-size="10" y="92.979" x="61.531" stroke-width="0" stroke="#000">Powerful Mind in Strong Body</text></g></svg>' grin-stars = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512" class="icon"><path d="M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm0 448c-110.3 0-200-89.7-200-200S137.7 56 248 56s200 89.7 200 200-89.7 200-200 200zm105.6-151.4c-25.9 8.3-64.4 13.1-105.6 13.1s-79.6-4.8-105.6-13.1c-9.8-3.1-19.4 5.3-17.7 15.3 7.9 47.2 71.3 80 123.3 80s115.3-32.9 123.3-80c1.6-9.8-7.7-18.4-17.7-15.3zm-227.9-57.5c-1 6.2 5.4 11 11 7.9l31.3-16.3 31.3 16.3c5.6 3.1 12-1.7 11-7.9l-6-34.9 25.4-24.6c4.5-4.5 1.9-12.2-4.3-13.2l-34.9-5-15.5-31.6c-2.9-5.8-11-5.8-13.9 0l-15.5 31.6-34.9 5c-6.2.9-8.9 8.6-4.3 13.2l25.4 24.6-6.1 34.9zm259.7-72.7l-34.9-5-15.5-31.6c-2.9-5.8-11-5.8-13.9 0l-15.5 31.6-34.9 5c-6.2.9-8.9 8.6-4.3 13.2l25.4 24.6-6 34.9c-1 6.2 5.4 11 11 7.9l31.3-16.3 31.3 16.3c5.6 3.1 12-1.7 11-7.9l-6-34.9 25.4-24.6c4.5-4.6 1.8-12.2-4.4-13.2z"/></svg>' list-alt = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="icon"><path d="M464 32H48C21.49 32 0 53.49 0 80v352c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V80c0-26.51-21.49-48-48-48zm-6 400H54a6 6 0 0 1-6-6V86a6 6 0 0 1 6-6h404a6 6 0 0 1 6 6v340a6 6 0 0 1-6 6zm-42-92v24c0 6.627-5.373 12-12 12H204c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h200c6.627 0 12 5.373 12 12zm0-96v24c0 6.627-5.373 12-12 12H204c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h200c6.627 0 12 5.373 12 12zm0-96v24c0 6.627-5.373 12-12 12H204c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h200c6.627 0 12 5.373 12 12zm-252 12c0 19.882-16.118 36-36 36s-36-16.118-36-36 16.118-36 36-36 36 16.118 36 36zm0 96c0 19.882-16.118 36-36 36s-36-16.118-36-36 16.118-36 36-36 36 16.118 36 36zm0 96c0 19.882-16.118 36-36 36s-36-16.118-36-36 16.118-36 36-36 36 16.118 36 36z"/></svg>' address-card = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" class="icon"><path d="M528 32H48C21.5 32 0 53.5 0 80v352c0 26.5 21.5 48 48 48h480c26.5 0 48-21.5 48-48V80c0-26.5-21.5-48-48-48zm0 400H48V80h480v352zM208 256c35.3 0 64-28.7 64-64s-28.7-64-64-64-64 28.7-64 64 28.7 64 64 64zm-89.6 128h179.2c12.4 0 22.4-8.6 22.4-19.2v-19.2c0-31.8-30.1-57.6-67.2-57.6-10.8 0-18.7 8-44.8 8-26.9 0-33.4-8-44.8-8-37.1 0-67.2 25.8-67.2 57.6v19.2c0 10.6 10 19.2 22.4 19.2zM360 320h112c4.4 0 8-3.6 8-8v-16c0-4.4-3.6-8-8-8H360c-4.4 0-8 3.6-8 8v16c0 4.4 3.6 8 8 8zm0-64h112c4.4 0 8-3.6 8-8v-16c0-4.4-3.6-8-8-8H360c-4.4 0-8 3.6-8 8v16c0 4.4 3.6 8 8 8zm0-64h112c4.4 0 8-3.6 8-8v-16c0-4.4-3.6-8-8-8H360c-4.4 0-8 3.6-8 8v16c0 4.4 3.6 8 8 8z"/></svg>'`

下面的图标是我安装你在文档里面的方法添加的，第一个brand是上面那个网页编辑器里面制作的，并在SVGOMG中进行了压缩。

**Comment by dawnow** [comment]
这是brand未压缩之前的代码：
![image](https://user-images.githubusercontent.com/46470508/74519323-6cd38180-4f50-11ea-9430-63f49d82ab89.png)

**Comment by reuixiy** [comment]
看了下，应该是你的 SVG 里面有 `'` 这个符号，解决方法是使用三个而非一个 `'` 符号包裹该 SVG，如下：

```toml
brand = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 100" class="brand"><path fill="none" d="M-1-1h252v102H-1z"/><g><text font-weight="bold" font-family="'Times New Roman', Times, serif" font-size="72" y="65.071" x="3.028" stroke-width="0" stroke="#000">Dawner</text><text font-style="italic" font-weight="bold" font-family="'Times New Roman', Times, serif" font-size="10" y="92.979" x="61.531" stroke-width="0" stroke="#000">Powerful Mind in Strong Body</text></g></svg>'''
```

参见：https://github.com/toml-lang/toml#string

**Comment by dawnow** [comment]
> 看了下，应该是你的 SVG 里面有 `'` 这个符号，解决方法是使用三个而非一个 `'` 符号包裹该 SVG，如下：
> 
> ```toml
> brand = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 100" class="brand"><path fill="none" d="M-1-1h252v102H-1z"/><g><text font-weight="bold" font-family="'Times New Roman', Times, serif" font-size="72" y="65.071" x="3.028" stroke-width="0" stroke="#000">Dawner</text><text font-style="italic" font-weight="bold" font-family="'Times New Roman', Times, serif" font-size="10" y="92.979" x="61.531" stroke-width="0" stroke="#000">Powerful Mind in Strong Body</text></g></svg>'''
> ```
> 
> 参见：https://github.com/toml-lang/toml#string

原来如此，学习了，谢谢！

**Comment by dawnow** [comment]
已解决。
