### ISSUE TITLE
无法以命令更新主题 | Cannot update MemE via `git submodule update --rebase --remote`

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#69]
![image](https://user-images.githubusercontent.com/46470508/75000546-a00a9900-5499-11ea-8288-ba1232c30ccc.png)
没有任何反应，meme文件也未更新

**Comment by reuixiy** [comment]
emmm，不好意思，昨天被我整炸了，我 rebase 了一下，所以不能正常更新了，解决方法见：https://github.com/reuixiy/hugo-theme-meme/commit/7fab5dbb0c57e6a36ed8254097ac114841f1e100#commitcomment-37412911

**Comment by dawnow** [comment]
> emmm，不好意思，昨天被我整炸了，我 rebase 了一下，所以不能正常更新了，解决方法见：[7fab5db#commitcomment-37412911](https://github.com/reuixiy/hugo-theme-meme/commit/7fab5dbb0c57e6a36ed8254097ac114841f1e100#commitcomment-37412911)

OK！
