### ISSUE TITLE
实现PWA过程中遇到的困难：

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#70]
开发者你好，本人纯小白文科生，我在根据您[这篇文章](https://io-oi.me/tech/pwa-via-workbox/)进行博客的PWA设置时遇到了问题。

在完成了安装模块、新建gulpfile.js文件以及sw-template.js文件后，输入你提供的本地测试命令，提示错误。（本人对npm相关命令不了解。。。

![image](https://user-images.githubusercontent.com/46470508/75009987-fcc87c80-54b6-11ea-9991-278a45432f64.png)

另外我注意到博主您的博客仓库中有package.json这个文件，我安装完成模块之后只有package-lock.json文件。不知道是哪个环节出错了。

以下是前两次命令后返回的代码：

`~/blog $ npm install workbox-build gulp gulp-uglify readable-stream uglify-es --save-dev`

![image](https://user-images.githubusercontent.com/46470508/75010168-75c7d400-54b7-11ea-8b15-19ccf8131801.png)

`~/blog $ npm update`

![image](https://user-images.githubusercontent.com/46470508/75010212-8f691b80-54b7-11ea-979a-005685288e42.png)

希望博主能够解答，感谢！

**Comment by reuixiy** [comment]
Windows 不清楚。尝试把 `.` 换为 `node ` 试试；或者直接全局安装模块，将安装模块命令中的 `--save-dev` 换为 `-g`，安装好后，命令直接用 `gulp build`。

**Comment by dawnow** [comment]
用您的方法已经build成功！

![image](https://user-images.githubusercontent.com/46470508/75016173-589a0200-54c5-11ea-9e16-1c943daa3f28.png)

但还需请教一下，您教程中后面的两步（下面两个图）是否已经集成在meme文件中了，是否还需要自己去配置或修改相关文件呢？
![image](https://user-images.githubusercontent.com/46470508/75016315-ab73b980-54c5-11ea-88ec-a6f3bc36957b.png)
![image](https://user-images.githubusercontent.com/46470508/75016332-b75f7b80-54c5-11ea-9a06-2f79afbf4bf2.png)
另外如果需要的话这个custom.styl是不是在blog的assets文件夹里创建呢？

**Comment by reuixiy** [comment]
嗯 这两个主题里面都有 你直接将 `enableServiceWorker` 即可

**Comment by dawnow** [comment]
好的，谢谢。
