### ISSUE TITLE
能否新增一个配置项，来控制是否为目录中的子标题添加序号

### ISSUE THREAD

**Issue by he-sb** [reuixiy/hugo-theme-meme#71]
根据文章内容的不同，有的文章子标题不需要序号，这类文章目前的显示效果没问题，MemE可以自动在生成的目录中添加上序号，比如这样

![图片](https://user-images.githubusercontent.com/26474615/75444073-acad5680-599d-11ea-84e9-e7a9cf78ed2a.png)

但是有些文章子标题需要加上序号，在阅读时体验会好一点，这种情况的话在目录中还是会被加上序号，看起来有点困扰，比如这样

![图片](https://user-images.githubusercontent.com/26474615/75444097-b767eb80-599d-11ea-9dc6-759c33401d98.png)

如果能手动控制是否在目录中为子标题添加序号会方便许多。

**Comment by reuixiy** [comment]
可以，刚好正在[浏览一篇文章](https://ishadeed.com/article/css-counters/)，正想改进下数字的模式（第一级数字结尾有 `.`，子级则无，如 `1.`、`1.1`），可以顺手完成这个需求。

**Comment by he-sb** [comment]
为你点赞！

期望的效果是这样，可以自由控制是否显示序号，若设置为不显示的话，其实目录里单靠缩进也能比较清晰地看出子标题的结构。

这个需求来自于，有时候二级标题想要设置序号来强调顺序，但内部的若干个三级标题之间则不必强调顺序，若强制都有序号的话就有点不太灵活。

不知是否唐突 🙈

**Comment by reuixiy** [comment]
嗯，已经完成了，可每篇文章独立控制。更新主题和 config.toml 测试一下吧～

**Comment by he-sb** [comment]
请收下我膜拜的眼神……
