### ISSUE TITLE
TOC一级标题不显示

### ISSUE THREAD

**Issue by 95eh** [reuixiy/hugo-theme-meme#79]
首先,很喜欢这个主题:) 
当我将toc设为true时,文章顶部的目录没有显示一级标题,不知道是怎么回事

**Comment by reuixiy** [comment]
你好，

如果你要显示一级标题，可以将 [`startLevel`](https://github.com/reuixiy/hugo-theme-meme/blob/dc0c4ef51e1f135be9bd1534805a2e075f0697c2/config-examples/zh-cn/config.toml#L88) 修改为 `1`。

不过，并不建议在文章内用一级标题，因为一级标题为文章标题。所以，文章内还是建议以二级标题开始，这更符合逻辑，也更[有利于 SEO](https://developer.mozilla.org/zh-CN/docs/Glossary/语义#HTML_中的语义)。

**Comment by 95eh** [comment]
谢谢:)
