### ISSUE TITLE
点击缩放过的图片时放大后的位置错误

### ISSUE THREAD

**Issue by FFRaycoder** [reuixiy/hugo-theme-meme#80]
如<https://raycoder.me/p/ulang/>。
点击表情包时（已缩放），图片会向左上移动。

**Comment by he-sb** [comment]
Firefox 74 无法复现，是正常的，怀疑是浏览器兼容问题。

**Comment by ayalhw** [comment]
Chromium 80.0.3987.132
Firefox Nightly  76.0a1.20200316
均未复现

**Comment by reuixiy** [comment]
发现那张表情包有 `style="zoom:15%;"` 属性，原因就在这了吧……你可以将之修改为 `style="width:15%; height:15%"` 来解决。

或者，你可以这样写：

```html
<img src="" class="sticker">
```

然后在 `~/blog/assets/custom/_custom.scss` 中添加：

```css
.sticker {
   width: 15%;
   height: 15%;
}
```

或者，如果你嫌每次都写 HTML 太麻烦，就可以动手写一个 Hugo 的[短代码](https://gohugo.io/templates/shortcode-templates/)，比如新建 `~/blog/layouts/shortcodes/sticker.html`，然后加入以下：

```html
<img src="{{ index .Params 0 }}" class="sticker">
```

然后在文章中这样写：

```
{{< sticker "/images/wtf.jpg" >}}
```

然后就可以开心地优雅地插入表情包了。样式啥的直接在上面提到的 `_custom.scss` 里面定制就行了。

这样做的好处有：

1. 相对简单，不用写 HTML
2. 易于维护，可随时修改模板，可随时更改样式

坏处有：

1. 如果你将来要离开 Hugo，就会很麻烦了，而直接写 HTML 就没有这个麻烦。

**Comment by FFRaycoder** [comment]
好的，已经正常。

**Comment by FFRaycoder** [comment]
我的版本：版本 83.0.4087.0（正式版本）canary （64 位）
