### ISSUE TITLE
Valine评论无法开启

### ISSUE THREAD

**Issue by murongxixi** [reuixiy/hugo-theme-meme#83]
config.toml里设置如下：
    enableComments = true
    # Note: *global settings*
    #       `comments` in post’s Front Matter
    #       has a higher priority than here

    ## Valine
    enableValine = true
    valineAppId = "e2rdxtewsjBdSsDOvKrnP1vS-gzGzoHsz"
    valineAppKey = "wFVB4xCkcyzY6eBBAkc3PYIp"
    valinePlaceholder = "Just go go"
    valineNotify = false
    valineVerify = false
    valinePath = ""
    valineAvatar = "mm"
    valineMeta = ["nick", "mail", "link"]
    valinePageSize = 10
    valineLang = "zh-cn"
    valineVisitor = false
    valineHighlight = true
    avatarForce = false
    valineRecordIP = false
    valineServerURLs = ""
    # Note: https://valine.js.org/

部署到github上后只显示“加载评论”，却没有输入评论的对话框，见如下链接https://murongxixi.github.io/hugo/post/new-start/

看了下网页源代码，只有一段valine.html里的代码：
<script>
    function loadComments() {
        if (typeof Valine === 'undefined') {
            var getScript = (options) => {
                var script = document.createElement('script');
                script.defer = true;
                script.crossOrigin = 'anonymous';
                Object.keys(options).forEach((key) => {
                    script[key] = options[key];
                });
                document.body.appendChild(script);
            };
            getScript({
                src: 'https://unpkg.com/valine/dist/Valine.min.js',
                onload: () => {
                    newValine();
                }
            });
        } else {
            newValine();
        }
    }
    function newValine() {
        new Valine({
            el: '#vcomments',
            appId: 'e2rdxtewsjBdSsDOvKrnP1vS-gzGzoHsz',
            appKey: 'wFVB4xCkcyzY6eBBAkc3PYIp',
            placeholder: 'Just go go',
            notify:  false ,
            verify:  false ,
            path: location.pathname,
            avatar: 'mm',
            meta: ["nick","mail","link"],
            pageSize:  10 ,
            lang: 'zh-cn',
            visitor:  false ,
            highlight:  true ,
            avatarForce:  false ,
            recordIP:  false ,
            serverURLs: ''
        });
    }
</script>

按理说不应该是生成下面这样的div吗？
<div class="post-comment">
<div id="vcomments"></div>
<script src='//unpkg.com/valine/dist/Valine.min.js'></script>

<script type="text/javascript">
new Valine({
el: '#vcomments',
appId: 'e2rdxtewsjBdSsDOvKrnP1vS-gzGzoHsz',
appKey: 'wFVB4xCkcyzY6eBBAkc3PYIp',
notify: 'false',
verify: 'false',
avatar: 'hide',
placeholder: 'Just go go',
visitor: 'true'
});
</script>
</div>

**Comment by reuixiy** [comment]
这是预期行为。

如果你想直接加载的话，可以通过定制实现。

比如：新建 `~/blog/assets/js/custom.js`，加入

```js
if (commentsToggle !== null) {
    loadComments();
    commentsToggle.style = "display: none";
}
```

**Comment by murongxixi** [comment]
可能我没表达清楚，我的问题是现在只有“加载评论”一个button，而且点了还没反应，if (commentsToggle !== null)里面的语句似乎没被执行

**Comment by reuixiy** [comment]
给个在线链接

**Comment by murongxixi** [comment]
https://murongxixi.github.io/hugo/post/new-start/

**Comment by reuixiy** [comment]
注意到你开启了「深色模式」，所以请务必将[配置中的该按钮](https://github.com/reuixiy/hugo-theme-meme/blob/dc0c4ef51e1f135be9bd1534805a2e075f0697c2/config-examples/zh-cn/config.toml#L208-L210)保留。

如果你希望其不显示，可通过配置中的 [`hideThemeToggle`](https://github.com/reuixiy/hugo-theme-meme/blob/dc0c4ef51e1f135be9bd1534805a2e075f0697c2/config-examples/zh-cn/config.toml#L476) 实现。

**Comment by murongxixi** [comment]
问题已解决，多谢大大耐心解答

**Comment by yeyuqiu** [comment]
> 问题已解决，多谢大大耐心解答

楼主怎么解决的，我也碰到了同样的问题
