### ISSUE TITLE
更新 MemE 后某些文字不显示

### ISSUE THREAD

**Issue by Xuezenghuigithub** [reuixiy/hugo-theme-meme#85]
昨天更新了最新版后，很多字（变量）都不显示了，如目录前的序号（已开启 `config.toml` 中的 `enableTOC`、`displayTOCNum`项），版权信息部分的作者、链接、许可，分享项上的提示文字等都不显示。

> 因为我更喜欢之前的字体，暂未应用可变字体，不知和这有无关系？

**Comment by reuixiy** [comment]
看了一下，你的配置文件有点 old 啊，你可以对比一下[最新版](https://github.com/reuixiy/hugo-theme-meme/blob/master/config-examples/zh-cn/config.toml)。

**Comment by Xuezenghuigithub** [comment]
文字不显示问题原来是 i18n 的 默认语言改名字了 😢解决了，谢谢。

但是文章目录的标题已按照 issue #71 中相关内容修改，但还是不显示..

**Comment by reuixiy** [comment]
这个，如果不嫌麻烦的话，可以复制一份最新版的 config.toml，然后重新配置，应该能解决全部问题。

**Comment by Xuezenghuigithub** [comment]
我用 Chrome 开发者工具看到我博客的目录使用的是 `ul` 标签，但是 issue #71 中的是 `ol`，而且你的博客里也是 `ol`。。🥺

**Comment by reuixiy** [comment]
https://github.com/reuixiy/hugo-theme-meme/blob/f873fccff7b41935d2d5abf2f0f9f618b0561e9b/config-examples/zh-cn/config.toml#L61-L90

**Comment by Xuezenghuigithub** [comment]
我已经把最新版的 `config.toml` 复制过来改了，我再看看吧，谢谢了

**Comment by Xuezenghuigithub** [comment]
`Module "meme" is not compatible with this Hugo version; run "hugo mod graph" for more information.`

**Comment by Xuezenghuigithub** [comment]
啊，所有的问题都是因为  Netlify.toml 文件中的 Hugo 版本问题🥺

已解决！
