### ISSUE TITLE
更新后诗意人生主页顶栏与“诗”的间距过小

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#86]
如图所示
![image](https://user-images.githubusercontent.com/46470508/77169258-28f60e00-6af4-11ea-807f-7fcbab621aff.png)

另外，更新主题的命令 `git submodule update --rebase --remote` 仍然无法使用
我用的是第二种方法，并对照example config进行了相关增减。

其次我注意到我的博客顶栏宽度跟您的不一致，我觉得我的顶栏太宽了，不知该如何解决？望解答。❤

**Comment by he-sb** [comment]
补充一个，顶栏内的菜单如何做到不显示图标啊，我对比了下作者的首页和配置文件，是有指定图标的，但按钮却只有文字，尝试手动在配置文件中关闭 `post` 这个参数，可以实现“不显示图标只显示文字”，但按钮文字的字体却比作者的小，配置文件中字号作者是 `16` ，我还设置的是 `18` ，看不懂了 🙈

**Comment by dawnow** [comment]
> 至于顶栏宽度的问题，经过我测试可以通过设置 `siteBrandFontSize` 的大小来改变，但作者的配置文件此参数值为 `2` ，而我设置为相同的值时网站标题字体倒是差不多，顶栏背景却明显要宽一大截。

谢谢，你说的这些我也都尝试过，但是没法做到像一休儿那样美观，另外我发现手机上右上角的那个“折叠”按钮在我的手机上是略微偏上的，不知道你们的有没有这种情况。reuixiy的就没这个问题。
![Screenshot_2020-03-21-00-05-02-395_Chrome](https://user-images.githubusercontent.com/46470508/77182618-05d55980-6b08-11ea-98c5-2c274a41bd81.png)

**Comment by guanqr** [comment]
自定义 css 就可以解决了

**Comment by reuixiy** [comment]
@dawnow @he-sb 往 `_custom.scss` 里面加代码定制即可，参见

- https://github.com/reuixiy/io-oi.me/commit/5087c6fa6f09af5955f7a08285ad66f4f7e43f1a
- https://github.com/reuixiy/io-oi.me/commit/27027ed173a8eb32b91c677f488b17310f0b9ca2

**Comment by dawnow** [comment]
> @dawnow @he-sb 往 `_custom.scss` 里面加代码定制即可，参见
> 
> * [reuixiy/io-oi.me@5087c6f](https://github.com/reuixiy/io-oi.me/commit/5087c6fa6f09af5955f7a08285ad66f4f7e43f1a)
> * [reuixiy/io-oi.me@27027ed](https://github.com/reuixiy/io-oi.me/commit/27027ed173a8eb32b91c677f488b17310f0b9ca2)

已解决，谢谢reuixiy👍

**Comment by he-sb** [comment]
感谢作者，光看 `config.toml` 的修改历史了，忽略了其他的 commit 记录……
