### ISSUE TITLE
顶栏的页面内容的间距过大

### ISSUE THREAD

**Issue by he-sb** [reuixiy/hugo-theme-meme#87]
如下示例，每个页面的顶栏和下方内容间距都是固定的，感觉额头这么大有点不协调，如何修改这个间距的大小呢

![图片](https://user-images.githubusercontent.com/26474615/77244099-800ef680-6c4c-11ea-94e2-84ce853a8e27.png)

![图片](https://user-images.githubusercontent.com/26474615/77244125-b5b3df80-6c4c-11ea-91e6-4afe0419a5f5.png)

**Comment by reuixiy** [comment]
https://developer.mozilla.org/zh-CN/docs/Learn/Getting_started_with_the_web/HTML_basics
https://developer.mozilla.org/zh-CN/docs/Learn/Getting_started_with_the_web/CSS_basics
https://developers.google.com/web/tools/chrome-devtools/css

**Comment by he-sb** [comment]
谢谢，我去学习 🙈
