### ISSUE TITLE
删除白色模式

### ISSUE THREAD

**Issue by samsarapt** [reuixiy/hugo-theme-meme#88]
请问只保留黑色模式要删除哪些代码才能把白色模式全删掉？

**Comment by reuixiy** [comment]
可通过 [`defaultTheme`](https://github.com/reuixiy/hugo-theme-meme/blob/0d14242bfe588efe12c0c11d3cb200c9d45e4eda/config-examples/zh-cn/config.toml#L472) 配置默认模式为深色模式。

如果想完全避免读者的系统设置对此的影响的话，一个简单的解决方法是[定制](https://io-oi.me/tech/documentation-of-hugo-theme-meme/#定制)一下 [themes](https://github.com/reuixiy/hugo-theme-meme/tree/master/assets/scss/themes)。

如果你非要删除，还需你自己尝试，代码这么多，我也不可能一行一行帮你揪出来。

**Comment by reuixiy** [comment]
现在有了一个 `overrideSystemPreferences` 的选项，更新主题后，将之开启并将 defaultTheme 改为 `dark`，最后关闭切换按钮，即可实现「纯深色模式」。

https://github.com/reuixiy/hugo-theme-meme/blob/e781e176e3e73d42e685b3483f497e9d5fc0fab6/config-examples/zh-cn/config.toml#L474-L496

**Comment by zigzagpig** [comment]
棒
