### ISSUE TITLE
report: [markdown code display] not performing well after [change postWidth in config file]

### ISSUE THREAD

**Issue by boholder** [reuixiy/hugo-theme-meme#9]
![img](https://i.ibb.co/YZ2MHcQ/Snipaste-2019-09-19-23-36-02.png)

I changed :  
[languages.zh-cn.params]  
...   
postWidth = 32->45

but markdown code display div's sliding control still behave as 32 size.

Or... should I change another config to deal with this problem?

**Comment by reuixiy** [comment]
Hi @boholder,

Thank you for trying MemE! :smile:

![2019-09-21-12-00-57](https://user-images.githubusercontent.com/28993043/65367696-ef893680-dc67-11e9-9923-85c0f7e41baf.png)

Which browser are you using? It looks great in my browser: `Google Chrome Version 77.0.3865.75 (Official Build) (64-bit)`

**Comment by boholder** [comment]
> Which browser are you using? It looks great in my browser: `Google Chrome Version 77.0.3865.75 (Official Build) (64-bit)`

You are right, I tried chrome and it works.   
My brower is Firefox Quantum 69.0.1 (64-bit) BTW.

**Comment by boholder** [comment]
Wait... I checked again, it works in Firefox, on github page.   
And I quickly tried [hugo sever] command and find out local build also works well.  
I'm confused, maybe that pic I post 2 days ago due to browser cache?  
I don't know the rendering optimization of the browser.  

Whatever, this seems to be just a misunderstanding, sorry for bothering, and thank you for creating such a good theme.
