### ISSUE TITLE
启动时报错了

### ISSUE THREAD

**Issue by spb512** [reuixiy/hugo-theme-meme#92]
$ hugo server -D
Building sites … Built in 52 ms
Error: Error building site: TOCSS: failed to transform "zh/styles/main-rendered.scss" (text/x-scss): resource "scss/scss/main.scss_a059ebc49e8302e6cfbf0e02020b9d85" not found in file cache

**Comment by Pierre-Malherbe** [comment]
Hello i have same issue with my blog.

**Comment by reuixiy** [comment]
I have received a lot of such feedback recently... Do you have an `extended` version of Hugo? You can check this via `hugo version` commend.

**Comment by spb512** [comment]
@reuixiy thank you .I've changed the extended version and the issue has been resolved.
