### ISSUE TITLE
bug : 点击目录中的按钮或其他页内跳转按钮后跳转的行会被挡住

### ISSUE THREAD

**Issue by he-sb** [reuixiy/hugo-theme-meme#93]
症状为：

点击目录中或文章内自定义的页内跳转链接后，跳转到的对应行会被顶栏挡住，如这个例子

![图片](https://user-images.githubusercontent.com/26474615/77783989-bf967200-7094-11ea-88a7-6706fceb678a.png)

跳转到的对应标题被顶栏挡住了

**Comment by reuixiy** [comment]
这个比较难，暂时的解决方法是开启 [smooth scroll](https://github.com/reuixiy/hugo-theme-meme/blob/a323e45d5ece0afb741fe90b495a723698600b8c/config-examples/zh-cn/config.toml#L1248)，然后[定制](https://io-oi.me/tech/documentation-of-hugo-theme-meme/#定制)一下 [smooth-scroll.html](https://github.com/reuixiy/hugo-theme-meme/blob/master/layouts/partials/third-party/smooth-scroll.html)：

```diff
<script src="https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>

<script>
    var scroll = new SmoothScroll('a[href*="#"]', {
+       speed: 1,
        speedAsDuration: true,
        header: '[data-scroll-header]'
    });
</script>
```

**Comment by he-sb** [comment]
ok ，我去试试先，感谢一休儿~

**Comment by he-sb** [comment]
测试了一下，仅开启 `smooth scroll` ，不定制的话也可以正常实现子标题显示在顶栏下方， Firefox 74.0.1 和 Chrome 80.0.3987.163 都没问题。

当然定制后也试了可以，那么使用不使用定制有什么区别呢

![图片](https://user-images.githubusercontent.com/26474615/78499377-e6366600-7782-11ea-80c1-51e792a1522b.png)

**Comment by he-sb** [comment]
而且这个速度我改成了 500 也没什么区别，不知为何……

**Comment by reuixiy** [comment]
区别是：是否有个动画的效果。

我还以为你关闭 `smoothScroll` 就是为了不要这个动画呢。

不应该没区别啊，可能是浏览器缓存的原因吧，刷新一下试试。

**Comment by he-sb** [comment]
刚从 Chrome 转到 Firefox 的时候，Firefox 默认是打开平滑滚动功能的，上下翻页的感觉十分难受，果断关了，所以后来配置 MemE 主题的时候看到有这个 `smoothscroll` 就直接设为 `false` 了……

刚才测试是本地 `hugo server` 测试的，不过应该不是缓存的问题，因为看不出区别后我又在 Chrome 开了个访客模式来看，确实没区别。

不过无所谓了，没有动画效果也好，简洁一点哈哈，不太喜欢这些花里胡哨的 🤣

**Comment by he-sb** [comment]
刚反应过来，那么说这个 bug 就是没有开启 `smoothscroll` 导致的是吧，只要开启的话就不会有这个症状了。

**Comment by reuixiy** [comment]
可以这么说

**Comment by he-sb** [comment]
明白了，那我先开着，谢谢啦
