### ISSUE TITLE
[question]我该如何在about页面中开启评论功能？

### ISSUE THREAD

**Issue by blleng** [reuixiy/hugo-theme-meme#94]
meme主题似乎只支持在post中开启评论功能，而无法在其他页面开启？

**Comment by reuixiy** [comment]
Front Matter 中 `comments: true`

**Comment by blleng** [comment]
> Front Matter 中 `comments: true`

config中的配置不是全局的吗...

**Comment by blleng** [comment]
刚刚试过，似乎没有作用。。。😫

**Comment by reuixiy** [comment]
https://github.com/reuixiy/hugo-theme-meme/issues/32

**Comment by blleng** [comment]
抱歉，我一直写成了`comment: true`。。。
