### ISSUE TITLE
子模块在Netlify上生成错误

### ISSUE THREAD

**Issue by FFRaycoder** [reuixiy/hugo-theme-meme#96]
如<https://raycoder.me/p/cf-worker-proxy/>等文章，我在本地调试是OK的，可能因为本地Hugo指令是用本地文件进行渲染。但是放到Netlify上使用子模块时，我所有的修改就无效了。博客源码<https://github.com/FFRaycoder/rays>

**Comment by FFRaycoder** [comment]
我这修改了comments.html也没用

**Comment by FFRaycoder** [comment]
就是在git commit时没显示meme文件夹中的修改，是我Git的原因吗？

**Comment by reuixiy** [comment]
应该是你使用的 Cloudflare 的锅。

检查方法，将[这些代码](https://github.com/FFRaycoder/rays/blob/6e2d626cce8878d94750a72d4a3487a3af4e2e9a/netlify.toml#L16-L19)注释，然后访问 <https://rb.netlify.com>。

如果正常，就说明 Netlify 没问题。

**Comment by FFRaycoder** [comment]
已经删除了，没有变化。<https://rb.netlify.com/p/cf-worker-proxy/>
子模块的更新没有被提交到commit里。

**Comment by FFRaycoder** [comment]
真是奇怪了。真的是Git的锅。
```bash
$ git rm -rf --cached themes/meme
```
就可以了。

**Comment by FFRaycoder** [comment]
Issue closed.
