### ISSUE TITLE
feature request : 分类页面增加折叠按钮

### ISSUE THREAD

**Issue by he-sb** [reuixiy/hugo-theme-meme#97]
现有的配置文件只能实现分类页面“显示”或“不显示”各个分类下的文章，如果设置为不显示，那么需要点击分类后经过一次跳转才能查看该分类下所有文章；如果显示，文章数多了后靠下的分类要滚动好久才能看到。

希望分类旁边可以增加一个开关，点击后展开显示该分类下的文章，比较灵活。

**Comment by palant** [comment]
Is this still necessary with #147 resolved? That's exactly the issue I tried to address there.

**Comment by reuixiy** [comment]
Not exactly. It can be solved by the same way, but what @he-sb means is related to `partials/pages/tree-categories.html` and `partials/pages/tree-sections.html`, which is controlled by [`enableTree`](https://github.com/reuixiy/hugo-theme-meme/blob/db102eb5b64af11c9cf9a0697ed312ea86aeca22/config-examples/en/config.toml#L394-L401).

**Comment by palant** [comment]
Ah, I see, a different type of page then.
