### ISSUE TITLE
引用文字的样式

### ISSUE THREAD

**Issue by dawnow** [reuixiy/hugo-theme-meme#99]
reuixiy你好，我注意到你这篇文章——[庄子和圣奥古斯丁](https://io-oi.me/life/chuang-tzu-and-saint-augustine/)中的引文样式是下图这样：
<img width="960" alt="2020-04 04-162415" src="https://user-images.githubusercontent.com/46470508/78422396-8744f400-7691-11ea-9e39-a394facf0c7e.png">
而我的是这样的：
![image](https://user-images.githubusercontent.com/46470508/78422413-ab083a00-7691-11ea-93f0-198955ebf2e7.png)
请问要如何才能实现你那种只降低文字饱和度的呈现形式呢？希望能够解答，谢谢！
（难道是开了缩进后就是这样吗？🙄

**Comment by reuixiy** [comment]
是的

**Comment by dawnow** [comment]
> 是的

Thanks！🎈才发现这个，MemE好厉害！
